act_code: '25972'
requisite: III шақырылған Шығыс Қазақстан облысы Қатонқарағай аудандық мәслихатының 2005 жылғы 25 наурыздағы № 11/13-III шешімі. Шығыс Қазақстан облысының Әділет департаментінде 2005 жылғы 7 сәуірде № 2265 тіркелді
title:
  rus: Катонқарағай ауданының ауылдарын көркейту, санитарлық жағдайы, жер мен жасыл өскіндерді қорғауды қамтамасыз етудің Ережелерін бекіту туралы
  kaz: Катонқарағай ауданының ауылдарын көркейту, санитарлық жағдайы, жер мен жасыл өскіндерді қорғауды қамтамасыз етудің Ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-03-25
approved_by:
- '157014000002'
version_date:
  kaz: 2005-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/25972/kaz/25.03.2005
