act_code: '170902'
requisite: Решение Восточно-Казахстанского областного маслихата от 22 августа 2022 года № 18/156-VІІ
title:
  rus: Об утверждении Правил содержания и выгула домашних животных в Восточно-Казахстанской области, Правил отлова, временного содержания и умерщвления животных в Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысында үй жануарларын ұстаудың және серуендетудің қағидаларын, Шығыс Қазақстан облысында жануарларды аулаудың, уақытша ұстаудың және жансыздандырудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-22
approved_by:
- '157000000002'
version_date:
  kaz: 2022-08-22
  rus: 2022-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/170902/kaz/22.08.2022
  rus: https://zan.gov.kz/client/#!/doc/170902/rus/22.08.2022
