act_code: '119915'
requisite: Решение акима Глубоковского района Восточно-Казахстанской области от 24 марта 2018 года № 03. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 29 марта 2018 года № 5575. Утратило силу решением акима Глубоковского района Восточно-Казахстанской области от 22 апреля 2021 года № 03 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера
  kaz: Табиғи сипаттағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-24
approved_by:
- '157010000003'
version_date:
  kaz: 2018-03-24
  rus: 2018-03-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/119915/kaz/24.03.2018
  rus: https://zan.gov.kz/client/#!/doc/119915/rus/24.03.2018
