act_code: '139111'
requisite: Решение маслихата Абайского района Восточно-Казахстанской области от 15 января 2020 года № 43/8-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 января 2020 года № 6702. Утратило силу решением Абайского районного маслихата Восточно-Казахстанской области от 28 декабря 2020 года № 58/13-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Каскабулакского сельского округа на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Қасқабұлақ ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-15
approved_by:
- '157006000002'
version_date:
  kaz: 2020-04-13
  rus: 2020-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/139111/kaz/13.04.2020
  rus: https://zan.gov.kz/client/#!/doc/139111/rus/13.04.2020
caused_by:
  code: '141898'
  requisite: Решение маслихата Абайского района Восточно-Казахстанской области от 13 апреля 2020 года № 46/7-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 апреля 2020 года № 6914. Утратило силу решением Абайского районного маслихата Восточно-Казахстанской области от 28 декабря 2020 года № 58/13-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Абайского районного маслихата от 15 января 2020 года № 43/8-VI «О бюджете Каскабулакского сельского округа на 2020-2022 годы»
    kaz: Абай аудандық мәслихатының 2020 жылғы 15 қаңтардағы № 43/8-VI «2020-2022 жылдарға арналған Қасқабұлақ ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141898/rus
