act_code: '85742'
requisite: Решение от 24.12.2014 №36/2-V, Маслихат Зыряновского района. Утратило силу решением маслихата Зыряновского района Восточно-Казахстанской области от 23.12.2015 № 52/2-V
title:
  rus: О бюджете Зыряновского района на 2015-2017 годы
  kaz: 2015-2017  жылдарға арналған Зырян ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '157013000002'
version_date:
  kaz: 2015-06-09
  rus: 2015-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/85742/kaz/09.06.2015
  rus: https://zan.gov.kz/client/#!/doc/85742/rus/09.06.2015
caused_by:
  code: '90789'
  requisite: Решение №43/6-V от 09.06.2015, Маслихат Зыряновского района. Утратило силу решением маслихата Зыряновского района Восточно-Казахстанской области от 23.12.2015 № 52/2-V
  title:
    rus: О внесении изменений в решение маслихата Зыряновского района от  24  декабря 2014 года № 36/2-V «О бюджете Зыряновского  района на 2015-2017 годы»
    kaz: «2015-2017 жылдарға арналған Зырян ауданының бюджеті туралы» Зырян ауданының мәслихатының 2014 жылғы 24 желтоқсандағы № 36/2-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/90789/rus
