act_code: '109473'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 22 декабря 2016 года № 9/73-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 26 января 2017 года № 4846. Действие решения приостановлено решением Жарминского районного маслихата от 5 марта 2019 года № 30/256-VI. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 18 ноября 2019 года № 40/326-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на захоронение твердых бытовых отходов по Жарминскому району
  kaz: Жарма ауданыны бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын және тұрмыстық қатты қалдықтарын көму тарифтерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-22
approved_by:
- '157011000002'
version_date:
  kaz: 2019-03-05
  rus: 2019-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/109473/kaz/05.03.2019
  rus: https://zan.gov.kz/client/#!/doc/109473/rus/05.03.2019
caused_by:
  code: '129704'
  requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 5 марта 2019 года № 30/256-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 марта 2019 года № 5777. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 18 ноября 2019 года № 40/326-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О приостановлении действия решения Жарминского районного маслихата от 22 декабря 2016 года № 9/73-VI «Об утверждении норм образования и накопления коммунальных отходов, тарифов на захоронение твердых бытовых отходов по Жарминскому району»
    kaz: Жарма аудандық мәслихатының 2016 жылғы 22 желтоқсандағы № 9/73-VI «Жарма ауданыны бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын және тұрмыстық қатты қалдықтарын көму тарифтерін бекіту туралы» шешімінің қолданылуын тоқтата тұру туралы
  link: https://zan.gov.kz/client/#!/doc/129704/rus
