act_code: '56475'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 29 декабря 2010 года № 28/2-IV. Зарегистрировано управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 31 декабря 2010 года за № 5-9-142. Прекращено действие по истечении срока действия (письмо Глубоковского районного маслихата от 30 декабря 2011 года № 332)
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-29
approved_by:
- '157010000002'
version_date:
  kaz: 2011-03-18
  rus: 2011-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/56475/kaz/18.03.2011
  rus: https://zan.gov.kz/client/#!/doc/56475/rus/18.03.2011
caused_by:
  code: '57854'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 18 марта 2011 года № 29/5-IV. Зарегистрировано управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 30 марта 2011 года за № 5-9-150. Прекращено действие по истечении срока действия (письмо Глубоковского районного маслихата от 30 декабря 2011 года № 332)
  title:
    rus: О внесении изменений и дополнений в решение от 29 декабря 2010 года № 28/2-IV "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" 2010 жылғы 29 желтоқсандағы № 28/2-IV шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/57854/rus
