act_code: '165311'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 24 декабря 2021 года № 10/197-VII
title:
  rus: О бюджете Карагашского сельского округа Аягозского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Аягөз ауданының Қарағаш ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '157007000002'
version_date:
  kaz: 2022-11-04
  rus: 2022-11-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/165311/kaz/04.11.2022
  rus: https://zan.gov.kz/client/#!/doc/165311/rus/04.11.2022
caused_by:
  code: '174044'
  requisite: Решение Аягозского районного маслихата области Абай от 4 ноября 2022 года № 18/339-VII
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 24 декабря 2021 года № 10/197-VIІ «О бюджете Карагашского сельского округа Аягозского района на 2022-2024 годы»
    kaz: Аягөз аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 10/197-VІІ «2022-2024 жылдарға арналған Аягөз ауданының Қарағаш ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174044/rus
