act_code: '152326'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/545-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 5 января 2021 года № 8315
title:
  rus: О бюджете Мамырсуского сельского округа Аягозского района на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Аягөз ауданының Мамырсу ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '157007000002'
version_date:
  kaz: 2020-12-25
  rus: 2020-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/152326/kaz/25.12.2020
  rus: https://zan.gov.kz/client/#!/doc/152326/rus/25.12.2020
