act_code: '121118'
requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 30 марта 2018 года № 27/8-VI. Зарегистрировано Управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 19 апреля 2018 года № 5-12-152. Утратило силу решением маслихата района Алтай Восточно-Казахстанской области от 26 июля 2022 года № 19/3-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения района Алтай
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Алтай ауданының пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-30
approved_by:
- '157013000002'
version_date:
  kaz: 2020-01-01
  rus: 2020-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/121118/kaz/01.01.2020
  rus: https://zan.gov.kz/client/#!/doc/121118/rus/01.01.2020
caused_by:
  code: '137086'
  requisite: Решение маслихата района Алтай Восточно-Казахстанской области от 3 декабря 2019 года № 57/3-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 18 декабря 2019 года № 6400. Утратило силу решением маслихата района Алтай Восточно-Казахстанской области от 26 июля 2022 года № 19/3-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата Зыряновского района от 30 марта 2018 года № 27/8-VI «О повышении базовых ставок земельного налога и ставок единого земельного налога на неиспользуемые земли сельскохозяйственного назначения»
    kaz: Зырян ауданының мәслихатының 2018 жылғы 30 наурыздағы № 27/8-VІ «Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығы мөлшерлемелерін жоғарылату туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137086/rus
