act_code: '229078'
requisite: Решение маслихата района Самар Восточно-Казахстанской области от 18 августа 2026 года № 34-4/VIII
title:
  rus: Об утверждении Положения о государственном учреждении «Аппарат маслихата района Самар» Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысы «Самар ауданы мәслихатының аппараты» мемлекеттік мекемесі туралы  ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-18
approved_by:
- '157021000002'
version_date:
  kaz: 2026-08-18
  rus: 2026-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/229078/kaz/18.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229078/rus/18.08.2026
