act_code: '205745'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 27 декабря 2024 года № 25/2-VIII
title:
  rus: О бюджете Акжарского сельского округа Тарбагатайского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Тарбағатай ауданы Ақжар ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '157017000002'
version_date:
  kaz: 2025-06-30
  rus: 2025-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/205745/kaz/30.06.2025
  rus: https://zan.gov.kz/client/#!/doc/205745/rus/30.06.2025
caused_by:
  code: '211869'
  requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 30 июня 2025 года № 30/7-VIII
  title:
    rus: О внесении изменений в решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 27декабря 2024 года №25/2-VIII  «О бюджете Акжарского сельского округа Тарбагатайского района на 2025-2027 годы»
    kaz: Шығыс Қазақстан облысы Тарбағатай аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 25/2-VIII «2025-2027 жылдарға арналған Тарбағатай ауданы Ақжар ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211869/rus
