act_code: '100604'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 25 февраля 2016 года № 50/276-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 28 марта 2016 года № 4447. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 17 июля 2020 года № 54/394-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций
  kaz: Жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-25
approved_by:
- '157003000002'
version_date:
  kaz: 2019-12-06
  rus: 2019-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/100604/kaz/06.12.2019
  rus: https://zan.gov.kz/client/#!/doc/100604/rus/06.12.2019
caused_by:
  code: '137306'
  requisite: Решение маслихата города Семей Восточно-Казахстанской области от 6 декабря 2019 года № 46/306-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 23 декабря 2019 года № 6423. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 17 июля 2020 года № 54/394-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Семей № 50/276-V от 25 февраля 2016 года «О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций»
    kaz: Семей қаласы мәслихатының «Жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізу тәртібін қосымша реттеу туралы» «2016 жылғы 25 ақпандағы № 50/276-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137306/rus
