act_code: '152347'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/535-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 5 января 2021 года № 8298
title:
  rus: О бюджете Байкошкарского сельского округа Аягозского района на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Аягөз ауданының Байқошқар ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '157007000002'
version_date:
  kaz: 2021-05-18
  rus: 2021-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/152347/kaz/18.05.2021
  rus: https://zan.gov.kz/client/#!/doc/152347/rus/18.05.2021
caused_by:
  code: '156126'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 18 мая 2021 года № 5/67-VIІ. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 мая 2021 года № 22796
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 25 декабря 2020 года № 55/535-VI «О бюджете Байкошкарского сельского округа Аягозского района на 2021-2023 годы»
    kaz: Аягөз аудандық мәслихатының 2020 жылғы 25 желтоқсандағы № 55/535-VІ «2021-2023 жылдарға арналған Аягөз ауданының Байқошқар ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156126/rus
