act_code: '128379'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 21 декабря 2018 года № 28/238-VI. Зарегистрировано Управлением юстиции Жарминского района Департамента юстиции Восточно-Казахстанской области 28 декабря 2018 года № 5-10-162. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 1 апреля 2020 года № 44/388-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О бюджете Жарминского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Жарма ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '157011000002'
version_date:
  kaz: 2019-11-18
  rus: 2019-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/128379/kaz/18.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128379/rus/18.11.2019
caused_by:
  code: '136280'
  requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 18 ноября 2019 года № 40/325-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 25 ноября 2019 года № 6301. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 1 апреля 2020 года № 44/388-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 21 декабря 2018 года № 28/238-VI «О бюджете Жарминского района на 2019-2021 годы»
    kaz: Жарма аудандық мәслихатының 2018 жылғы 21 желтоқсандағы № 28/238-VI «2019-2021 жылдарға арналған Жарма ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136280/rus
