act_code: '56633'
requisite: Шығыс Қазақстан облысы Бесқарағай аудандық мәслихатының 2010 жылғы 28 желтоқсандағы № 27/2-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Бесқарағай ауданындағы Әділет басқармасында 2011 жылғы 11 қаңтарда № 5-7-88 тіркелді. Күші жойылды - Шығыс Қазақстан облысы Бесқарағай аудандық мәслихатының 2011 жылғы 21 желтоқсандағы № 38/7-IV шешімімен
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-28
approved_by:
- '157009000002'
version_date:
  kaz: 2010-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/56633/kaz/28.12.2010
