act_code: '56633'
requisite: Шығыс Қазақстан облысы Бесқарағай аудандық мәслихатының 2010 жылғы 28 желтоқсандағы № 27/2-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Бесқарағай ауданындағы Әділет басқармасында 2011 жылғы 11 қаңтарда № 5-7-88 тіркелді. Күші жойылды - Шығыс Қазақстан облысы Бесқарағай аудандық мәслихатының 2011 жылғы 21 желтоқсандағы № 38/7-IV шешімімен
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-28
approved_by:
- '157009000002'
version_date:
  kaz: 2011-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56633/kaz/14.11.2011
caused_by:
  code: '61462'
  requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 14 ноября 2011 года № 36/1-IV. Зарегистрировано Управлением юстиции Бескарагайского района Департамента юстиции Восточно-Казахстанской области 22 ноября 2011 года за № 5-7-104. Утратило силу решением Бескарагайского районного маслихата Восточно-Казахстанской области от 21 декабря 2011 года № 38/7-IV
  title:
    rus: О внесении изменений в решение от 28 декабря 2010 года № 27/2-IV "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" 2010 жылғы 28 желтоқсандағы № 27/2-IV шешімге өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/61462/rus
