act_code: '85634'
requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 23 декабря 2014 года N 29-2. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 06 января 2015 года N 3612
title:
  rus: О бюджете Зайсанского района на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған Зайсан ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '157012000002'
version_date:
  kaz: 2015-10-19
  rus: 2015-10-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/85634/kaz/19.10.2015
  rus: https://zan.gov.kz/client/#!/doc/85634/rus/19.10.2015
caused_by:
  code: '96250'
  requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 19 октября 2015 года N 39-1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 22 октября 2015 года N 4188. Утратило силу - решением Зайсанского районного маслихата Восточно-Казахстанской области от 23 декабря 2015 года № 41-1
  title:
    rus: О внесении изменений в решение Зайсанского районного маслихата от 23 декабря 2014 года № 29-2 «О бюджете Зайсанского района  на 2015-2017 годы»
    kaz: «2015-2017 жылдарға арналған Зайсан ауданының бюджеті туралы» 2014 жылғы 23 желтоқсандағы № 29-2 Зайсан аудандық мәслихатының шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96250/rus
