act_code: '118952'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 9 февраля 2018 года № 19/138-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 23 февраля 2018 года № 5490. Возобновлено действие решением Аягозского районного маслихата Восточно-Казахстанской области от 27 июня 2019 года № 39/262-VI. Действие решения приостановлено решением Аягозского районного маслихата от 14 апреля 2020 года № 46/367-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования). Утратило силу решением Аягозского районного маслихата области Абай от 16 января 2023 года № 21/429-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении тарифов на сбор, вывоз и захоронение твердых бытовых отходов в городе Аягоз и поселке Актогай Аягозского района
  kaz: Аягөз ауданының Аягөз қаласындағы және Ақтоғай кентіндегі тұрмыстық қатты қалдықтарды жинауға, әкетуге және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-09
approved_by:
- '157007000002'
version_date:
  kaz: 2019-06-27
  rus: 2019-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/118952/kaz/27.06.2019
  rus: https://zan.gov.kz/client/#!/doc/118952/rus/27.06.2019
caused_by:
  code: '133275'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 27 июня 2019 года № 39/262-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 июля 2019 года № 6072. Утратило силу решением Аягозского районного маслихата области Абай от 16 января 2023 года № 21/428-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 9 февраля 2018 года № 19/138-VI «Об утверждении тарифов на сбор, вывоз и захоронение твердых бытовых отходов в Аягозском районе»
    kaz: Аягөз аудандық мәслихатының 2018 жылғы 9 ақпандағы № 19/138-VІ «Аягөз ауданындағы тұрмыстық қатты қалдықтарды жинауға, әкетуге және көмуге арналған тарифтерді бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133275/rus
