act_code: '164464'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 28 декабря 2021 года № 11/202-VII
title:
  rus: О бюджете посёлка Суыкбулак Жарминского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Жарма ауданы Суықбұлақ кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '157011000002'
version_date:
  kaz: 2022-11-21
  rus: 2022-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/164464/kaz/21.11.2022
  rus: https://zan.gov.kz/client/#!/doc/164464/rus/21.11.2022
caused_by:
  code: '175871'
  requisite: Решение Жарминского районного маслихата области Абай от 21 ноября 2022 года № 22/345-VII
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 28 декабря 2021 года № 11/202-VII «О бюджете поселка Суыкбулак Жарминского района на 2022-2024 годы»
    kaz: «2022-2024 жылдарға арналған Жарма ауданы Суықбұлақ кентінің бюджеті туралы» Жарма аудандық мәслихатының 2021 жылғы 28 желтоқсандағы №11/202-VII шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175871/rus
