act_code: '57657'
requisite: Решение акима Аягозского района Восточно-Казахстанской области от 1 марта 2011 года № 02. Зарегистрировано управлением юстиции Аягозского района Департамента юстиции Восточно-Казахстанской области 14 марта 2011 года за № 5-6-131. Утратило силу - постановлением акимата Аягозского района от 4 мая 2011 года № 522
title:
  rus: Об образовании избирательных участков по выборам Президента Республики Казахстан на территории Аягозского района
  kaz: Қазақстан Республикасы Президентінің сайлауы бойынша Аягөз ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-01
approved_by:
- '157007000001'
version_date:
  kaz: 2011-03-01
  rus: 2011-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/57657/kaz/01.03.2011
  rus: https://zan.gov.kz/client/#!/doc/57657/rus/01.03.2011
