act_code: '55507'
requisite: Шығыс Қазақстан облысы Тарбағатай аудандық мәслихатының 2010 жылғы 27 қазандағы № 24-7 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Тарбағатай аудандық әділет басқармасында 2010 жылғы 23 қарашада № 5-16-102 тіркелді. Күші жойылды - Тарбағатай аудандық мәслихатының 2011 жылғы 21 желтоқсандағы № 33-5 шешімімен
title:
  rus: Бір жолғы талондардың құны туралы
  kaz: Бір жолғы талондардың құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-27
approved_by:
- '157017000002'
version_date:
  kaz: 2010-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/55507/kaz/27.10.2010
