act_code: '8304'
requisite: Решение акима Восточно-Казахстанской области от 9 января 2001 года № 973. Зарегистрировано управлением юстиции Восточно-Казахстанской области 28 февраля 2001 года за № 445. Утратило силу решением акима Восточно-Казахстанской области от 13 мая 2004 года № 88
title:
  rus: О проведении приписки граждан 1984 года рождения к призывным участкам в 2001 году
  kaz: 1984 жылы туған азаматтарды 2001 жылы шақыру учаскелерiне тiркеудi жүргiзу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-01-09
approved_by:
- '157000000001'
version_date:
  kaz: 2001-01-09
  rus: 2001-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/8304/kaz/09.01.2001
  rus: https://zan.gov.kz/client/#!/doc/8304/rus/09.01.2001
