act_code: '137764'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 23 декабря 2019 года № 37/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 31 декабря 2019 года № 6470. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 28 декабря 2020 года № 55/2-VI (вводится в действие с 01.01.2021)
title:
  rus: О Глубоковском районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Глубокое аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-23
approved_by:
- '157010000002'
version_date:
  kaz: 2020-09-04
  rus: 2020-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/137764/kaz/04.09.2020
  rus: https://zan.gov.kz/client/#!/doc/137764/rus/04.09.2020
caused_by:
  code: '146488'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 4 сентября 2020 года № 48/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 18 сентября 2020 года № 7551. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 28 декабря 2020 года № 55/2-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Глубоковского районного маслихата от 23 декабря 2019 года № 37/2-VI «О Глубоковском районном бюджете на 2020-2022 годы»
    kaz: Глубокое аудандық мәслихатының 2019 жылғы 23 желтоқсандағы № 37/2-VІ «2020-2022 жылдарға арналған Глубокое аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146488/rus
