act_code: '44177'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 9 февраля 2009 года № 16-10-IV. Зарегистрировано в Управлении юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 10 февраля 2009 года за № 5-8-74. Утратило силу решением Бородулихинского районного маслихата Восточно-Казахстанской области от 17 марта 2010 года № 25-3-IV
title:
  rus: Об утверждении Правил предоставления социально защищаемым слоям населения Бородулихинского района жилищной помощи на возмещение затрат приобретенного топлива и оплату жилищно-коммунальных услуг
  kaz: Бородулиха ауданы халқының әлеуметтік қорғалатын тобына сатып алған көмірге шыққан шығындарын өтеу және тұрғын үй-коммуналдық қызметтерге ақы төлеуі үшін тұрғын үй көмегін беру ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-02-09
approved_by:
- '157008000002'
version_date:
  kaz: 2009-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/44177/kaz/28.04.2009
