act_code: '44177'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 9 февраля 2009 года № 16-10-IV. Зарегистрировано в Управлении юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 10 февраля 2009 года за № 5-8-74. Утратило силу решением Бородулихинского районного маслихата Восточно-Казахстанской области от 17 марта 2010 года № 25-3-IV
title:
  rus: Об утверждении Правил предоставления социально защищаемым слоям населения Бородулихинского района жилищной помощи на возмещение затрат приобретенного топлива и оплату жилищно-коммунальных услуг
  kaz: Бородулиха ауданы халқының әлеуметтік қорғалатын тобына сатып алған көмірге шыққан шығындарын өтеу және тұрғын үй-коммуналдық қызметтерге ақы төлеуі үшін тұрғын үй көмегін беру ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-02-09
approved_by:
- '157008000002'
version_date:
  rus: 2009-04-21
source:
  rus: https://zan.gov.kz/client/#!/doc/44177/rus/21.04.2009
caused_by:
  code: '45503'
  requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 21 апреля 2009 года № 17-9-IV. Зарегистрировано Управлением юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 28 апреля 2009 года за № 5-8-87. Утратило силу решением Бородулихинского районного маслихата Восточно-Казахстанской области от 23 ноября 2012 года № 9-3-V
  title:
    rus: О внесении изменений в некоторые решения Бородулихинского районного маслихата
    kaz: Бородулиха аудандық мәслихатының кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45503/rus
