act_code: '135508'
requisite: Решение акима Алмасайского сельского округа Уланского района Восточно-Казахстанской области от 18 октября 2019 года № 1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 23 октября 2019 года № 6219
title:
  rus: О присвоении наименований безымянным улицам села Сарыозек Алмасайского сельского округа
  kaz: Ұлан ауданы Алмасай ауылдық округінің Сарыөзек ауылында атауы жоқ көшелеріне атауларын беру туралы.
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-18
approved_by:
- '157018004002'
version_date:
  kaz: 2019-10-18
  rus: 2019-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/135508/kaz/18.10.2019
  rus: https://zan.gov.kz/client/#!/doc/135508/rus/18.10.2019
