act_code: '193286'
requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 26 декабря 2023 года № 14/12-VIII
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Калжырскому сельскому округу на 2023-2024  годы
  kaz: Қалжыр ауылдық округі бойынша жайылымдарды басқару және оларды пайдалану жөніндегі 2023-2024 жылдарға арналған жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '157016000002'
version_date:
  kaz: 2023-12-26
  rus: 2023-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/193286/kaz/26.12.2023
  rus: https://zan.gov.kz/client/#!/doc/193286/rus/26.12.2023
