act_code: '146586'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 10 сентября 2020 года № 49/466-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 22 сентября 2020 года № 7559. Утратило силу решением Жарминского районного маслихата области Абай от 28 августа 2024 года № 15/290-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Жарминском районе
  kaz: Жарма ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-10
approved_by:
- '157011000002'
version_date:
  kaz: 2021-11-11
  rus: 2021-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/146586/kaz/11.11.2021
  rus: https://zan.gov.kz/client/#!/doc/146586/rus/11.11.2021
caused_by:
  code: '160278'
  requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 11 ноября 2021 года № 9/113-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 ноября 2021 года № 25200. Утратило силу решением Жарминского районного маслихата области Абай от 28 августа 2024 года № 15/290-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 10 сентября 2020 года № 49/466-VI «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: Жарма аудандық мәслихатының 2020 жылғы 10 қыркүйектегі № 49/466-VI «Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау Қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160278/rus
