act_code: '195160'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 29 марта 2024 года № 130
title:
  rus: Об утверждении Регламента собрания местного сообщества по Уланскому району
  kaz: Ұлан ауданы бойынша жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-29
approved_by:
- '157018000002'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/195160/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195160/rus/29.03.2024
