act_code: '85855'
requisite: Решение Абайского районного маслихата Восточно-Казахстанской области от 24 декабря 2014 года № 25/3-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 января 2015 года № 3626. Утратило силу - решением маслихата Абайского района Восточно-Казахстанской области от 23.12.2015 № 33/3-V
title:
  rus: О бюджете Абайского района  на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған   Абай ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '157006000002'
version_date:
  kaz: 2015-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/85855/kaz/23.12.2015
caused_by:
  code: '97372'
  requisite: Решение маслихата Абайского района Восточно-Казахстанской области от 23 декабря 2015 года № 33/3-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 12 января 2016 года № 4322. Утратило силу - решением маслихата Абайского района Восточно-Казахстанской области от 23 декабря 2016 года № 8/3-VI
  title:
    rus: О бюджете Абайского района на 2016-2018 годы
    kaz: 2016-2018 жылдарға арналған Абай ауданының бюджеті туралы
  link: https://zan.gov.kz/client/#!/doc/97372/rus
