act_code: '85855'
requisite: Решение Абайского районного маслихата Восточно-Казахстанской области от 24 декабря 2014 года № 25/3-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 января 2015 года № 3626. Утратило силу - решением маслихата Абайского района Восточно-Казахстанской области от 23.12.2015 № 33/3-V
title:
  rus: О бюджете Абайского района  на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған   Абай ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '157006000002'
version_date:
  kaz: 2015-04-08
  rus: 2015-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/85855/kaz/08.04.2015
  rus: https://zan.gov.kz/client/#!/doc/85855/rus/08.04.2015
caused_by:
  code: '88734'
  requisite: Решение Абайского районного маслихата Восточно-Казахстанской области от 08 апреля 2015 года № 28/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 апреля 2015 года № 3882. Утратило силу - решением маслихата Абайского района Восточно-Казахстанской области от 23.12.2015 № 33/3-V
  title:
    rus: О внесении изменений в решение Абайского районного маслихата от 24 декабря 2014 года № 25/3-V«О бюджете Абайского района на 2015-2017 годы»
    kaz: «2015-2017 жылдарға арналған Абай ауданының бюджеті туралы» Абай аудандық мәслихатының 2014 жылғы 24 желтоқсандағы № 25/3-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88734/rus
