act_code: '219726'
requisite: Решение маслихата района Үлкен Нарын Восточно-Казахстанской области от 19 декабря 2025 года № 18/191-VIII
title:
  rus: О бюджете района Үлкен Нарын на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Үлкен Нарын ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-19
approved_by:
- '157022000002'
version_date:
  kaz: 2026-05-19
  rus: 2026-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/219726/kaz/19.05.2026
  rus: https://zan.gov.kz/client/#!/doc/219726/rus/19.05.2026
caused_by:
  code: '225576'
  requisite: Решение маслихата района Үлкен Нарын Восточно-Казахстанской области от 19 мая 2026 года № 24/239-VIII
  title:
    rus: О внесении изменений в решение маслихата района Үлкен Нарын от 19 декабря 2025 года № 18/191-VІII «О бюджете района Үлкен Нарын на 2026-2028  годы»
    kaz: Үлкен Нарын ауданы мәслихатының 2025 жылғы 19 желтоқсандағы № 18/191–VIІI «2026-2028 жылдарға арналған Үлкен Нарын ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225576/rus
