act_code: '109213'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 30 ноября 2016 года № 7/4-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 28 декабря 2016 года № 4795
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Глубоковском районе
  kaz: Глубокое ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алулар тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-11-30
approved_by:
- '157010000002'
version_date:
  kaz: 2023-07-05
  rus: 2023-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/109213/kaz/05.07.2023
  rus: https://zan.gov.kz/client/#!/doc/109213/rus/05.07.2023
caused_by:
  code: '184466'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 5 июля 2023 года № 3/7-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 31 июля 2023 года № 8891-16
  title:
    rus: О внесении изменений в решение Глубоковского районного маслихата от 30 ноября 2016 года № 7/4-VI «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Глубоковском районе»
    kaz: Глубокое аудандық мәслихатының 2016 жылғы 30 қарашадағы № 7/4-VI «Глубокое ауданында мүгедектігі бар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алулар тәртібі мен мөлшерін анықтау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184466/rus
