act_code: '3139'
requisite: Решение Акима Восточно-Казахстанской области от 25 мая 1999 года № 691-к. Зарегистрировано управлением юстиции Восточно-Казахстанской области 9 июня 1999 года за № 195. Утратило силу решением акима Восточно-Казахстанской области от 25 апреля 2000 года № 849
title:
  rus: О подготовке к работе в осенне-зимний период 1999-2000 гг. объектов энергетики, соцкультбыта и жилищно-коммунального хозяйства области
  kaz: Облыстың энергетика, әлеуметтік, мәдени-тұрмыстық және тұрғын үй-коммуналдық шаруашылығы объектілерін 1999-2000 жылдардағы күзгі-қысқы кездердегі жұмысқа әзірлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-05-24
approved_by:
- '157000000003'
version_date:
  kaz: 1999-05-24
  rus: 1999-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/3139/kaz/24.05.1999
  rus: https://zan.gov.kz/client/#!/doc/3139/rus/24.05.1999
