act_code: '43257'
requisite: Шығыс Қазақстан облысы Катонқарағай аудандық мәслихатының 2008 жылғы 23 желтоқсандағы N 9/98-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Катонқарағай аудандық Әділет басқармасында 2008 жылғы 30 желтоқсанда № 5-13-51 тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Катонқарағай аудандық мәслихатының 2010 жылғы 11 қаңтардағы № 09 хатымен
title:
  rus: 2009 жылға арналған аудан бюджетi туралы
  kaz: 2009 жылға арналған аудан бюджетi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '157014000002'
version_date:
  kaz: 2008-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43257/kaz/23.12.2008
