act_code: '138085'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 26 декабря 2019 года № 35/299-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 9 января 2020 года № 6483. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 46/400-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Катон-Карагайского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Катонқарағай ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-26
approved_by:
- '157014000002'
version_date:
  kaz: 2020-06-26
  rus: 2020-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/138085/kaz/26.06.2020
  rus: https://zan.gov.kz/client/#!/doc/138085/rus/26.06.2020
caused_by:
  code: '144666'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 26 июня 2020 года № 40/346-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 8 июля 2020 года № 7283. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 46/400-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Катон-Карагайского районного маслихата от 26 декабря 2019 года № 35/299-VI «О бюджете Катон-Карагайского района на 2020-2022 годы»
    kaz: Катонқарағай аудандық мәслихатының 2019 жылғы 26 желтоқсандағы № 35/299–VI «2020-2022 жылдарға арналған Катонқарағай ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144666/rus
