act_code: '97803'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 23 декабря 2015 года № 38-2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 января 2016 года № 4338. Утратило силу - решением маслихата Бородулихинского района Восточно-Казахстанской области от 23 декабря 2016 года № 8-2-VI
title:
  rus: О бюджете Бородулихинского района на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған Бородулиха ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '157008000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/97803/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/97803/rus/23.12.2016
caused_by:
  code: '109181'
  requisite: Решение маслихата Бородулихинского района Восточно-Казахстанской области от 23 декабря 2016 года № 8-2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 9 января 2017 года № 4807
  title:
    rus: О бюджете Бородулихинского района на 2017-2019 годы
    kaz: 2017-2019 жылдарға арналған Бородулиха ауданының бюджеті туралы
  link: https://zan.gov.kz/client/#!/doc/109181/rus
