act_code: '62530'
requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 15 ноября 2011 года № 40/3-IV. Зарегистрировано управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 14 декабря 2011 года за № 5-12-129. Утратило силу - решением маслихата Зыряновского района от 26 июня 2012 года № 4/8-V
title:
  rus: Об утверждении "Инструкции по оказанию социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, образования, социального обеспечения, культуры и спорта, проживающим и работающим в сельских населенных пунктах"
  kaz: '"Ауылдық елді мекендерде тұратын және жұмыс істейтін денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мемлекеттік ұйымдардың мамандарына отын сатып алуға әлеуметтік көмек көрсету бойынша нұсқаулығын" бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-15
approved_by:
- '157013000002'
version_date:
  kaz: 2011-11-15
  rus: 2011-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/62530/kaz/15.11.2011
  rus: https://zan.gov.kz/client/#!/doc/62530/rus/15.11.2011
