act_code: '151774'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 46/415-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 31 декабря 2020 года № 8211
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Жамбылскому сельскому округу на 2020-2021 годы
  kaz: 2020-2021 жылдарға арналған Жамбыл ауылдық округі бойынша жайылымдарды басқару және оларды пайдалану жөніндегі Жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2020-12-25
approved_by:
- '157014000002'
version_date:
  kaz: 2020-12-25
  rus: 2020-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/151774/kaz/25.12.2020
  rus: https://zan.gov.kz/client/#!/doc/151774/rus/25.12.2020
