act_code: '127968'
requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 21 декабря 2018 года № 41/2-VI. Зарегистрировано Управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 28 декабря 2018 года № 5-12-181. Утратило силу решением маслихата района Алтай Восточно-Казахстанской области от 27 декабря 2019 года № 60/2-VI (вводится в действие с 01.01.2020)
title:
  rus: О районном бюджете района Алтай на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Алтай ауданының аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '157013000002'
version_date:
  kaz: 2019-04-12
  rus: 2019-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/127968/kaz/12.04.2019
  rus: https://zan.gov.kz/client/#!/doc/127968/rus/12.04.2019
caused_by:
  code: '130741'
  requisite: Решение маслихата района Алтай Восточно-Казахстанской области от 12 апреля 2019 года № 47/6-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 апреля 2019 года № 5867. Утратило силу решением маслихата района Алтай Восточно-Казахстанской области от 27 декабря 2019 года № 60/2-VI (вводится в действие с 01.01.2020)
  title:
    rus: О внесении изменений в решение маслихата Зыряновского района от 21 декабря 2018 года № 41/2-VI «О Зыряновском районном бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған Зырян аудандық бюджеті туралы» Зырян ауданының мәслихатының 2018 жылғы 21 желтоқсандағы № 41/2-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130741/rus
