act_code: '205053'
requisite: Решение акима Иртышского сельского округа Глубоковского района Восточно-Казахстанской области от 23 декабря 2024 года № 7
title:
  rus: Об установлении публичного сервитута на земельный участок для проведения дноуглубительных, берегоукрепительных работ на реке Иртыш в районе села Прапорщиково товариществу с ограниченной ответственностью «AKKY Ltd»
  kaz: «KKY Ltd» жауапкершілігі шектеулі серіктестігіне Прапорщиково ауылы маңында Ертіс өзенінің түбін тереңдету, жағалауын нығайту жұмыстарын жүргізу үшін жер учаскесіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-23
approved_by:
- '157010013002'
version_date:
  kaz: 2024-12-23
  rus: 2024-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/205053/kaz/23.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205053/rus/23.12.2024
