act_code: '49184'
requisite: Шығыс Қазақстан облысы Бесқарағай аудандық мәслихатының 2009 жылғы 22 қазандағы № 18/8-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Бесқарағай ауданындағы Әділет басқармасында 2009 жылғы 25 қарашада № 5-7-72 тіркелді. Күші жойылды - Шығыс Қазақстан облысы Бесқарағай аудандық мәслихатының 2012 жылғы 6 сәуірдегі № 2/6-V шешімімен
title:
  rus: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін жергілікті бюджет қаражаты
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін жергілікті бюджет қаражаты есебінен әлеуметтік көмек көрсету мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-22
approved_by:
- '157009000002'
version_date:
  kaz: 2009-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/49184/kaz/22.10.2009
