act_code: '181134'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 3 мая 2023 года № 21. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 мая 2023 года № 8842-16
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума по Уланскому району на 2023 год
  kaz: Ұлан ауданы бойынша 2023 жылға кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-03
approved_by:
- '157018000002'
version_date:
  kaz: 2023-05-03
  rus: 2023-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/181134/kaz/03.05.2023
  rus: https://zan.gov.kz/client/#!/doc/181134/rus/03.05.2023
