act_code: '20794'
requisite: Решение акима Глубоковского района Восточно-Казахстанской области от 16 июня 2004 года № 35. Зарегистрировано Управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 30 июля 2004 года за № 1904. Утратило силу решением акима Глубоковского района Восточно-Казахстанской области от 30 марта 2006 года № 35
title:
  rus: Об утверждении Регламента аппарата Акима Глубоковского района
  kaz: Об утверждении Регламента аппарата Акима Глубоковского района
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-06-15
approved_by:
- '157010000003'
version_date:
  kaz: 2004-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/20794/kaz/15.06.2004
