act_code: '108549'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 23 ноября 2016 года № 9/4-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 21 декабря 2016 года № 4778. Утратило силу решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 5 июля 2018 года № 26/9-VI
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Шемонаихинскому району
  kaz: Шемонаиха ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-11-23
approved_by:
- '157020000002'
version_date:
  kaz: 2016-11-23
  rus: 2016-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/108549/kaz/23.11.2016
  rus: https://zan.gov.kz/client/#!/doc/108549/rus/23.11.2016
