act_code: '96335'
requisite: Решение акима Бахтинского сельского округа Урджарского района Восточно-Казахстанской области от 6 ноября 2015 года № 9. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 4 декабря 2015 года № 4253
title:
  rus: О переименовании улицы в селе Бахты
  kaz: Бахты ауылындағы көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-06
approved_by:
- '157019006001'
version_date:
  kaz: 2015-11-06
  rus: 2015-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/96335/kaz/06.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96335/rus/06.11.2015
