act_code: '79442'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 31 марта 2014 года № 28/150-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 25 апреля 2014 года № 3267. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 29 апреля 2020 года № 52/379-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-03-31
approved_by:
- '157003000002'
version_date:
  kaz: 2020-03-03
  rus: 2020-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/79442/kaz/03.03.2020
  rus: https://zan.gov.kz/client/#!/doc/79442/rus/03.03.2020
caused_by:
  code: '141095'
  requisite: Решение маслихата города Семей Восточно-Казахстанской области от 3 марта 2020 года № 49/336-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 3 апреля 2020 года № 6844. Утратило силу решением маслихата города Семей области Абай от 9 ноября 2023 года № 12/73-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата города Семей от 31 марта 2014 года № 28/150–V «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Семей қаласы мәслихатының 2014 жылғы 31 наурыздағы № 28/150-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141095/rus
