act_code: '29041'
requisite: Решение XVII сессии Уланского районного маслихата Восточно-Казахстанской области III созыва от 12 июля 2006 года № 182. Зарегистрировано Управлением юстиции Уланского района Департамента юстиции Восточно-Казахстанской области 24 июля 2006 года № 5-17-40. Утратило силу решением Уланского районного маслихата от 13 июля 2012 года № 54
title:
  rus: Об утверждении Правил сожержания животных в Уланском районе
  kaz: Об утверждении Правил сожержания животных в Уланском районе
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-07-12
approved_by:
- '157018000002'
version_date:
  rus: 2006-07-12
source:
  rus: https://zan.gov.kz/client/#!/doc/29041/rus/12.07.2006
