act_code: '125559'
requisite: Решение Восточно-Казахстанского областного маслихата от 10 октября 2018 года № 23/265-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 октября 2018 года № 5687
title:
  rus: Об определении перечня социально значимых сообщений по Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2018-10-10
approved_by:
- '157000000002'
version_date:
  kaz: 2024-09-20
  rus: 2024-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/125559/kaz/20.09.2024
  rus: https://zan.gov.kz/client/#!/doc/125559/rus/20.09.2024
caused_by:
  code: '200921'
  requisite: Решение Восточно-Казахстанского областного маслихата от 20 сентября 2024 года № 16/127-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 24 сентября 2024 года № 9080-16
  title:
    rus: О внесении изменения в решение Восточно-Казахстанского областного маслихата от 10 октября 2018 года № 23/265-VI «Об определении перечня социально значимых сообщений по Восточно-Казахстанской области»
    kaz: «Шығыс Қазақстан облысы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы» Шығыс Қазақстан облыстық мәслихатының 2018 жылғы 10 қазандағы № 23/265-VI шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200921/rus
