act_code: '11257'
requisite: РРешение XII сессии Восточно-Казахстанского областного маслихата от 21 декабря 2001 года N 12/13-II. Зарегистрировано Управлением юстиции Восточно-Казахстанской области 30 января 2002 года за N 667. Утратило силу решением XI сессии ВКО маслихата от 31 мая 2005 года N 11/168-III
title:
  rus: О предельных (максимальных) размерах земельных участков, которые могут находиться в долгосрочном землепользовании или в собственности
  kaz: Жеке меншікте немесе ұзақ мерзімді жер пайдалануда бола алатын жер учаскелерінің шекті (ең көп) мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-21
approved_by:
- '157000000002'
version_date:
  kaz: 2001-12-21
  rus: 2001-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/11257/kaz/21.12.2001
  rus: https://zan.gov.kz/client/#!/doc/11257/rus/21.12.2001
