act_code: '138885'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 10 января 2020 года № 48-545/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 января 2020 года № 6564. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 29 декабря 2020 года № 57-759/VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Бахтинского сельского округа Урджарского района на 2020-2022 годы
  kaz: Үржар ауданы Бахты ауылдық округінің 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '157019000002'
version_date:
  kaz: 2020-10-14
  rus: 2020-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/138885/kaz/14.10.2020
  rus: https://zan.gov.kz/client/#!/doc/138885/rus/14.10.2020
caused_by:
  code: '147595'
  requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 14 октября 2020 года № 55-690/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 октября 2020 года № 7681. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 29 декабря 2020 года № 57-759/VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Урджарского районного маслихата от 10 января 2020 года № 48-545/VI «О бюджете Бахтинского сельского округа Урджарского района на 2020-2022 годы»
    kaz: Үржар аудандық мәслихатының 2020 жылғы 10 қаңтардағы № 48-545/VI «2020-2022 жылдарға арналған Үржар ауданы Бахты ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147595/rus
