act_code: '56594'
requisite: Шығыс Қазақстан облысы Катонқарағай аудандық мәслихатының 2010 жылғы 29 желтоқсандағы № 27/229-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Катонқарағай аудандық әділет басқармасында 2010 жылғы 31 желтоқсанда № 5-13-82 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды (Катонқарағай аудандық мәслихатының 2012 жылғы 5 қаңтардағы № 03 хаты)
title:
  rus: 2011-2013 жылдарға арналған аудан бюджеті туралы
  kaz: 2011-2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-29
approved_by:
- '157014000002'
version_date:
  kaz: 2011-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/56594/kaz/16.06.2011
caused_by:
  code: '59284'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 16 июня 2011 года № 29/256-IV. Зарегистрировано управлением юстиции Катон-Карагайского района Департамента юстиции Восточно-Казахстанской области 22 июня 2011 года за № 5-13-91. Утратило силу в связи с истечением срока действия (письмо Катон-Карагайского районного маслихата от 5 января 2012 года № 03)
  title:
    rus: О внесении изменений и дополнения в решение от 29 декабря 2010 года № 27/229-IV "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудан бюджеті туралы" 2010 жылғы 29 желтоқсандағы № 27/229-IV шешімге өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/59284/rus
