act_code: '44726'
requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 19 февраля 2009 года № 16/119-IV. Зарегистрировано Управлением юстиции города Курчатова Департамента юстиции Восточно-Казахстанской области 11 марта 2009 года за № 5-3-69. Утратило силу - решением Курчатовского городского маслихата Восточно-Казахстанской области от 4 мая 2018 года № 20/152-VI
title:
  rus: О базовых ставках фиксированного налога
  kaz: Тіркелген салықтың базалық ставкасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-19
approved_by:
- '157004000002'
version_date:
  kaz: 2009-02-19
  rus: 2009-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/44726/kaz/19.02.2009
  rus: https://zan.gov.kz/client/#!/doc/44726/rus/19.02.2009
