act_code: '87073'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 26 января 2015 года № 29-2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 23 февраля 2015 года № 3695. Утратило силу решением Бородулихинского районного маслихата области Абай от 29 марта 2024 года № 15-8-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Бородулихинском районе
  kaz: Бородулиха ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-01-26
approved_by:
- '157008000002'
version_date:
  kaz: 2020-07-03
  rus: 2020-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/87073/kaz/03.07.2020
  rus: https://zan.gov.kz/client/#!/doc/87073/rus/03.07.2020
caused_by:
  code: '144885'
  requisite: Решение маслихата Бородулихинского района Восточно-Казахстанской области от 3 июля 2020 года № 51-7-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 июля 2020 года № 7356. Утратило силу решением Бородулихинского районного маслихата области Абай от 29 марта 2024 года № 15-8-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Бородулихинского районного маслихата от 26 января 2015 года № 29-2-V «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: «Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы Қағиданы бекіту туралы» Бородулиха аудандық мәслихатының 2015 жылғы 26 қаңтардағы № 29-2-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144885/rus
