act_code: '87073'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 26 января 2015 года № 29-2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 23 февраля 2015 года № 3695. Утратило силу решением Бородулихинского районного маслихата области Абай от 29 марта 2024 года № 15-8-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Бородулихинском районе
  kaz: Бородулиха ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-01-26
approved_by:
- '157008000002'
version_date:
  kaz: 2018-09-21
  rus: 2018-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/87073/kaz/21.09.2018
  rus: https://zan.gov.kz/client/#!/doc/87073/rus/21.09.2018
caused_by:
  code: '125430'
  requisite: Решение маслихата Бородулихинского района Восточно-Казахстанской области от 21 сентября 2018 года № 26-5-VI. Зарегистрировано Управлением юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 25 октября 2018 года № 5-8-174. Утратило силу решением Бородулихинского районного маслихата области Абай от 29 марта 2024 года № 15-8-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Бородулихинского районного маслихата от 26 января 2015 года № 29-2-V «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: «Тұрғын үй көмегiн көрсетудiң мөлшерi мен тәртiбiн айқындау туралы Қағиданы бекiту туралы» Бородулиха аудандық мәслихатының 2015 жылғы 26 қаңтардағы № 29-2-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125430/rus
