act_code: '80275'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 15 апреля 2014 года № 24-249/V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 мая 2014 года № 3353. Утратило силу решением Урджарского районного маслихата области Абай от 13 июля 2023 года № 3-91/VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества  и определения количества представителей жителей сел, улиц, многоквартирных  жилых домов для участия в сходах местного сообщества на территории Урджарского района
  kaz: Үржар ауданының аумағында бөлек жергілікті қоғамдастық жиындарын өткізу Қағидасын бекіту және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-15
approved_by:
- '157019000002'
version_date:
  kaz: 2014-04-15
  rus: 2014-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/80275/kaz/15.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80275/rus/15.04.2014
