act_code: '148497'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 21 октября 2020 года № 403. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 ноября 2020 года № 7789
title:
  rus: Об утверждении проектов (схем) зонирования земель и поправочных коэффициентов к базовым ставкам земельного налога по Уланскому району
  kaz: Ұлан ауданы бойынша жерді аймақтарға бөлу және жер салығының базалық ставкаларына түзету коэффициентерінің жобаларын (сызбалар) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-10-21
approved_by:
- '157018000002'
version_date:
  kaz: 2020-10-21
  rus: 2020-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/148497/kaz/21.10.2020
  rus: https://zan.gov.kz/client/#!/doc/148497/rus/21.10.2020
