act_code: '152452'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 3 декабря 2020 года № 65-5. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 января 2021 года № 8338. Утратило силу решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 12 июля 2024 года № 16/16-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Тарбагатайском районе
  kaz: Тарбағатай ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-03
approved_by:
- '157017000002'
version_date:
  kaz: 2022-11-30
  rus: 2022-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/152452/kaz/30.11.2022
  rus: https://zan.gov.kz/client/#!/doc/152452/rus/30.11.2022
caused_by:
  code: '174757'
  requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 30 ноября 2022 года № 28/4-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 декабря 2022 года № 30874. Утратило силу решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 12 июля 2024 года № 16/16-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Тарбагатайского районного маслихата от 3 декабря 2020 года № 65-5 «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: Тарбағатай аудандық мәслихатының 2020 жылғы 3 желтоқсандағы № 65-5 «Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау Қағидасын бекіту» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174757/rus
