act_code: '154387'
requisite: Решение Кокпектинского районного маслихата Восточно-Казахстанской области от 31 марта 2021 года № 4-6/2. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 6 апреля 2021 года № 8522
title:
  rus: Об установлении повышенных должностных окладов и тарифных ставок
  kaz: Жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-31
approved_by:
- '157015000002'
version_date:
  kaz: 2021-03-31
  rus: 2021-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/154387/kaz/31.03.2021
  rus: https://zan.gov.kz/client/#!/doc/154387/rus/31.03.2021
