act_code: '29991'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 19 сентября 2006 года № 23-10. Зарегистрировано Управлением юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 12 октября 2006 года № 5-8-31. Утратило силу решением Бородулихинского районного маслихата от 29 октября 2007 года № 2-6-IV
title:
  rus: О правилах содержания крупного рогатого скота, овец, коз, собак и кошек в населенных пунктах Бородулихинского района
  kaz: О правилах содержания крупного рогатого скота, овец, коз, собак и кошек в населенных пунктах Бородулихинского района
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-09-19
approved_by:
- '157008000002'
version_date:
  rus: 2006-09-19
source:
  rus: https://zan.gov.kz/client/#!/doc/29991/rus/19.09.2006
