act_code: '175078'
requisite: Решение акима Кожоховского сельского округа Глубоковского района Восточно-Казахстанской области от 5 декабря 2022 года № 10. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 декабря 2022 года № 30988
title:
  rus: О переименовании составных частей села Прогресс Кожоховского сельского округа Глубоковского района Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысы Глубокое ауданы Кожохово ауылдық округі Прогресс ауылының құрамдас бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-05
approved_by:
- '157010003002'
version_date:
  kaz: 2022-12-05
  rus: 2022-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/175078/kaz/05.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175078/rus/05.12.2022
