act_code: '30211'
requisite: Шығыс Қазақстан облысы Тарбағатай ауданы әкімінің 2006 жылғы 20 қазандағы № 14 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Тарбағатай аудандық Әділет басқармасында 2006 жылғы 27 қазанда № 5-16-26 тіркелді
title:
  rus: 2006-2007 оқу жылында Қазақстан Республикасының Қарулы Күштері үшін әскери-техникалық мамандар даярлау туралы
  kaz: 2006-2007 оқу жылында Қазақстан Республикасының Қарулы Күштері үшін әскери-техникалық мамандар даярлау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-10-20
approved_by:
- '157017000003'
version_date:
  kaz: 2006-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/30211/kaz/20.10.2006
