act_code: '124251'
requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 31 июля 2018 года № 32/3-VI. Зарегистрировано Управлением юстиции города Усть-Каменогорска Департамента юстиции Восточно-Казахстанской области 23 августа 2018 года № 5-1-195. Утратило силу решением Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 4 июня 2024 года № 22/3-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в городе Усть-Каменогорске
  kaz: Өскемен қаласында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-07-31
approved_by:
- '157002000002'
version_date:
  kaz: 2018-07-31
  rus: 2018-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/124251/kaz/31.07.2018
  rus: https://zan.gov.kz/client/#!/doc/124251/rus/31.07.2018
