act_code: '123125'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 19 июня 2018 года № 28-287/VI. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 2 июля 2018 года № 5-18-159. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 24 июня 2020 года № 53-655/VI (вводится в действие с 01.01.2020)
title:
  rus: Об установлении ставок фиксированного налога в Урджарском районе
  kaz: Үржар ауданында тіркелген салықтың мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-19
approved_by:
- '157019000002'
version_date:
  kaz: 2018-06-19
  rus: 2018-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/123125/kaz/19.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123125/rus/19.06.2018
