act_code: '49862'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 25 декабря 2009 года № 23/2-IV. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 10 января 2010 года за № 5-19-111. Утратило силу в связи с истечением срока действия (письмо Шемонаихинского районного маслихата от 14 апреля 2011 года № 73)
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '157020000002'
version_date:
  kaz: 2010-01-26
  rus: 2010-01-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/49862/kaz/26.01.2010
  rus: https://zan.gov.kz/client/#!/doc/49862/rus/26.01.2010
caused_by:
  code: '50688'
  requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 26 января 2010 года № 24/2-IV. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 9 февраля 2010 года за № 5-19-114. Утратило силу в связи с истечением срока действия (письмо Шемонаихинского районного маслихата от 14 апреля 2011 года № 73)
  title:
    rus: О внесении изменений и дополнений в решение от 25 декабря 2009 года № 23/2-IV "О районном бюджете на 2010-2012 годы"
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" 2009 жылғы 25 желтоқсандағы № 23/2-ІV шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/50688/rus
