act_code: '117059'
requisite: Решение Кокпектинского районного маслихата Восточно-Казахстанской области от 22 декабря 2017 года № 18-2. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 26 декабря 2017 года № 5355. Утратило силу решением Кокпектинского районного маслихата Восточно-Казахстанской области от 21 декабря 2018 года № 30-2
title:
  rus: О Кокпектинском районном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Көкпекті аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '157015000002'
version_date:
  kaz: 2018-06-20
  rus: 2018-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/117059/kaz/20.06.2018
  rus: https://zan.gov.kz/client/#!/doc/117059/rus/20.06.2018
caused_by:
  code: '123054'
  requisite: Решение Кокпектинского районного маслихата Восточно-Казахстанской области от 20 июня 2018 года № 23-6/1. Зарегистрировано Управлением юстиции Кокпектинского района Департамента юстиции Восточно-Казахстанской области 28 июня 2018 года № 5-15-115. Утратило силу решением Кокпектинского районного маслихата Восточно-Казахстанской области от 21 декабря 2018 года № 30-2
  title:
    rus: О внесении изменений в решение Кокпектинского районного маслихата от 22 декабря 2017 года № 18-2 «О Кокпектинском районном бюджете на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған Көкпекті аудандық бюджеті туралы» Көкпекті аудандық мәслихатының 2017 жылғы 22 желтоқсандағы № 18-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123054/rus
