act_code: '205757'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 27 декабря 2024 года № 25/9-VIII
title:
  rus: О бюджете Маныракского сельского округа Тарбагатайского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Тарбағатай ауданы Маңырақ ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '157017000002'
version_date:
  kaz: 2025-09-18
  rus: 2025-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/205757/kaz/18.09.2025
  rus: https://zan.gov.kz/client/#!/doc/205757/rus/18.09.2025
caused_by:
  code: '214696'
  requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 18 сентября 2025 года № 32/9-VIII
  title:
    rus: О внесении изменений в решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 27 декабря 2024 года №25/9-VIII «О бюджете Маныракского сельского округа Тарбагатайского района на 2025-2027 годы»
    kaz: Шығыс Қазақстан облысы Тарбағатай аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 25/9-VIII «2025-2027 жылдарға арналған Тарбағатай ауданы Маңырақ ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214696/rus
