act_code: '58032'
requisite: Решение акима Зайсанского района Восточно-Казахстанской области от 24 февраля 2011 года № 3. Зарегистрировано управлением юстиции Зайсанского района Департамента юстиции Восточно-Казахстанской области 1 апреля 2011 года за № 5-11-132. Утратило силу - решением акима Зайсанского района от 27 апреля 2011 года № 7
title:
  rus: Об определении границ избирательных участков по Зайсанскому району
  kaz: Зайсан ауданы бойынша сайлау учаскелерінің шекараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-02-24
approved_by:
- '157012000001'
version_date:
  kaz: 2011-02-24
  rus: 2011-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/58032/kaz/24.02.2011
  rus: https://zan.gov.kz/client/#!/doc/58032/rus/24.02.2011
