act_code: '37025'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 26 декабря 2007 года № 5/3-IV. Зарегистрировано управлением юстиции города Риддера Департамента юстиции Восточно-Казахстанской области 9 января 2008 года № 5-4-77. Утратило силу - решением Риддерского городского маслихата от 24 июля 2009 года № 18/9-IV
title:
  rus: Об утверждении Инструкции по оказанию жилищной помощи малообеспеченным гражданам
  kaz: Тұрмысы төмен азаматтарға тұрғын үй көмегін көрсету Нұсқауын бекіту туралы
form: РЕШ
type_codes:
- ИНСТ
- РЕШ
approved_on: 2007-12-26
approved_by:
- '157005000002'
version_date:
  kaz: 2007-12-26
  rus: 2007-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/37025/kaz/26.12.2007
  rus: https://zan.gov.kz/client/#!/doc/37025/rus/26.12.2007
