act_code: '48744'
requisite: Шығыс Қазақстан облысы Аягөз аудандық мәслихатының 2009 жылғы 22 қазандағы № 01-02/19-4 шешімі. Шығыс Қазақстан облысы Аягөз ауданының Әділет басқармасында 2009 жылғы 20 қарашада № 5-6-98 тіркелді. Күші жойылды - Аягөз аудандық мәслихатының 2010 жылғы 28 шілдедегі № 01-02/27-17 шешімімен
title:
  rus: '"Тұрмысы төмен азаматтарға үйді ұстауға және үй-коммуналдық қызметке ақы төлеу үшін тұрғын үй жәрдемақыларын беру" Ережелерін бекіту туралы'
  kaz: '"Тұрмысы төмен азаматтарға үйді ұстауға және үй-коммуналдық қызметке ақы төлеу үшін тұрғын үй жәрдемақыларын беру" Ережелерін бекіту туралы'
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-10-22
approved_by:
- '157007000002'
version_date:
  kaz: 2009-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/48744/kaz/22.10.2009
