act_code: '61794'
requisite: Решение акима Бородулихинского района Восточно-Казахстанской области от 23 ноября 2011 года N 12. Зарегистрировано Управлением юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 5 декабря 2011 года за N 5-8-138. Утратило силу решением акима Бородулихинского района Восточно-Казахстанской области от 4 декабря 2014 года № 15
title:
  rus: Об образовании избирательных участков по Бородулихинскому району
  kaz: Бородулиха ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-23
approved_by:
- '157008000001'
version_date:
  kaz: 2011-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/61794/kaz/23.11.2011
