act_code: '97372'
requisite: Решение маслихата Абайского района Восточно-Казахстанской области от 23 декабря 2015 года № 33/3-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 12 января 2016 года № 4322. Утратило силу - решением маслихата Абайского района Восточно-Казахстанской области от 23 декабря 2016 года № 8/3-VI
title:
  rus: О бюджете Абайского района на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған Абай ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '157006000002'
version_date:
  kaz: 2016-08-01
  rus: 2016-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/97372/kaz/01.08.2016
  rus: https://zan.gov.kz/client/#!/doc/97372/rus/01.08.2016
caused_by:
  code: '105352'
  requisite: Решение маслихата Абайского района Восточно-Казахстанской области от 1 августа 2016 года № 4/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 9 августа 2016 года № 4638. Утратило силу - решением маслихата Абайского района Восточно-Казахстанской области от 23 декабря 2016 года № 8/3-VI
  title:
    rus: О внесении изменений в решение Абайского районного маслихата от 23 декабря 2015 года № 33/3-V «О бюджете Абайского района на 2016-2018 годы»
    kaz: «2016-2018 жылдарға арналған Абай ауданының бюджеті туралы» Абай аудандық мәслихатының 2015 жылғы 23 желтоқсандығы № 33/3-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/105352/rus
