act_code: '198487'
requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 26 июня 2024 года № 24/9-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 4 июля 2024 года № 9045-16. Утратило силу решением Зайсанского районного маслихата Восточно-Казахстанской области от 14 октября 2025 года № 41/7-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Зайсанскому району
  kaz: Зайсан ауданы бойынша тұрғын үй сертификаттарының мөлшерін және оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-26
approved_by:
- '157012000002'
version_date:
  kaz: 2024-06-26
  rus: 2024-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/198487/kaz/26.06.2024
  rus: https://zan.gov.kz/client/#!/doc/198487/rus/26.06.2024
