act_code: '169862'
requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 7 июля 2022 года № 22/5-VII. Отменен решением Бескарагайского районного маслихата области Абай от 28 апреля 2023 года № 2/8-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Бескарагайского районного маслихата»
  kaz: «Бесқарағай аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-07-07
approved_by:
- '157009000002'
version_date:
  kaz: 2022-07-07
  rus: 2022-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/169862/kaz/07.07.2022
  rus: https://zan.gov.kz/client/#!/doc/169862/rus/07.07.2022
