act_code: '165533'
requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 24 декабря 2021 года № 15-17/12
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию на 2022-2023 годы Караталского сельского округа Зайсанского района
  kaz: Зайсан ауданы Қаратал ауылдық округі бойынша жайылымдарды басқару және оларды пайдалану жөніндегі 2022-2023 жылдарға арналған Жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '157012000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/165533/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/165533/rus/24.12.2021
