act_code: '121098'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 30 марта 2018 года № 23-6. Зарегистрировано Управлением юстиции Тарбагатайского района Департамента юстиции Восточно-Казахстанской области 17 апреля 2018 года № 5-16-130. Утратило силу решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 30 декабря 2022 года № 31/12-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Тарбагатайского районного маслихата»
  kaz: «Тарбағатай аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-03-30
approved_by:
- '157017000002'
version_date:
  kaz: 2018-03-30
  rus: 2018-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/121098/kaz/30.03.2018
  rus: https://zan.gov.kz/client/#!/doc/121098/rus/30.03.2018
