act_code: '23149'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 10 февраля 2005 года № 11-8. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 1 марта 2005 года за № 2203. Утратило силу на основание письма маслихата Бородулихинского района Восточно-Казахстанской области от 17 марта 2007 года № 41
title:
  rus: Об утверждении Правил предоставления малообеспеченным гражданам жилищной помощи на содержание жилья и оплату жилищно-коммунальных услуг
  kaz: Тұрмысы төмен азаматтарға үйді ұстауға және үй-коммуналдық кызметке ақы төлеу үшін тұрғын үй жәрдемақыларын беру тәртібі туралы Ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-02-10
approved_by:
- '157008000002'
version_date:
  rus: 2005-02-10
source:
  rus: https://zan.gov.kz/client/#!/doc/23149/rus/10.02.2005
