act_code: '56701'
requisite: Решение акима Андреевского сельского округа Бородулихинского района Восточно-Казахстанской области от 14 декабря 2010 года № 1. Зарегистрировано Управлением юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 13 января 2011 года № 5-8-124
title:
  rus: О переименовании улиц
  kaz: Көшелердің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '157008000001'
version_date:
  kaz: 2010-12-14
  rus: 2010-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56701/kaz/14.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56701/rus/14.12.2010
