act_code: '145121'
requisite: Решение маслихата Абайского района Восточно-Казахстанской области от 15 июля 2020 года № 50/6-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 24 июля 2020 года № 7410
title:
  rus: Об утверждении проекта (схемы) зонирования земель и поправочных коэффициентов к базовым ставкам платы за земельные участки по Абайскому району
  kaz: Абай ауданы бойынша жерлерді аймақтарға бөлу жобасын (схемасын) және жер учаскелері үшін төлемақының базалық мөлшерлемелеріне түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-15
approved_by:
- '157006000002'
version_date:
  kaz: 2020-07-15
  rus: 2020-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/145121/kaz/15.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145121/rus/15.07.2020
