act_code: '117734'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 29 декабря 2017 года № 22/141-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 января 2018 года № 5409. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 29 декабря 2018 года № 33/223-VI
title:
  rus: «О бюджете Иртышского сельского округа на 2018-2020 годы»
  kaz: «Ертіс ауылдық округінің 2018-2020 жылдарға арналған бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-29
approved_by:
- '157003000002'
version_date:
  kaz: 2018-12-07
  rus: 2018-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/117734/kaz/07.12.2018
  rus: https://zan.gov.kz/client/#!/doc/117734/rus/07.12.2018
caused_by:
  code: '127001'
  requisite: Решение маслихата города Семей Восточно-Казахстанской области от 7 декабря 2018 года № 31/209-VI. Зарегистрировано Управлением юстиции города Семей Департамента юстиции Восточно-Казахстанской области 13 декабря 2018 года № 5-2-192. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 29 декабря 2018 года № 33/223-VI
  title:
    rus: О внесении изменений в решение маслихата города Семей от 29 декабря 2017 года № 22/141-VI «О бюджете Иртышского сельского округа на 2018-2020 годы»
    kaz: Семей қаласы мәслихатының 2017 жылғы 29 желтоқсандағы № 22/141-VI «Ертіс ауылдық округінің 2018-2020 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127001/rus
