act_code: '164767'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 30 декабря 2021 года № 12-179/VII. Утратило силу решением Урджарского районного маслихата области Абай от 22 декабря 2022 года № 22-366/VII (вводится в действие с 01.01.2023)
title:
  rus: О бюджете Жана тилекского сельского округа Урджарского района на 2022-2024 годы
  kaz: Үржар ауданы Жаңа тілек ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '157019000002'
version_date:
  kaz: 2022-12-05
  rus: 2022-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/164767/kaz/05.12.2022
  rus: https://zan.gov.kz/client/#!/doc/164767/rus/05.12.2022
caused_by:
  code: '176045'
  requisite: Решение Урджарского районного маслихата области Абай от 5 декабря 2022 года № 21-346/VII. Утратило силу решением Урджарского районного маслихата области Абай от 22 декабря 2022 года № 22-366/VII (вводится в действие с 01.01.2023)
  title:
    rus: О внесении изменения в решение Урджарского районного маслихата от 30 декабря 2021 года № 12-179/VII «О бюджете Жана тилекского сельского округа Урджарского района на 2022-2024 годы»
    kaz: Үржар аудандық мәслихатының 2021 жылғы 30 желтоқсандағы № 12-179/VII «2022-2024 жылдарға арналған Үржар ауданы Жаңа тілек ауылдық округінің бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/176045/rus
