act_code: '162610'
requisite: Решение маслихата Бородулихинского района Восточно-Казахстанской области от 24 декабря 2021 года № 12-2-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 декабря 2021 года № 26158
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '157008000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/162610/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162610/rus/24.12.2021
