act_code: '164006'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 31 декабря 2021 года № 13/12-VII
title:
  rus: О бюджете Кумкольского сельского округа Тарбагатайского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Тарбағатай ауданы Құмкөл ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-31
approved_by:
- '157017000002'
version_date:
  kaz: 2022-04-19
  rus: 2022-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/164006/kaz/19.04.2022
  rus: https://zan.gov.kz/client/#!/doc/164006/rus/19.04.2022
caused_by:
  code: '168349'
  requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 19 апреля 2022 года № 16/12-VII
  title:
    rus: О внесении изменений и дополнений в решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 31 декабря 2021 года № 13/12-VII «О бюджете Кумкольского сельского округа Тарбагатайского района на 2022-2024 годы»
    kaz: Шығыс Қазақстан облысы Тарбағатай аудандық мәслихатының 2021 жылғы 31 желтоқсандағы № 13/12-VII «2022-2024 жылдарға арналған Тарбағатай ауданы Құмкөл ауылдық округінің бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/168349/rus
