act_code: '85221'
requisite: Решение от 10.12.2014 №24/289-V, Маслихат Восточно-Казахстанской области. Утратило силу решением маслихата Восточно-Казахстанской области от 09.12.2015 № 34/406-V
title:
  rus: Об областном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-10
approved_by:
- '157000000002'
version_date:
  kaz: 2015-10-07
  rus: 2015-10-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/85221/kaz/07.10.2015
  rus: https://zan.gov.kz/client/#!/doc/85221/rus/07.10.2015
caused_by:
  code: '94421'
  requisite: Решение от 07.10.2015 №32/379-V, Маслихат Восточно-Казахстанской области. Утратило силу решением маслихата Восточно-Казахстанской области от 09.12.2015 № 34/406-V
  title:
    rus: О внесении изменений в решение Восточно-Казахстанского областного маслихата от 10 декабря 2014 года № 24/289-V «Об областном бюджете на 2015-2017 годы»
    kaz: '«2015-2017 жылдарға арналған  облыстық бюджет туралы» Шығыс Қазақстан облыстық мәслихатының 2014 жылғы 10 желтоқсандағы № 24/289-V шешіміне өзгерістер енгізу туралы '
  link: https://zan.gov.kz/client/#!/doc/94421/rus
