act_code: '48808'
requisite: Шығыс Қазақстан облысы Ұлан аудандық мәслихатының 2009 жылғы 22 қазандағы № 147 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Ұлан аудандық Әділет басқармасында 2009 жылғы 23 қарашада № 5-17-115 тіркелді. Күші жойылды - Ұлан аудандық мәслихатының 2011 жылғы 30 қыркүйектегі № 269 шешімімен
title:
  rus: Бір рет берілетін талондар құнының мөлшері туралы
  kaz: Бір рет берілетін талондар құнының мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-22
approved_by:
- '157018000002'
version_date:
  kaz: 2009-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/48808/kaz/22.10.2009
