act_code: '66370'
requisite: Решение акима Средигорного сельского округа Зыряновского района Восточно-Казахстанской области от 29 мая 2012 года № 1. Зарегистрировано управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 20 июня 2012 года за № 5-12-142
title:
  rus: О присвоении наименований улицам сел Средигорное, Чиркаин, Андреевка, Александровка Средигорного сельского округа Зыряновского района Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысының Зырян ауданы Средигорное селолық округінің Средигорное, Шірікқайың, Андреевка, Александровка ауылдарындағы көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-29
approved_by:
- '157013013002'
version_date:
  kaz: 2012-05-29
  rus: 2012-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/66370/kaz/29.05.2012
  rus: https://zan.gov.kz/client/#!/doc/66370/rus/29.05.2012
