act_code: '60412'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 23 августа 2011 года № 38/9-IV. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 7 сентября 2011 года за № 5-19-153. Утратило силу - решением Шемонаихинского районного маслихата от 12 июля 2012 года № 4/13-V
title:
  rus: Об утверждении Инструкции по назначению и оказанию социальной помощи отдельным категориям граждан
  kaz: Азаматтардың жекелеген санаттарына әлеуметтік көмегін тағайындау және көрсету жөніндегі Нұқаулықты бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-08-23
approved_by:
- '157020000002'
version_date:
  kaz: 2011-08-23
  rus: 2011-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/60412/kaz/23.08.2011
  rus: https://zan.gov.kz/client/#!/doc/60412/rus/23.08.2011
