act_code: '141617'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 17 марта 2020 года № 36/317-VІ. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 13 апреля 2020 года № 6878. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 46/408-VI (вводится в действие с 01.01.2021)
title:
  rus: Об установлении повышенных должностных окладов и тарифных ставок специалистам в области социального обеспечения, образования, культуры, спорта, являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, бiлiм беру, мәдениет, спорт саласындағы мамандарға жоғарылатылған лауазымдық айлықақылар мен тарифтiк мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-17
approved_by:
- '157014000002'
version_date:
  kaz: 2020-12-04
  rus: 2020-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/141617/kaz/04.12.2020
  rus: https://zan.gov.kz/client/#!/doc/141617/rus/04.12.2020
caused_by:
  code: '149680'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 4 декабря 2020 года № 45/398-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 декабря 2020 года № 7962. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 46/408-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменении в решение Катон-Карагайского районного маслихата от 17 марта 2020 года № 36/317-VI «Об установлении повышенных должностных окладов и тарифных ставок специалистам в области социального обеспечения, образования, культуры, спорта, являющимся гражданскими служащими и работающим в сельской местности»
    kaz: Катонқарағай аудандық мәслихатының 2020 жылғы 17 наурыздағы № 36/317-VI «Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, бiлiм беру, мәдениет, спорт саласындағы мамандарға жоғарылатылған лауазымдық айлықақылар мен тарифтiк мөлшерлемелер белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149680/rus
