act_code: '8941'
requisite: Решение Акима Восточно-Казахстанской области от 8 мая 2001 года № 1045. Зарегистрировано управлением юстиции Восточно-Казахстанской области 10 мая 2001 года за № 494. Утратило силу решением Восточно-Казахстанского областного акима от 13 мая 2004 года № 88
title:
  rus: О кредитовании сельхозтоваропроизводителей для обеспечения горюче-смазочными материалами на период проведения весенне-полевых и уборочных работ 2001 года
  kaz: 2001 жылдың көктемгi егiс және егiн жинау жұмыстары кезiнде ауылшаруашылық тауар өндiрушiлерiн жанар-жағар маймен қамтамасыз ету үшін несиелеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-05-07
approved_by:
- '157000000001'
version_date:
  kaz: 2001-05-07
  rus: 2001-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/8941/kaz/07.05.2001
  rus: https://zan.gov.kz/client/#!/doc/8941/rus/07.05.2001
