act_code: '177274'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 27 декабря 2022 года № 27/3-VII
title:
  rus: О бюджетах города, поселков и сельских округов Шемонаихинского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Шемонаиха ауданының қала, кенттер және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '157020000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/177274/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177274/rus/27.12.2022
