act_code: '128557'
requisite: Решение маслихата Бородулихинского района Восточно-Казахстанской области от 28 декабря 2018 года № 32-5-VI. Зарегистрировано Управлением юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 15 января 2019 года № 5-8-198
title:
  rus: О бюджете Новошульбинского сельского округа Бородулихинского района на 2019–2021 годы
  kaz: 2019-2021 жылдарға арналған Бородулиха ауданының Новошульба ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '157008000002'
version_date:
  kaz: 2019-04-09
  rus: 2019-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/128557/kaz/09.04.2019
  rus: https://zan.gov.kz/client/#!/doc/128557/rus/09.04.2019
caused_by:
  code: '130504'
  requisite: Решение маслихата Бородулихинского района Восточно-Казахстанской области от 9 апреля 2019 года № 37-5-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 апреля 2019 года № 5844
  title:
    rus: О внесении изменений в решение Бородулихинского районного маслихата от 28 декабря 2018 года № 32-5-VI «О бюджете Новошульбинского сельского округа Бородулихинского района на 2019 – 2021 годы»
    kaz: Бородулиха аудандық мәслихатының 2018 жылғы 28 желтоқсандағы № 32-5-VI «2019-2021 жылдарға арналған Бородулиха ауданының Новошульба ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130504/rus
