act_code: '116479'
requisite: Решение акима города Зайсан Зайсанского района Восточно-Казахстанской области от 10 ноября 2017 года № 4. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 29 ноября 2017 года № 5295. Утратило силу - решением акима города Зайсан Зайсанского района Восточно-Казахстанской области от 8 января 2018 года № 1
title:
  rus: Об установлении ограничительных мероприятий в микрорайоне «Заречный» Зайсанского городского округа
  kaz: Зайсан қала округінің «Заречный» мөлтек ауданына шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-11-10
approved_by:
- '157012009002'
version_date:
  kaz: 2017-11-10
  rus: 2017-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/116479/kaz/10.11.2017
  rus: https://zan.gov.kz/client/#!/doc/116479/rus/10.11.2017
