act_code: '138783'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 10 января 2020 года № 43/308-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 января 2020 года № 6589. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/537-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Бидайыкского сельского округа Аягозского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Аягөз ауданының Бидайық ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '157007000002'
version_date:
  kaz: 2020-09-16
  rus: 2020-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/138783/kaz/16.09.2020
  rus: https://zan.gov.kz/client/#!/doc/138783/rus/16.09.2020
caused_by:
  code: '146757'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 16 сентября 2020 года № 52/453-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 25 сентября 2020 года № 7588. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/537-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 10 января 2020 года № 43/308-VI «О бюджете Бидайыкского сельского округа Аягозского района на 2020-2022 годы»
    kaz: Аягөз аудандық мәслихатының 2020 жылғы 10 қаңтардағы № 43/308-VІ «2020-2022 жылдарға арналған Аягөз ауданының Бидайық ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146757/rus
