act_code: '80081'
requisite: Решение маслихата Урджарского района Восточно-Казахстанской области от 15 апреля 2014 года № 24-253/V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 мая 2014 года № 3325. Утратило силу решением Урджарского районного маслихата области Абай от 20 сентября 2023 года № 5-113/VIII (вводится в действие по истечении десяти календарных дней после дня первого официального опубликования)
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-04-15
approved_by:
- '157019000002'
version_date:
  kaz: 2020-10-14
  rus: 2020-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/80081/kaz/14.10.2020
  rus: https://zan.gov.kz/client/#!/doc/80081/rus/14.10.2020
caused_by:
  code: '147804'
  requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 14 октября 2020 года № 55-714/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 26 октября 2020 года № 7714. Утратило силу решением Урджарского районного маслихата области Абай от 20 сентября 2023 года № 5-113/VIII (вводится в действие по истечении десяти календарных дней после дня первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение Урджарского районного маслихата от 15 апреля 2014 года № 24-253/V «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Үржар аудандық мәслихатының 2014 жылғы 15 сәуірдегі № 24-253/V «Әлеуметтік көмек көрсетудің, мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147804/rus
