act_code: '18291'
requisite: Решение 3-ей сессии Восточно-Казахстанского областного маслихата III созыва от 26 декабря 2003 года № 3/33-III. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 22 января 2004 года № 1576. Утратило силу решением Восточно-Казахстанского областного маслихата от 9 октября 2020 года № 42/486-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении поправочных коэффициентов к базовым ставкам платы за земельные участки и границ зон в городах областного значения
  kaz: Облыстық маңызы бар қалаларда аймақтардың шекаралары және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-26
approved_by:
- '157000000002'
version_date:
  kaz: 2003-12-26
  rus: 2003-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/18291/kaz/26.12.2003
  rus: https://zan.gov.kz/client/#!/doc/18291/rus/26.12.2003
