act_code: '122246'
requisite: Решение акима Степного сельского округа Бородулихинского района Восточно-Казахстанской области от 18 мая 2018 года № 1. Зарегистрировано Управлением юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 1 июня 2018 года № 5-8-157
title:
  rus: О переименовании улиц в населенных пунктах Степного сельского округа Бородулихинского района
  kaz: Бородулиха ауданы Степной ауылдық округінің елді мекендеріндегі көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-18
approved_by:
- '157008017002'
version_date:
  kaz: 2018-05-18
  rus: 2018-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/122246/kaz/18.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122246/rus/18.05.2018
