act_code: '176840'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 27 декабря 2022 года № 27/6-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 января 2023 года № 31576
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума на 2023 год
  kaz: Кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың 2023 жылға ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '157020000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/176840/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176840/rus/27.12.2022
