act_code: '164530'
requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 30 декабря 2021 года № 15/4-VII
title:
  rus: О бюджете Бегенского сельского округа на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Беген ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '157009000002'
version_date:
  kaz: 2022-12-07
  rus: 2022-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/164530/kaz/07.12.2022
  rus: https://zan.gov.kz/client/#!/doc/164530/rus/07.12.2022
caused_by:
  code: '175743'
  requisite: Решение Бескарагайского районного маслихата области Абай от 7 декабря 2022 года № 28/3-VII
  title:
    rus: О внесении изменений в решение Бескарагайского районного маслихата от 30 декабря 2021 года № 15/4-VII «О бюджете Бегенского сельского округа на 2022-2024 годы»
    kaz: Бесқарағай аудандық мәслихатының 2021 жылғы 30 желтоқсандағы № 15/4-VII «2022-2024  жылдарға арналған Беген ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175743/rus
