act_code: '85373'
requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 23 декабря 2014 года № 30/206-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 декабря 2014 года № 3604
title:
  rus: ИМПОРТ. О бюджете города Курчатов на 2015-2017 годы
  kaz: ИМПОРТ. Курчатов қаласының 2015–2017 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '157004000002'
version_date:
  kaz: 2015-12-22
  rus: 2015-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/85373/kaz/22.12.2015
  rus: https://zan.gov.kz/client/#!/doc/85373/rus/22.12.2015
caused_by:
  code: '96811'
repealed_on: 2016-01-01
repealed_by:
  code: '100842'
  requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 23 декабря 2015 года № 41/295-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 12 января 2016 года № 4325. Утратило силу - решением Курчатовского городского маслихата Восточно-Казахстанской области от 23 декабря 2016 года № 9/52-VI
  title:
    rus: О бюджете города Курчатов на 2016-2018 годы
    kaz: Курчатов қаласының 2016–2018 жылдарға арналған бюджеті туралы
  link: https://zan.gov.kz/client/#!/doc/100842/rus
