act_code: '85373'
requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 23 декабря 2014 года № 30/206-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 декабря 2014 года № 3604
title:
  rus: ИМПОРТ. О бюджете города Курчатов на 2015-2017 годы
  kaz: ИМПОРТ. Курчатов қаласының 2015–2017 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '157004000002'
version_date:
  kaz: 2015-10-15
  rus: 2015-10-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/85373/kaz/15.10.2015
  rus: https://zan.gov.kz/client/#!/doc/85373/rus/15.10.2015
caused_by:
  code: '100797'
  requisite: Решение маслихата города Курчатов Восточно-Казахстанской области от 15 октября 2015 года № 39/285-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 21 октября 2015 года № 4203. Утратило силу - решением маслихата города Курчатов района Восточно-Казахстанской области от 23.12.2015 № 41/295-V
  title:
    rus: О внесении изменений в решение Курчатовского городского маслихата от 23 декабря 2014 года № 30/206-V «О бюджете города Курчатов на 2015 - 2017 годы»
    kaz: «Курчатов қаласының 2015-2017 жылдарға арналған бюджеті туралы» Курчатов қалалық мәслихатының 2014 жылғы 23 желтоқсандағы № 30/206-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/100797/rus
