act_code: '210178'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 12 мая 2025 года № 29/11-VІІІ
title:
  rus: Об утверждении Регламента собрания местного сообщества на территории населенных пунктов Тарбагатайского района
  kaz: Тарбағатай ауданының елді мекендері аумағындағы жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-12
approved_by:
- '157017000002'
version_date:
  kaz: 2025-05-12
  rus: 2025-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/210178/kaz/12.05.2025
  rus: https://zan.gov.kz/client/#!/doc/210178/rus/12.05.2025
