act_code: '78474'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 5 марта 2014 года № 27/139-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 3 апреля 2014 года № 3216. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 31 декабря 2021 года № 21/154-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по городу Семей
  kaz: Семей қаласы бойынша коммуналдық қалдықтардың пайда болу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-05
approved_by:
- '157003000002'
version_date:
  kaz: 2014-03-05
  rus: 2014-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/78474/kaz/05.03.2014
  rus: https://zan.gov.kz/client/#!/doc/78474/rus/05.03.2014
