act_code: '169343'
requisite: Решение акима города Семей Восточно-Казахстанской области от 22 июня 2022 года № 3. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 июня 2022 года № 28638. Утратило силу решением акима города Семей области Абай от 9 августа 2023 года № 6 (вводится в действие по истечении десяти календарных дней после его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера
  kaz: Табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-06-22
approved_by:
- '157003000003'
version_date:
  kaz: 2022-06-22
  rus: 2022-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/169343/kaz/22.06.2022
  rus: https://zan.gov.kz/client/#!/doc/169343/rus/22.06.2022
