act_code: '33210'
requisite: Шығыс Қазақстан облысы Тарбағатай ауданы әкімінің 2007 жылғы 2 мамырдағы № 4 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Тарбағатай аудандық Әділет басқармасында 2007 жылғы 10 мамырда № 5-16-38 тіркелді
title:
  rus: Ақжар ауылында ірі-қара малдарынан пастереллез ауруының шығуына байланысты шектеу кою туралы
  kaz: Ақжар ауылында ірі-қара малдарынан пастереллез ауруының шығуына байланысты шектеу кою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-05-02
approved_by:
- '157017000003'
version_date:
  kaz: 2007-05-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/33210/kaz/02.05.2007
