act_code: '56379'
requisite: Шығыс Қазақстан облысы Абай аудандық мәслихатының 2010 жылғы 28 желтоқсандағы № 26-3 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Абай ауданындағы Әділет басқармасында 2010 жылғы 31 желтоқсанда № 5-5-120 тіркелді. Күші жойылды - Шығыс Қазақстан облысы Абай аудандық мәслихатының 2012 жылғы 17 ақпандағы № 2-3 шешімімен
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-28
approved_by:
- '157006000002'
version_date:
  kaz: 2011-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/56379/kaz/08.11.2011
caused_by:
  code: '61435'
  requisite: Решение маслихата Абайского района Восточно-Казахстанской области от 8 ноября 2011 года № 32-2. Зарегистрировано Управлением юстиции Абайского района Департамента юстиции Восточно-Казахстанской области 16 ноября 2011 года за № 5-5-130. Утратило силу решением маслихата Абайского района Восточно-Казахстанской области от 17 февраля 2012 года № 2-3
  title:
    rus: О внесении изменений в решение от 28 декабря 2010 года № 26-3 "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" 2010 жылғы 28 желтоқсандағы № 26-3 шешімге өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/61435/rus
