act_code: '151764'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 46/423-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 31 декабря 2020 года № 8250
title:
  rus: О бюджете Аккайнарского сельского округа на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Аққайнар ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-30
approved_by:
- '157014000002'
version_date:
  kaz: 2021-11-16
  rus: 2021-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/151764/kaz/16.11.2021
  rus: https://zan.gov.kz/client/#!/doc/151764/rus/16.11.2021
caused_by:
  code: '161266'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 16 ноября 2021 года № 12/119-VII
  title:
    rus: О внесении изменений и дополнение в решение Катон–Карагайского районного маслихата от 30 декабря 2020 года № 46/423-VI «О бюджете Аккайнарского сельского округа на 2021-2023 годы»
    kaz: Катонқарағай аудандық мәслихатының 2020 жылғы 30 желтоқсандағы № 46/423–VI «2021-2023 жылдарға арналған Аққайнар ауылдық округінің бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161266/rus
