act_code: '57430'
requisite: Решение акима Глубоковского района Восточно-Казахстанской области от 14 февраля 2011 года № 15. Зарегистрировано управлением юстиции Глубоковского района Департамента юстиции Восточно -Казахстанской области 23 февраля 2011 года № 5-9-149. Утратило силу решением акима Глубоковского района Восточно-Казахстанской области от 26 октября 2020 года № 03 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков по Глубоковскому району
  kaz: Глубокое ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-02-14
approved_by:
- '157010000001'
version_date:
  kaz: 2011-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/57430/kaz/21.11.2011
caused_by:
  code: '61763'
  requisite: Решение акима Глубоковского района Восточно-Казахстанской области от 21 ноября 2011 года № 18. Зарегистрировано управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 7 декабря 2011 года № 5-9-157. Утратило силу решением акима Глубоковского района Восточно-Казахстанской области от 26 октября 2020 года № 03 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение от 14 февраля 2011 года № 15 "Об образовании избирательных участков по Глубоковскому району"
    kaz: '"Глубокое ауданы бойынша сайлау учаскелерін құру туралы" 2011 жылғы 14 ақпандағы № 15 шешімге өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/61763/rus
