act_code: '44725'
requisite: Решение Курчатовского городского маслихата Восточно Казахстанского области от 19 февраля 2009 года № 16/120-IV. Зарегистрировано Управлением юстиции города Курчатова Департамента юстиции Восточно-Казахстанской области 11 марта 2009 года за № 5-3-68. Утратило силу решением Курчатовского городского маслихата Восточно-Казахстанской области от 23 ноября 2018 года № 26/198-VI
title:
  rus: Об утверждения поправочных коэффициентов к базовым ставкам земельного налога
  kaz: Жер салығының базалық мөлшерлемелеріне түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-19
approved_by:
- '157004000002'
version_date:
  kaz: 2009-02-19
  rus: 2009-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/44725/kaz/19.02.2009
  rus: https://zan.gov.kz/client/#!/doc/44725/rus/19.02.2009
