act_code: '194856'
requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 20 марта 2024 года № 20/3-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 28 марта 2024 года № 8983-16
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в Курчумском районе
  kaz: Күршім ауданында  тұрғын үй көмегін көрсетудің мөлшері мен Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-20
approved_by:
- '157016000002'
version_date:
  kaz: 2026-07-21
  rus: 2026-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/194856/kaz/21.07.2026
  rus: https://zan.gov.kz/client/#!/doc/194856/rus/21.07.2026
caused_by:
  code: '228158'
  requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 21 июля 2026 года № 55/3-VIII. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 июля 2026 года № 39392
  title:
    rus: О внесении изменений в решение Курчумского районного маслихата от 20 марта 2024 года № 20/3-VIII «Об утверждении размера и Правил оказания жилищной помощи в Курчумском районе»
    kaz: Күршім аудандық мәслихатының 2024 жылғы 20 наурыздағы № 20/3-VIII «Күршім ауданында тұрғын үй көмегін көрсетудің мөлшері мен Ережесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/228158/rus
