act_code: '69712'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 21 декабря 2012 года № 12/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 4 января 2013 года № 2805. Прекращено действие по истечении срока действия (письмо Глубоковского районного маслихата от 19 декабря 2013 года № 302)
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '157010000002'
version_date:
  kaz: 2013-12-13
  rus: 2013-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/69712/kaz/13.12.2013
  rus: https://zan.gov.kz/client/#!/doc/69712/rus/13.12.2013
caused_by:
  code: '76058'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 13 декабря 2013 года № 21/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 декабря 2013 года № 3128. Прекращено действие по истечении срока действия (письмо Глубоковского районного маслихата от 19 декабря 2013 года № 302)
  title:
    rus: О внесении изменений и дополнения в решение Глубоковского районного маслихата от 21 декабря 2012 года № 12/2-V "О районном бюджете на 2013-2015 годы"
    kaz: '"2013-2015 жылдарға арналған аудандық бюджет туралы" Глубокое аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 12/2-V шешіміне өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/76058/rus
