act_code: '176663'
requisite: Решение акима Айыртауского сельского округа Уланского района Восточно-Казахстанской области от 26 декабря 2022 года № 8. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2022 года № 31447
title:
  rus: О переименовании улиц села Айыртау Айыртауского сельского округа Уланского района
  kaz: Ұлан ауданы Айыртау ауылдық округі Айыртау ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-26
approved_by:
- '157018010002'
version_date:
  kaz: 2022-12-26
  rus: 2022-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/176663/kaz/26.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176663/rus/26.12.2022
