act_code: '80169'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 15 апреля 2014 года № 24-246/V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 мая 2014 года № 3352. Утратило силу - решением Урджарского районного маслихата Восточно-Казахстанской области от 09.06.2016 № 3-35/VI
title:
  rus: Об утверждении регламента Урджарского районного маслихата
  kaz: Үржар аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-15
approved_by:
- '157019000002'
version_date:
  kaz: 2014-04-15
  rus: 2014-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/80169/kaz/15.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80169/rus/15.04.2014
