act_code: '85363'
requisite: 'Решение маслихата города Семей Восточно-Казахстанской области от 23 декабря 2014 года № 36/191-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 декабря 2014 года № 3601. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 23.12.2015 № 47/258-V '
title:
  rus: О бюджете города Семей на 2015-2017 годы
  kaz: Семей қаласының 2015-2017 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '157003000002'
version_date:
  kaz: 2015-12-22
  rus: 2015-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/85363/kaz/22.12.2015
  rus: https://zan.gov.kz/client/#!/doc/85363/rus/22.12.2015
caused_by:
  code: '96558'
  requisite: 'Решение маслихата города Семей Восточно-Казахстанской области от 22 декабря 2015 года № 47/269-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 28 декабря 2015 года № 4299. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 23.12.2015 № 47/258-V '
  title:
    rus: О внесении изменений в решение маслихата города Семей от 23 декабря 2014 года № 36/191-V «О бюджете города Семей на 2015-2017 годы»
    kaz: Семей қаласы мәслихатының 2014 жылғы 23 желтоқсандағы  № 36/191-V «Семей қаласының 2015-2017 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96558/rus
