act_code: '80286'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 23 апреля 2014 года N 26/17-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 мая 2014 года № 3363
title:
  rus: Об утверждении регламента Риддерского городского маслихата
  kaz: Риддер қалалық маслихатының регламентiн бекiту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-04-23
approved_by:
- '157005000002'
version_date:
  kaz: 2014-04-23
  rus: 2014-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/80286/kaz/23.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80286/rus/23.04.2014
