act_code: '204840'
requisite: Решение маслихата района Самар Восточно-Казахстанской области от 25 декабря 2024 года № 18-13/VIII
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по району Самар
  kaz: Самар ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын, тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '157021000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/204840/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204840/rus/25.12.2024
