act_code: '205267'
requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 27 декабря 2024 года № 31/6-VIII
title:
  rus: О бюджете Каратальского сельского округа Зайсанского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Зайсан ауданы Қаратал ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '157012000002'
version_date:
  kaz: 2025-05-12
  rus: 2025-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/205267/kaz/12.05.2025
  rus: https://zan.gov.kz/client/#!/doc/205267/rus/12.05.2025
caused_by:
  code: '210255'
  requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 12 мая 2025 года № 34/6-VIII
  title:
    rus: О внесении изменений и дополнения в решение Зайсанского районного маслихата от 27 декабря 2024 года №31/6-VIII «О бюджете  Каратальского  сельского округа Зайсанского района на 2025-2027 годы»
    kaz: Зайсан аудандық мәслихатының 2024 жылғы 27 желтоқсандағы«2025-2027 жылдарға арналғанЗайсан ауданы Қаратал ауылдық округінің бюджеті туралы» №31/6- VIII шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210255/rus
