act_code: '1149'
requisite: Решение Акима Восточно-Казахстанской области от 24 февраля 1998 года N 477-к. Зарегистрировано управлением юстиции Восточно-Казахстанской области 29 апреля 1998 года за N 11. Утратило силу решением акима ВКО от 24 сентября 2004 года N 100
title:
  rus: Об итогах социально-экономического развития области за 1997 год
  kaz: 1997 жылы облысты әлеуметтік-экономикалық дамытудың қорытындылары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-02-24
approved_by:
- '157000000001'
version_date:
  kaz: 1998-02-24
  rus: 1998-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/1149/kaz/24.02.1998
  rus: https://zan.gov.kz/client/#!/doc/1149/rus/24.02.1998
