act_code: '88101'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 25 февраля 2015 года N 33/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 31 марта 2015 года N 3794. Утратило силу решением  Глубоковского районного маслихата Восточно-Казахстанской области от 20 марта 2024 года № 10/5-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Глубоковском районе
  kaz: Глубокое ауданында тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-02-25
approved_by:
- '157010000002'
version_date:
  kaz: 2022-10-22
  rus: 2022-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/88101/kaz/22.10.2022
  rus: https://zan.gov.kz/client/#!/doc/88101/rus/22.10.2022
caused_by:
  code: '173348'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 22 октября 2022 года № 25/3-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 октября 2022 года № 30308. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 20 марта 2024 года № 10/5-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Глубоковского районного маслихата от  25 февраля 2015 года № 33/2-V «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: Глубокое аудандық мәслихатының 2015 жылғы 25 ақпандағы № 33/2-V «Тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173348/rus
