act_code: '69644'
requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 21 декабря 2012 года № 10/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 3 января 2013 года за № 2799. Утратило силу решением Бескарагайского районного маслихата Восточно-Казахстанской области от 25 декабря 2013 года № 19/11-V
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '157009000002'
version_date:
  kaz: 2013-10-10
  rus: 2013-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/69644/kaz/10.10.2013
  rus: https://zan.gov.kz/client/#!/doc/69644/rus/10.10.2013
caused_by:
  code: '74967'
  requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 10 октября 2013 года № 16/4-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 21 октября 2013 года № 3069. Күші жойылды - Шығыс Қазақстан облысы Бесқарағай аудандық мәслихатының 2013 жылғы 25 желтоқсандағы № 19/11-V шешімімен
  title:
    rus: О внесении изменений в решение Бескарагайского районного маслихата от 21 декабря 2012 года № 10/2-V "О районном бюджете на 2013-2015 годы"
    kaz: '"2013-2015 жылдарға арналған аудандық бюджет туралы" Бесқарағай аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 10/2-V шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/74967/rus
