act_code: '96807'
requisite: Решение Восточно-Казахстанского областного маслихата от 9 декабря 2015 года № 34/406-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 23 декабря 2015 года № 4287. Утратило силу - решением Восточно-Казахстанского областного маслихата от 9 декабря 2016 года № 8/86-VI
title:
  rus: Об областном бюджете на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-09
approved_by:
- '157000000002'
version_date:
  kaz: 2016-07-14
  rus: 2016-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/96807/kaz/14.07.2016
  rus: https://zan.gov.kz/client/#!/doc/96807/rus/14.07.2016
caused_by:
  code: '104901'
  requisite: Решение Восточно-Казахстанского областного маслихата от 14 июля 2016 года № 5/37-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 22 июля 2016 года № 4607. Утратило силу - решением Восточно-Казахстанского областного маслихата от 9 декабря 2016 года № 8/86-VI
  title:
    rus: О внесении изменений в решение Восточно-Казахстанского областного маслихата от 9 декабря 2015 года № 34/406-V «Об областном бюджете на 2016-2018 годы»
    kaz: «2016-2018 жылдарға арналған облыстық бюджет туралы» Шығыс Қазақстан облыстық мәслихатының 2015 жылғы 9 желтоқсандағы № 34/406-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104901/rus
