act_code: '143564'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 21 мая 2020 года № 43/8-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 4 июня 2020 года № 7150. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 3 декабря 2020 года № 53/4-VI (вводится в действие с 01.01.2021)
title:
  rus: Об установлении повышенных должностных окладов и тарифных ставок гражданским служащим сельской местности Глубоковского района
  kaz: Глубокое ауданының ауылдық жердегі азаматтық қызметшілеріне жоғарылатылған лауазымдық жалақылар мен тарифтік мөлшерлемелерді белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-05-21
approved_by:
- '157010000002'
version_date:
  kaz: 2020-05-21
  rus: 2020-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/143564/kaz/21.05.2020
  rus: https://zan.gov.kz/client/#!/doc/143564/rus/21.05.2020
