act_code: '1599'
requisite: Решение Акима Восточно-Казахстанской области от 27 апреля 1998 года N 505. Зарегистрировано управлением юстиции Восточно-Казахстанской области 7 мая 1998 года за N 12. Утратило силу решением акима ВКО от 24 сентября 2004 года N 100
title:
  rus: О передаче в управление имущественного комплекса АО "Бухтарминский речной порт" и части имущества АО "Восточно-Казахстанское речное пароходство"
  kaz: '"Бұқтырма өзен порты" акционерлік қоғамының мүліктік кешенін және "Шығыс Қазақстан өзен пароходствосы" акционерлік қоғамы мүлкінің бір бөлігін басқаруға беру туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-04-26
approved_by:
- '157000000001'
version_date:
  kaz: 1998-04-26
  rus: 1998-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/1599/kaz/26.04.1998
  rus: https://zan.gov.kz/client/#!/doc/1599/rus/26.04.1998
