act_code: '164496'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 24 декабря 2021 года № 10/194-VII
title:
  rus: О бюджете Баршатасского сельского округа Аягозского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Аягөз ауданының Баршатас ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '157007000002'
version_date:
  kaz: 2022-07-13
  rus: 2022-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/164496/kaz/13.07.2022
  rus: https://zan.gov.kz/client/#!/doc/164496/rus/13.07.2022
caused_by:
  code: '170774'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 13 июля 2022 года № 15/309-VII
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 24 декабря 2021 года № 10/194-VIІ «О бюджете Баршатасского сельского округа Аягозского района на 2022-2024 годы»
    kaz: Аягөз аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 10/194-VІI «2022-2024 жылдарға арналған Аягөз ауданының Баршатас ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170774/rus
