act_code: '52782'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 21 апреля 2010 года № 27/189-IV. Зарегистрировано Управлением юстиции города Семей Департамента юстиции Восточно-Казахстанской области 28 мая 2010 года за № 5-2-130. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 26 февраля 2015 года № 37/200-V
title:
  rus: Об утверждении Правил предоставления жилищной помощи
  kaz: Тұрғын үй көмегін көрсету жөніндегі Қағиданы бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-04-21
approved_by:
- '157003000002'
version_date:
  kaz: 2012-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/52782/kaz/18.04.2012
caused_by:
  code: '65627'
  requisite: Решение маслихата города Семей Восточно-Казахстанской области от 18 апреля 2012 года № 4/28-V. Зарегистрировано Управлением юстиции города Семей Департамента юстиции Восточно-Казахстанской области 17 мая 2012 года за № 5-2-162. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 26 февраля 2015 года № 37/200-V
  title:
    rus: О внесении изменений в решение от 21 апреля 2010 года № 27/189-IV "Об утверждении Правил предоставления жилищной помощи"
    kaz: 2010 жылғы 21 сәуірдегі № 27/189-IV "Тұрғын үй көмегін көрсету жөніндегі Қағиданы бекіту туралы" шешімге өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/65627/rus
