act_code: '52782'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 21 апреля 2010 года № 27/189-IV. Зарегистрировано Управлением юстиции города Семей Департамента юстиции Восточно-Казахстанской области 28 мая 2010 года за № 5-2-130. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 26 февраля 2015 года № 37/200-V
title:
  rus: Об утверждении Правил предоставления жилищной помощи
  kaz: Тұрғын үй көмегін көрсету жөніндегі Қағиданы бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-04-21
approved_by:
- '157003000002'
version_date:
  kaz: 2014-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/52782/kaz/05.03.2014
caused_by:
  code: '78473'
  requisite: Решение маслихата города Семей Восточно-Казахстанской области от 5 марта 2014 года № 27/141-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 31 марта 2014 года № 3214. Утратило силу - решением маслихата города Семей Восточно-Казахстанской области от 20 ноября 2015 года № 46/255-V
  title:
    rus: О внесении изменений в решение маслихата города Семей от 21 апреля 2010 года № 27/189-IV "Об утверждении Правил предоставления жилищной помощи"
    kaz: Семей қаласы мәслихатының 2010 жылғы 21 сәуірдегі № 27/189-ІV "Тұрғын үй көмегін көрсету жөніндегі Қағиданы бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/78473/rus
