act_code: '48543'
requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 22 октября 2011 года № 18/7-IV. Зарегистрировано Управлением юстиции Бескарагайского района Департамента юстиции Восточно-Казахстанской области 10 ноября 2009 года за № 5-7-71
title:
  rus: Тіркелген салық ставкаларының мөлшерін бекіту туралы
  kaz: Тіркелген салық ставкаларының мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-21
approved_by:
- '157009000002'
version_date:
  kaz: 2012-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/48543/kaz/21.12.2012
caused_by:
  code: '106695'
  requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 21 декабря 2012 года № 10/8-V
  title:
    rus: О признании утратившими силу некоторых решении Бескарагайского районного маслихата
    kaz: Бесқарағай аудандық мәслихатының кейбір шешімдерінің күші жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/106695/rus
