act_code: '166126'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 25 марта 2022 года № 14/249-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 апреля 2022 года № 27353
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по Жарминскому району Восточно-Казахстанкой области
  kaz: Шығыс Қазақстан облысы Жарма ауданы бойынша шетелдіктер үшін 2022 жылға туристік жарнаны бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-25
approved_by:
- '157011000002'
version_date:
  kaz: 2022-03-25
  rus: 2022-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/166126/kaz/25.03.2022
  rus: https://zan.gov.kz/client/#!/doc/166126/rus/25.03.2022
