act_code: '29743'
requisite: Шығыс Қазақстан облысы Тарбағатай ауданы әкімінің 2006 жылғы 12 қыркүйектегі № 11 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Тарбағатай аудандық Әділет басқармасында 2006 жылғы 20 қыркүйекте № 5-16-23 тіркелді
title:
  rus: Тарбағатай ауданының әскер жасына дейінгі және әскерге шақырылатын жастарының 2006-2007 оқу жылындағы бастапқы әскери дайындығы туралы
  kaz: Тарбағатай ауданының әскер жасына дейінгі және әскерге шақырылатын жастарының 2006-2007 оқу жылындағы бастапқы әскери дайындығы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-09-12
approved_by:
- '157017000003'
version_date:
  kaz: 2006-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/29743/kaz/12.09.2006
