act_code: '110581'
requisite: Решение акима Каратальского сельского округа Урджарского района Восточно-Казахстанской области от 4 апреля 2016 года № 11
title:
  rus: О снятии ограничительных мероприятий в селе Бекет Каратальского сельского округа
  kaz: Қаратал ауылдық округінің Бекет ауылында шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-04
approved_by:
- '157019020002'
version_date:
  kaz: 2016-04-04
  rus: 2016-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/110581/kaz/04.04.2016
  rus: https://zan.gov.kz/client/#!/doc/110581/rus/04.04.2016
