act_code: '44179'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 9 февраля 2009 года № 16-11-IV. Зарегистрировано в Управлении юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 10 февраля 2009 года за № 5-8-76. Утратило силу решением Бородулихинского районного маслихата Восточно-Казахстанской области от 13 июля 2012 года № 6-4-V
title:
  rus: Об утверждении Инструкции по предоставлению материальной помощи на компенсацию расходов на коммунальные услуги лицам, которым назначены пенсии за особые заслуги перед Республикой Казахстан и пенсионерам, имеющий статус персонального пенсионера областного значения
  kaz: Қазақстан Республикасы алдындағы ерекше еңбегі үшін зейнетақы тағайындалған адамдарға және облыстық маңызы бар дербес зейнеткер мәртебесі бар зейнеткерлерге коммуналдық қызметтерге төлеген шығындарын өтеу үшін материалдық көмек беру жөніндегі нұсқаулықты бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-09
approved_by:
- '157008000002'
version_date:
  kaz: 2009-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/44179/kaz/28.04.2009
