act_code: '58238'
requisite: Решение акима Каратуминского сельского округа Урджарского района Восточно-Казахстанской области от 14 марта 2011 года № 4. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 15 апреля 2011 года за № 5-18-118. Утратило силу решением акима Каратуминского сельского округа Урджарского района ВКО от 3 ноября 2011 года № 19
title:
  rus: Об установлении ограничения в связи со вспышкой бруцеллеза крупного и мелкого рогатого скота на территории Каратуминского сельского округа
  kaz: Қаратұма ауылдық округі аймағында ірі қара және мүйізді ұсақ малдарынан бруцеллез індетінің шығуына байланысты шектеу қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-14
approved_by:
- '157019014002'
version_date:
  kaz: 2011-03-14
  rus: 2011-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/58238/kaz/14.03.2011
  rus: https://zan.gov.kz/client/#!/doc/58238/rus/14.03.2011
