act_code: '138143'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 6 января 2020 года № 35/314-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 января 2020 года № 6578. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 14 апреля 2021 года № 5/39-VII (вводится в действие с 01.01.2021)
title:
  rus: О бюджетах сельских округов Катон-Карагайского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Катонқарағай ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-06
approved_by:
- '157014000002'
version_date:
  kaz: 2020-05-20
  rus: 2020-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/138143/kaz/20.05.2020
  rus: https://zan.gov.kz/client/#!/doc/138143/rus/20.05.2020
caused_by:
  code: '143205'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 20 мая 2020 года № 39/340-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 26 мая 2020 года № 7116. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 14 апреля 2021 года № 5/39-VII (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений и дополнений в решение Катон-Карагайского районного маслихата от 6 января 2020 года № 35/314-VI «О бюджетах сельских округов Катон-Карагайского района на 2020-2022 годы»
    kaz: Катонқарағай аудандық мәслихатының 2020 жылғы 6 қаңтардағы № 35/314–VI «2020-2022 жылдарға арналған Катонқарағай ауданының ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143205/rus
