act_code: '195747'
requisite: Решение Восточно-Казахстанского областного маслихата от 12 апреля 2024 года № 12/98-VIII
title:
  rus: Об утверждении Правил создания, содержания и защиты зеленых насаждений населенных пунктов Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысының елді мекендерінің жасыл екпелерін жасау, күтiп-баптау және қорғау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-12
approved_by:
- '157000000002'
version_date:
  kaz: 2024-04-12
  rus: 2024-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/195747/kaz/12.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195747/rus/12.04.2024
