act_code: '49721'
requisite: Шығыс Қазақстан облысы Жарма аудандық мәслихатының 2009 жылғы 28 желтоқсандағы № 17/2-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Жарма аудандық әділет басқармасында 2010 жылғы 10 қаңтарда № 5-10-92 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Жарма аудандық мәслихатының 2010 жылғы 31 желтоқсандағы № 287/4-15 хаты
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-28
approved_by:
- '157011000002'
version_date:
  kaz: 2010-10-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/49721/kaz/29.10.2010
caused_by:
  code: '55373'
  requisite: Шығыс Қазақстан облысы Жарма аудандық мәслихатының 2010 жылғы 29 қазандағы № 24/192-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Жарма аудандық әділет басқармасында 2010 жылғы 12 қарашада № 5-10-106 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Жарма аудандық мәслихатының 2010 жылғы 31 желтоқсандағы № 287/4-15 хаты
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" 2009 жылғы 28 желтоқсандағы № 17/2-IV шешімге өзгерістер енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" 2009 жылғы 28 желтоқсандағы № 17/2-IV шешімге өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/55373/rus
