act_code: '146182'
requisite: Решение акима сельского округа Полянское района Алтай Восточно-Казахстанской области от 8 сентября 2020 года № 1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 9 сентября 2020 года № 7514
title:
  rus: Об установлении права ограниченного пользования (публичный сервитут) земельными участками для размещения и эксплуатации телефонной канализации в селе Полянское
  kaz: Полянское аулында телефон кәрізін орналастыру және пайдалану үшін жер учаскелерімен (қауымдық сервитут) шектеулі пайдалану құқығын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-08
approved_by:
- '157013009002'
version_date:
  kaz: 2020-09-08
  rus: 2020-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/146182/kaz/08.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146182/rus/08.09.2020
