act_code: '112103'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 6 апреля 2017 года № 13/91-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 5 мая 2017 года № 5011
title:
  rus: Об определении мер социальной поддержки на 2017 год специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты города Семей
  kaz: Семей қаласының ауылдық елдi мекендеріне жұмыс iстеу және тұру үшiн келген денсаулық сақтау, бiлiм беру, әлеуметтiк қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға 2017 жылға арналған әлеуметтiк қолдау шараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-04-06
approved_by:
- '157003000002'
version_date:
  kaz: 2017-04-06
  rus: 2017-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/112103/kaz/06.04.2017
  rus: https://zan.gov.kz/client/#!/doc/112103/rus/06.04.2017
