act_code: '43716'
requisite: Шығыс Қазақстан облысы Абай ауданының әкімінің 2008 жылғы 23 желтоқсандағы № 41 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Абай ауданындағы Әділет басқармасында 2009 жылғы 23 қаңтарда № 5-5-86 тіркелді. Күші жойылды - Шығыс Қазақстан облысы Абай ауданының әкімдігінің 2009 жылғы 16 сәуірдегі № 4 шешімімен
title:
  rus: 1992 жылғы туған ер азаматтарды 2009 жылы Абай ауданының шақыру учаскесінде тіркеуден өткізу туралы
  kaz: 1992 жылғы туған ер азаматтарды 2009 жылы Абай ауданының шақыру учаскесінде тіркеуден өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '157006000001'
version_date:
  kaz: 2008-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43716/kaz/23.12.2008
