act_code: '58317'
requisite: Решение акима Маканчинского сельского округа Урджарского района Восточно-Казахстанской области от 18 марта 2011 года № 15. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 20 апреля 2011 года за № 5-18-119. Утратило силу - решением акима Маканчинского сельского округа Урджарского района Восточно-Казахстанской Области от 23 ноября 2011 года № 73
title:
  rus: Об установлении ограничения в связи со вспышкой бруцеллеза крупного и мелкого рогатого скота на территории Маканчинского сельского округа
  kaz: Мақаншы ауылдық округі аймағында ірі қара және мүйізді ұсақ малдарынан бруцеллез індетінің шығуына байланысты шектеу қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-18
approved_by:
- '157019022002'
version_date:
  kaz: 2011-03-18
  rus: 2011-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/58317/kaz/18.03.2011
  rus: https://zan.gov.kz/client/#!/doc/58317/rus/18.03.2011
