act_code: '3076'
requisite: Решение Акима Восточно-Казахстанской области от 7 декабря 1998 года № 616. Зарегистрировано управлением юстиции Восточно-Казахстанской области 8 декабря 1998 года за № 118. Утратило силу решением акима Восточно-Казахстанской области от 24 сентября 2004 года № 100
title:
  rus: О неотложных мерах защиты населения Восточно-Казахстанской области от туберкулеза
  kaz: Шығыс Қазақстан облысының халқын туберкулезден қорғаудың шұғыл шаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-12-07
approved_by:
- '157000000001'
version_date:
  kaz: 1998-12-07
  rus: 1998-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/3076/kaz/07.12.1998
  rus: https://zan.gov.kz/client/#!/doc/3076/rus/07.12.1998
