act_code: '92762'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 14 июля 2015 года № 29/250-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 13 августа 2015 года № 4105. Утратило силу - решением Жарминского районного маслихата Восточно-Казахстанской области от 16 октября 2015 года № 32/273-V
title:
  rus: О повышении ставок земельного  налога по Жарминскому району
  kaz: Жарма ауданы бойынша жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-14
approved_by:
- '157011000002'
version_date:
  kaz: 2015-07-14
  rus: 2015-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/92762/kaz/14.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92762/rus/14.07.2015
