act_code: '109590'
requisite: Решение акима Балыкшинского сельского округа города Атырау Атырауской области от 27 декабря 2016 года № 383. Зарегистрировано Департаментом юстиции Атырауской области 26 января 2017 года № 3774
title:
  rus: О присвоении наименовании улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-27
approved_by:
- '157016005001'
version_date:
  kaz: 2016-12-27
  rus: 2016-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/109590/kaz/27.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109590/rus/27.12.2016
