act_code: '37927'
requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 8 февраля 2008 года № 5/4. Зарегистрировано управлением юстиции города Усть-Каменогорска Восточно-Казахстанской области 25 февраля 2008 года за № 5-1-79. Утратило силу - решением Усть-Каменогорского городского маслихата от 12 августа 2008 года № 9/4
title:
  rus: О стоимости разовых талонов
  kaz: Біржолғы талондардың құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-08
approved_by:
- '157002000002'
version_date:
  kaz: 2008-02-08
  rus: 2008-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/37927/kaz/08.02.2008
  rus: https://zan.gov.kz/client/#!/doc/37927/rus/08.02.2008
