act_code: '139520'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 30 декабря 2019 года № 341. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 22 января 2020 года № 6682. Утратило силу решением Уланского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 439 (вводится в действие с 01.01.2021)
title:
  rus: О бюджете сельских округов и поселков Уланского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Ұлан ауданының ауылдық округтер мен кенттер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '157018000002'
version_date:
  kaz: 2020-10-21
  rus: 2020-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/139520/kaz/21.10.2020
  rus: https://zan.gov.kz/client/#!/doc/139520/rus/21.10.2020
caused_by:
  code: '148152'
  requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 21 октября 2020 года № 405. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 3 ноября 2020 года № 7756. Утратило силу решением Уланского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 439 (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Уланского районного маслихата от 30 декабря 2019 года № 341 «О бюджете сельских округов и поселков Уланского района на 2020-2022»
    kaz: Ұлан аудандық мәслихатының 2019 жылдың 30 желтоқсандағы № 341 «2020-2022 жылдарға арналған Ұлан ауданының ауылдық округтер мен кенттер бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148152/rus
