act_code: '132799'
requisite: Решение маслихата Абайского района Восточно-Казахстанской области от 18 июня 2019 года № 36/2-VІ. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 24 июня 2019 года № 6031. Утратило силу решением Абайского районного маслихата области Абай от 29 ноября 2023 года № 10/17-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
  kaz: Әлеуметтiк көмек көрсетудiң, оның мөлшерлерiн белгiлеудiң және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың Қағидаларын бекiту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-06-18
approved_by:
- '157006000002'
version_date:
  kaz: 2023-07-12
  rus: 2023-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/132799/kaz/12.07.2023
  rus: https://zan.gov.kz/client/#!/doc/132799/rus/12.07.2023
caused_by:
  code: '184070'
  requisite: Решение Абайского районного маслихата области Абай от 12 июля 2023 года № 4/13-VIII. Зарегистрировано Департаментом юстиции области Абай 18 июля 2023 года № 101-18. Утратило силу решением Абайского районного маслихата области Абай от 29 ноября 2023 года № 10/17-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Абайского районного маслихата от 18 июня 2019 года № 36/2-VI «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Абай аудандық мәслихатының 2019 жылғы 18 маусымдағы № 36/2-VI «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184070/rus
