act_code: '117778'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 29 декабря 2017 года № 18/133-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 января 2018 года № 5427. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 29 декабря 2018 года № 33/223-VI
title:
  rus: О бюджетах города Аягоз, Актогайского поселкового округа, Баршатасского сельского округа, Мамырсуского сельского округа, Тарлаулинского сельского округа, Тарбагатайского сельского округа на 2018-2020 годы
  kaz: 2018-2020  жылдарға арналған Аягөз қаласының, Ақтоғай кенттік округінің, Баршатас ауылдық округінің, Мамырсу ауылдық округінің, Тарлаулы ауылдық округінің, Тарбағатай ауылдық округінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-29
approved_by:
- '157007000002'
version_date:
  kaz: 2018-09-21
  rus: 2018-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/117778/kaz/21.09.2018
  rus: https://zan.gov.kz/client/#!/doc/117778/rus/21.09.2018
caused_by:
  code: '124937'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 21 сентября 2018 года № 28/194-VI. Зарегистрировано Управлением юстиции Аягозского района Департамента юстиции Восточно-Казахстанской области 26 сентября 2018 года № 5-6-181. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 29 декабря 2018 года № 33/223-VI
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 29 декабря 2017 года № 18/133-VI «О бюджетах города Аягоз, Актогайского поселкового округа, Баршатасского сельского округа, Мамырсуского сельского округа, Тарлаулинского сельского округа, Тарбагатайского сельского округа на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған Аягөз қаласының, Ақтоғай кенттік округінің, Баршатас ауылдық округінің, Мамырсу ауылдық округінің, Тарлаулы ауылдық округінің, Тарбағатай ауылдық округінің бюджеттері туралы» Аягөз аудандық мәслихатының 2017 жылғы 29 желтоқсандағы № 18/133-VІ шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124937/rus
