act_code: '109640'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 23 декабря 2016 года № 8/69-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 января 2017 года № 4870. Утратило силу решением Аягозского районного маслихата области Абай от 24 января 2024 года № 11/195-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки по городу Аягоз
  kaz: Аягөз қаласы бойынша бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерiн бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-23
approved_by:
- '157007000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/109640/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109640/rus/23.12.2016
