act_code: '190276'
requisite: Решение Восточно-Казахстанского областного маслихата от 15 декабря 2023 года № 9/69-VІІІ
title:
  rus: Об областном бюджете на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-15
approved_by:
- '157000000002'
version_date:
  kaz: 2024-11-15
  rus: 2024-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/190276/kaz/15.11.2024
  rus: https://zan.gov.kz/client/#!/doc/190276/rus/15.11.2024
caused_by:
  code: '202998'
  requisite: Решение Восточно-Казахстанского областного маслихата от 15 ноября 2024 года № 18/138-VIII
  title:
    rus: О внесении изменений в решение Восточно-Казахстанского областного маслихата от 15 декабря 2023 года № 9/69-VIII «Об областном бюджете на 2024-2026 годы»
    kaz: «2024-2026 жылдарға арналған облыстық бюджет туралы» Шығыс Қазақстан облыстық мәслихатының 2023 жылғы 15 желтоқсандағы № 9/69-VIII шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202998/rus
