act_code: '61088'
requisite: Решение акима Урджарского сельского округа Урджарского района Восточно-Казахстанской области от 26 октября 2011 года № 54. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 4 ноября 2011 года за № 5-18-133
title:
  rus: О переименовании улицы в селе Урджар
  kaz: Үржар ауылындағы көшенің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-10-26
approved_by:
- '157019001001'
version_date:
  kaz: 2011-10-26
  rus: 2011-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/61088/kaz/26.10.2011
  rus: https://zan.gov.kz/client/#!/doc/61088/rus/26.10.2011
