act_code: '155948'
requisite: Решение акима Киндиктинского сельского округа Тарбагатайского района Восточно-Казахстанской области от 5 мая 2021 года № 6. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 мая 2021 года № 8755
title:
  rus: О присвоении наименования безымянной улице в селе Киндикти Киндиктинского сельского округа
  kaz: Кіндікті ауылдық округінің Кіндікті ауылындағы атауы жоқ көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-05-05
approved_by:
- '157017009002'
version_date:
  kaz: 2021-05-05
  rus: 2021-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/155948/kaz/05.05.2021
  rus: https://zan.gov.kz/client/#!/doc/155948/rus/05.05.2021
