act_code: '120642'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 27 марта 2018 года № 20/3-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 апреля 2018 года № 5596
title:
  rus: О ставках фиксированного налога
  kaz: Тіркелген салық мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-27
approved_by:
- '157005000002'
version_date:
  kaz: 2018-03-27
  rus: 2018-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/120642/kaz/27.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120642/rus/27.03.2018
