act_code: '128668'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 28 декабря 2018 года № 265. Зарегистрировано Управлением юстиции Уланского района Департамента юстиции Восточно-Казахстанской области 17 января 2019 года № 5-17-213. Утратило силу решением Уланского районного маслихата Восточно-Казахстанской области от 30 декабря 2019 года № 341 (вводится в действие с 01.01.2020)
title:
  rus: О бюджетах поселков и сельских округов Уланского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Ұлан ауданының кенттер мен ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '157018000002'
version_date:
  kaz: 2018-12-28
  rus: 2018-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/128668/kaz/28.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128668/rus/28.12.2018
