act_code: '151544'
requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 29 декабря 2020 года № 62/4-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 31 декабря 2020 года № 8186
title:
  rus: О бюджете Бегенского сельского округа на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Беген ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '157009000002'
version_date:
  kaz: 2021-07-22
  rus: 2021-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/151544/kaz/22.07.2021
  rus: https://zan.gov.kz/client/#!/doc/151544/rus/22.07.2021
caused_by:
  code: '157818'
  requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 22 июля 2021 года № 7/4-VII
  title:
    rus: О внесении изменений в решение Бескарагайского районного маслихата Восточно-Казахстанской области от 29 декабря 2020 года № 62/4-VI «О бюджете Бегенского сельского округа на 2021-2023 годы»
    kaz: Шығыс Қазақстан облысы Бесқарағай аудандық мәслихатының 2020 жылғы 29 желтоқсандағы № 62/4-VІ «2021-2023 жылдарға арналған Беген ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157818/rus
