act_code: '219587'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 23 декабря 2025 года № 34/372-VIII
title:
  rus: Об утверждении бюджета Урыльского сельского округа на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Өрел ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-23
approved_by:
- '157014000002'
version_date:
  kaz: 2026-05-26
  rus: 2026-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/219587/kaz/26.05.2026
  rus: https://zan.gov.kz/client/#!/doc/219587/rus/26.05.2026
caused_by:
  code: '225619'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 26 мая 2026 года № 36/402-VIII
  title:
    rus: О внесении изменений в решение Катон-Карагайского районного маслихата от 23 декабря 2025 года № 34/372-VIII «О бюджете Урыльского сельского округа на 2026-2028 годы»
    kaz: Катонқарағай аудандық мәслихатының 2025 жылғы 23 желтоқсандағы № 34/372–VIII  «2026-2028 жылдарға арналған Өрел ауылдық округінің бюджеті туралы» шешіміне өзерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225619/rus
