act_code: '67529'
requisite: Решение Абайского районного маслихата Восточно-Казахстанской области от 21 августа 2012 года № 6-4. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 12 сентября 2012 года за № 2647. Утратило силу решением Абайского районного маслихата Восточно-Казахстанской области от 21 декабря 2012 года № 10-7
title:
  rus: Об утверждении стоимости разовых талонов
  kaz: Бір жолғы талондардың құнын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-08-21
approved_by:
- '157006000002'
version_date:
  kaz: 2012-08-21
  rus: 2012-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/67529/kaz/21.08.2012
  rus: https://zan.gov.kz/client/#!/doc/67529/rus/21.08.2012
