act_code: '146267'
requisite: Решение акима Акжальского сельского округа Жарминского района Восточно-Казахстанской области от 1 сентября 2020 года № 3. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 сентября 2020 года № 7521
title:
  rus: О переименование улиц села Жанаозен Акжальского сельского округа Жарминского района
  kaz: Жарма ауданы Ақжал ауылдық округі Жаңаөзен ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-01
approved_by:
- '157011001002'
version_date:
  kaz: 2020-09-01
  rus: 2020-09-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/146267/kaz/01.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146267/rus/01.09.2020
