act_code: '5380'
requisite: Решение акима Восточно-Казахстанской области от 4 февраля  2000 года № 806. Зарегистрировано управлением юстиции Восточно- Казахстанской области 16 февраля 2000 года за № 266. Утратило силу - решением акима Восточно-Казахстанской области от 28 июля 2004 года № 90
title:
  rus: О ликвидации Зыряновского рудника
  kaz: Зырян кенішін тарату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-02-04
approved_by:
- '157000000001'
version_date:
  kaz: 2000-02-04
  rus: 2000-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/5380/kaz/04.02.2000
  rus: https://zan.gov.kz/client/#!/doc/5380/rus/04.02.2000
