act_code: '147157'
requisite: Решение акима Баскольского сельского округа Бескарагайского района Восточно-Казахстанской области от 6 октября 2020 года № 11. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 6 октября 2020 года № 7626. Утратило силу решением акима Баскольского сельского округа Бескарагайского района Восточно-Казахстанской области от 5 ноября 2020 года № 12 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении карантина на территории села Башкуль Баскольского сельского округа Бескарагайского района
  kaz: Бесқарағай ауданы Баскөл ауылдық округінің Башкөл ауылының аумағына карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-10-06
approved_by:
- '157009002002'
version_date:
  kaz: 2020-10-06
  rus: 2020-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/147157/kaz/06.10.2020
  rus: https://zan.gov.kz/client/#!/doc/147157/rus/06.10.2020
