act_code: '134122'
requisite: Решение акима Тоскаинского сельского округа Курчумского района Восточно-Казахстанской области от 15 августа 2019 года № 1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 августа 2019 года № 6120. Утратило силу решением акима Тоскаинского сельского округа Курчумского района Восточно-Казахстанской области от 3 февраля 2020 года № 1 (вводится в действие по истечении десяти календарных дней после его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий в селе Шанагаты Тоскаинского сельского округа Курчумского района
  kaz: Күршім ауданының Төсқайың ауылдық округіне қарасты Шанағаты ауылында шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-08-15
approved_by:
- '157016012002'
version_date:
  kaz: 2019-08-15
  rus: 2019-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/134122/kaz/15.08.2019
  rus: https://zan.gov.kz/client/#!/doc/134122/rus/15.08.2019
