act_code: '5439'
requisite: Решение Акима Восточно-Казахстанской области от 15 февраля 2000 г. № 811. Зарегистрировано управлением юстиции Восточно-Казахстанской области 22 февраля 2000 г. за № 269. Утратило силу решением акима ВКО от 22 февраля 2001 года № 995
title:
  rus: О формировании и использовании средств Восточно-Казахстанского областного фонда охраны окружающей среды на 2000 год
  kaz: Шығыс Қазақстан облыстық қоршаған ортаны қорғау қорының 2000 жылға арналған қаражатын калыптастыру және пайдалану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-02-15
approved_by:
- '157000000003'
version_date:
  kaz: 2000-02-15
  rus: 2000-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/5439/kaz/15.02.2000
  rus: https://zan.gov.kz/client/#!/doc/5439/rus/15.02.2000
