act_code: '145017'
requisite: Решение Кокпектинского районного маслихата Восточно-Казахстанской области от 3 июля 2020 года № 48-5/5. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 22 июля 2020 года № 7385
title:
  rus: Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Кокпектинского района
  kaz: Көкпекті ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету Қағидалары мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-03
approved_by:
- '157015000002'
version_date:
  kaz: 2026-03-18
  rus: 2026-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/145017/kaz/18.03.2026
  rus: https://zan.gov.kz/client/#!/doc/145017/rus/18.03.2026
caused_by:
  code: '223645'
  requisite: Решение Кокпектинского районного маслихата области Абай от 18 марта 2026 года № 41-2. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 марта 2026 года № 38187
  title:
    rus: О внесении изменений и дополнения в решение Кокпектинского районного маслихата от 3 июля 2020 года № 48-5/5 «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Кокпектинского района»
    kaz: Көкпекті аудандық мәслихатының 2020 жылғы 3 шілдедегі № 48-5/5 «Көкпекті ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен көрсетілетін коммуналдық қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібі мен мөлшерін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223645/rus
