act_code: '65496'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 11 апреля 2012 года N 3-6. Зарегистрировано управлением юстиции Тарбагатайского района Департамента юстиции Восточно-Казахстанской области 14 мая 2012 года за N 5-16-129. Утратило силу - решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 28 января 2015 года N 24-2
title:
  rus: Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам) Тарбагатайского района
  kaz: Тарбағатай ауданының аз қамтылған отбасыларына (азаматтарына) тұрғын үй көмегін көрсету Қағиданы бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-04-11
approved_by:
- '157017000002'
version_date:
  kaz: 2014-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/65496/kaz/27.03.2014
caused_by:
  code: '79322'
  requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 27 марта 2014 года № 19-11. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 24 апреля 2014 года № 3246. Утратило силу - решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 28 января 2015 года № 24-2
  title:
    rus: О внесении изменений в решение Тарбагатайского районного маслихата от 11 апреля 2012 года № 3-6 "Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам) Тарбагатайского района"
    kaz: '"Тарбағатай ауданының аз қамтылған отбасыларына (азаматтарына) тұрғын  үй көмегін көрсету ережесін бекіту туралы" 2012 жылғы 11 сәуірдегі № 3-6 Тарбағатай аудандық мәслихатының шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/79322/rus
