act_code: '65496'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 11 апреля 2012 года N 3-6. Зарегистрировано управлением юстиции Тарбагатайского района Департамента юстиции Восточно-Казахстанской области 14 мая 2012 года за N 5-16-129. Утратило силу - решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 28 января 2015 года N 24-2
title:
  rus: Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам) Тарбагатайского района
  kaz: Тарбағатай ауданының аз қамтылған отбасыларына (азаматтарына) тұрғын үй көмегін көрсету Қағиданы бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-04-11
approved_by:
- '157017000002'
version_date:
  kaz: 2013-12-25
  rus: 2013-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/65496/kaz/25.12.2013
  rus: https://zan.gov.kz/client/#!/doc/65496/rus/25.12.2013
caused_by:
  code: '76983'
  requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 25 декабря 2013 года № 18-16. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 21 января 2014 года № 3174. Утратило силу решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 27 марта 2020 года № 52-7 (вводится в действие с 01.01.2020)
  title:
    rus: О внесении изменений в решение Тарбагатайского районного маслихата от 11 апреля 2012 года № 3-6 "Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам) Тарбагатайского района"
    kaz: '"Тарбағатай ауданының аз қамтылған отбасыларына (азаматтарына) тұрғын үй көмегін көрсету ережесін бекіту туралы" Тарбағатай аудандық мәслихатының 2012 жылғы 11 сәуірдегі № 3-6 шешімге өзгерістер енгізу туралы"'
  link: https://zan.gov.kz/client/#!/doc/76983/rus
