act_code: '65496'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 11 апреля 2012 года N 3-6. Зарегистрировано управлением юстиции Тарбагатайского района Департамента юстиции Восточно-Казахстанской области 14 мая 2012 года за N 5-16-129. Утратило силу - решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 28 января 2015 года N 24-2
title:
  rus: Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам) Тарбагатайского района
  kaz: Тарбағатай ауданының аз қамтылған отбасыларына (азаматтарына) тұрғын үй көмегін көрсету Қағиданы бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-04-11
approved_by:
- '157017000002'
version_date:
  rus: 2012-04-11
source:
  rus: https://zan.gov.kz/client/#!/doc/65496/rus/11.04.2012
