act_code: '135143'
requisite: Решение акима поселка Новая Бухтарма района Алтай Восточно-Казахстанской области от 2 октября 2019 года № 1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 7 октября 2019 года № 6188
title:
  rus: О наименовании и переименовании улиц поселка Новая Бухтарма района Алтай
  kaz: Алтай ауданы Жаңа Бұқтырма кентінің көшелеріне атау беру және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-02
approved_by:
- '157013003001'
version_date:
  kaz: 2019-10-02
  rus: 2019-10-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/135143/kaz/02.10.2019
  rus: https://zan.gov.kz/client/#!/doc/135143/rus/02.10.2019
