act_code: '43818'
requisite: Шығыс Қазақстан облысы Зайсан аудандық мәслихатының 2008 жылғы 23 желтоқсандағы № 10-1 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Зайсан аудандық әділет басқармасында 2008 жылғы 31 желтоқсанда № 5-11-87 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Зайсан аудандық мәслихатының 2010 жылғы 6 қаңтардағы № 4 хаты
title:
  rus: Зайсан ауданының 2009 жылға арналған бюджеті туралы
  kaz: Зайсан ауданының 2009 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '157012000002'
version_date:
  kaz: 2009-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/43818/kaz/20.07.2009
caused_by:
  code: '47074'
  requisite: Шығыс Қазақстан облысы Зайсан аудандық мәслихатының 2009 жылғы 20 шілдедегі № 14-4/1 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Зайсан аудандық әділет басқармасында 2009 жылғы 24 шілдеде № 5-11-100 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Зайсан аудандық мәслихатының 2010 жылғы 6 қаңтардағы № 4 хаты
  title:
    rus: '"Зайсан ауданының 2009 жылға арналған бюджеті туралы" 2008 жылғы 23 желтоқсандағы № 10-1 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"Зайсан ауданының 2009 жылға арналған бюджеті туралы" 2008 жылғы 23 желтоқсандағы № 10-1 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/47074/rus
