act_code: '164854'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 27 декабря 2021 года № 14/7-VII
title:
  rus: Об утверждении Планов по управлению пастбищами и их использованию по Глубоковскому району на 2022-2023 годы
  kaz: Глубокое ауданы бойынша 2022-2023 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарларды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '157010000002'
version_date:
  kaz: 2021-12-27
  rus: 2021-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/164854/kaz/27.12.2021
  rus: https://zan.gov.kz/client/#!/doc/164854/rus/27.12.2021
