act_code: '222094'
requisite: Решение акима района Алтай Восточно-Казахстанской области от 12 февраля 2026 года № 1
title:
  rus: Об образовании избирательных участков на территории района Алтай
  kaz: Алтай ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-02-12
approved_by:
- '157013000003'
version_date:
  kaz: 2026-02-12
  rus: 2026-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/222094/kaz/12.02.2026
  rus: https://zan.gov.kz/client/#!/doc/222094/rus/12.02.2026
