act_code: '57637'
requisite: Решение акима Курчумского района Восточно-Казахстанской области от 18 февраля 2011 года № 49. Зарегистрировано Управлением юстиции Курчумского района Департамента юстиции Восточно-Казахстанской области 10 марта 2011 года за № 5-14-122. Утратило силу в связи с окончанием срока применения решением акима Курчумского района от 16 июля 2011 года № 52
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-02-18
approved_by:
- '157016000001'
version_date:
  kaz: 2011-02-18
  rus: 2011-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/57637/kaz/18.02.2011
  rus: https://zan.gov.kz/client/#!/doc/57637/rus/18.02.2011
