act_code: '3075'
requisite: Решение XVIII сессии Восточно-Казахстанского областного маслихата от 17 сентября 1998 года № 18/11. Зарегистрировано управлением юстиции Восточно-Казахстанской области 9 октября 1998 года за № 100. Утратило силу - решением Восточно-Казахстанского областного маслихата от 7 июля 2006 года № 18/278-III
title:
  rus: О Правилах безопасности граждан на водоемах Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысының су қоймаларында шомылатын азаматтардың қауіпсіздік ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 1998-09-16
approved_by:
- '157000000002'
version_date:
  kaz: 1998-09-16
  rus: 1998-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/3075/kaz/16.09.1998
  rus: https://zan.gov.kz/client/#!/doc/3075/rus/16.09.1998
