act_code: '76630'
requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 26 декабря 2013 года № 27/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 января 2014 года № 3152. Утратило силу (письмо аппарата маслихата Зыряновского района Восточно-Казахстанской области от 5 января 2015 года № 4-9-1)
title:
  rus: О бюджете Зыряновского района на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған Зырян ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-26
approved_by:
- '157013000002'
version_date:
  kaz: 2014-07-23
  rus: 2014-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/76630/kaz/23.07.2014
  rus: https://zan.gov.kz/client/#!/doc/76630/rus/23.07.2014
caused_by:
  code: '81796'
  requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 23 июля 2014 года № 33/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 5 августа 2014 года № 3439. Утратило силу (письмо аппарата маслихата Зыряновского района Восточно-Казахстанской области от 5 января 2015 года № 4-9-1)
  title:
    rus: О внесении изменений в решение маслихата Зыряновского района от 26 декабря 2013 года № 27/2-V "О бюджете Зыряновского района на 2014-2016 годы"
    kaz: '"2014-2016 жылдарға арналған Зырян ауданының бюджеті туралы" Зырян ауданының мәслихатының 2013 жылғы 26 желтоқсандағы № 27/2-V шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/81796/rus
