act_code: '148960'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 23 ноября 2020 года № 52/499-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 26 ноября 2020 года № 7868. Утратило силу решением Жарминского районного маслихата области Абай от 4 марта 2024 года № 11/210-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования, норм их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению, границ прилегающих территорий, в которых запрещено проведение пикетирования в Жарминском районе
  kaz: Жарма ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды белгілеу, олардың пайдалану тәртібі, олардың шекті толу нормалары, сондай-ақ материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптар, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-23
approved_by:
- '157011000002'
version_date:
  kaz: 2020-11-23
  rus: 2020-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/148960/kaz/23.11.2020
  rus: https://zan.gov.kz/client/#!/doc/148960/rus/23.11.2020
