act_code: '139011'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 13 января 2020 года № 51-9. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 21 января 2020 года № 6664. Утратило силу решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 67-9 (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Киндиктинского сельского округа Тарбагатайского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Тарбағатай ауданы Кіндікті ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '157017000002'
version_date:
  kaz: 2020-01-13
  rus: 2020-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/139011/kaz/13.01.2020
  rus: https://zan.gov.kz/client/#!/doc/139011/rus/13.01.2020
