act_code: '3580'
requisite: Решение акима Восточно-Казахстанской области от 19 июля 1999 года № 713. Зарегистрировано управлением юстиции Восточно-Казахстанской области 23 июля 1999 года за № 212. Утратило силу решением акима Восточно-Казахстанской области от 19 августа 2004 года № 94
title:
  rus: О погашении задолженности за ремонт учреждений образования частному предприятию "Роза"
  kaz: '"Роза" жекеменшік кәсіпорынға білім мекемелерін жөндеу үшін берешектерін өтеу туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-07-18
approved_by:
- '157000000003'
version_date:
  kaz: 1999-07-18
  rus: 1999-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/3580/kaz/18.07.1999
  rus: https://zan.gov.kz/client/#!/doc/3580/rus/18.07.1999
