act_code: '82235'
requisite: Решение маслихата Тарбагатайского района Восточно-Казахстанской области от 22 июля 2014 года № 21-13. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 18 августа 2014 года № 3459. Утратило силу решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 2 июля 2018 года № 27-6
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтiк көмек көрсетудiң, оның мөлшерлерiн белгiлеудiң және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың қағидаларын  бекiту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-07-22
approved_by:
- '157017000002'
version_date:
  kaz: 2014-07-22
  rus: 2014-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/82235/kaz/22.07.2014
  rus: https://zan.gov.kz/client/#!/doc/82235/rus/22.07.2014
