act_code: '11945'
requisite: Решение XIV сессии Восточно-Казахстанского областного маслихата II созыва от 29 марта 2002 года N 14/10-II. Зарегистрировано управлением юстиции Восточно-Казахстанской области 22 апреля 2002 года за N 788. Утратило силу решением ВКО маслихата от 3 июля 2004 года N 6/80-III
title:
  rus: Об утверждении Положения о порядке предоставления малообеспеченным гражданам жилищной помощи на содержание жилья и оплату жилищно-коммунальных услуг
  kaz: Тұрмысы төмен азаматтарға үйді ұстауға және үй-коммуналдық қызметке ақы төлеу үшін тұрғын үй жәрдемақыларын беру тәртібі туралы Ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2002-03-29
approved_by:
- '157000000002'
version_date:
  kaz: 2002-03-29
  rus: 2002-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/11945/kaz/29.03.2002
  rus: https://zan.gov.kz/client/#!/doc/11945/rus/29.03.2002
