act_code: '44178'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 9 февраля 2009 года № 16-12-IV. Зарегистрировано Управлением юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 10 февраля 2009 года за № 5-8-75. Утратило силу решением Бородулихинского районного маслихата Восточно-Казахстанской области от 13 июля 2012 года № 6-4-V
title:
  rus: Об утверждении Инструкции по оказанию социальной помощи отдельным категориям граждан Бородулихинского района
  kaz: Бородулиха ауданы азаматтарының жекелеген санаттарына әлеуметтік көмек беруді көрсету бойынша нұсқаулықты бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-09
approved_by:
- '157008000002'
version_date:
  kaz: 2009-02-09
  rus: 2009-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/44178/kaz/09.02.2009
  rus: https://zan.gov.kz/client/#!/doc/44178/rus/09.02.2009
