act_code: '109184'
requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области 23 декабря 2016 года № 8/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 9 января 2017 года № 4804
title:
  rus: «О бюджете Бескарагайского района на 2017-2019 годы»
  kaz: «2017-2019 жылдарға арналған Бесқарағай ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-23
approved_by:
- '157009000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/109184/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109184/rus/23.12.2016
