act_code: '138948'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 20 января 2020 года № 48-571/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 21 января 2020 года № 6656. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 29 декабря 2020 года № 57-779/VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Салкынбельского сельского округа Урджарского района на 2020-2022 годы
  kaz: Үржар ауданы Салқынбел ауылдық округінің 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-20
approved_by:
- '157019000002'
version_date:
  kaz: 2020-07-09
  rus: 2020-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/138948/kaz/09.07.2020
  rus: https://zan.gov.kz/client/#!/doc/138948/rus/09.07.2020
caused_by:
  code: '144881'
  requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 9 июля 2020 года № 53-667/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 июля 2020 года № 7352
  title:
    rus: О внесении изменений в решение Урджарского районного маслихата от 20 января 2020 года № 48-571/VI «О бюджете Салкынбельского сельского округа Урджарского района на 2020-2022 годы»
    kaz: Үржар аудандық мәслихатының 2020 жылғы 20 қаңтардағы № 48-571/VI «2020-2022 жылдарға арналған Үржар ауданы Салқынбел ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144881/rus
