act_code: '42794'
requisite: Шығыс Қазақстан облысы Ұлан ауданы әкімінің 2008 жылғы 9 желтоқсандағы № 9 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Ұлан аудандық Әділет басқармасында 2008 жылғы 18 желтоқсанда № 5-17-93 тіркелді. Күші жойылды - Ұлан ауданы әкімдігінің 2009 жылғы 3 шілдедегі № 05/2059 хатымен
title:
  rus: 2009 жылы Ұлан ауданының Қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне тіркеу жылы он жеті жасқа толған еркек жынысты азаматтарын тіркеуді өткізу туралы
  kaz: 2009 жылы Ұлан ауданының Қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне тіркеу жылы он жеті жасқа толған еркек жынысты азаматтарын тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-09
approved_by:
- '157018000001'
version_date:
  kaz: 2008-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/42794/kaz/09.12.2008
