act_code: '138512'
requisite: Решение маслихата района Алтай Восточно-Казахстанской области от 5 января 2020 года № 61/6-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 января 2020 года № 6522. Утратило силу решением маслихата района Алтай Восточно-Казахстанской области от 25 декабря 2020 года № 77/7-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете поселка Октябрьский на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Октябрьск кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-05
approved_by:
- '157013000002'
version_date:
  kaz: 2020-12-09
  rus: 2020-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/138512/kaz/09.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138512/rus/09.12.2020
caused_by:
  code: '149897'
  requisite: Решение маслихата района Алтай Восточно-Казахстанской области от 9 декабря 2020 года № 74/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 декабря 2020 года № 7975. Утратило силу решением маслихата района Алтай Восточно-Казахстанской области от 25 декабря 2020 года № 77/7-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений и дополнения в решение маслихата района Алтай от 5 января 2020 года № 61/6-VI «О бюджете поселка Октябрьский на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Октябрьск кентінің бюджеті туралы» Алтай ауданының мәслихатының 2020 жылғы 5 қантардағы № 61/6- VI шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149897/rus
