act_code: '195246'
requisite: Решение маслихата района Үлкен Нарын Восточно-Казахстанской области от 27 марта 2024 года № 3/16-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 2 апреля 2024 года № 8987-16
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в районе Үлкен Нарын
  kaz: Үлкен Нарын ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-27
approved_by:
- '157022000002'
version_date:
  kaz: 2024-03-27
  rus: 2024-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/195246/kaz/27.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195246/rus/27.03.2024
