act_code: '56595'
requisite: Шығыс Қазақстан облысы Үржар аудандық мәслихатының 2010 жылғы 29 желтоқсандағы № 25-268-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Үржар аудандық әділет басқармасында 2010 жылғы 31 желтоқсанда № 5-18-108 тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Үржар аудандық мәслихатының 2011 жылғы 26 желтоқсандағы № 163-03/11 хаты)
title:
  rus: 2011-2013 жылдарға арналған аудан бюджеті туралы
  kaz: 2011-2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-29
approved_by:
- '157019000002'
version_date:
  kaz: 2010-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/56595/kaz/29.12.2010
