act_code: '56595'
requisite: Шығыс Қазақстан облысы Үржар аудандық мәслихатының 2010 жылғы 29 желтоқсандағы № 25-268-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Үржар аудандық әділет басқармасында 2010 жылғы 31 желтоқсанда № 5-18-108 тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Үржар аудандық мәслихатының 2011 жылғы 26 желтоқсандағы № 163-03/11 хаты)
title:
  rus: 2011-2013 жылдарға арналған аудан бюджеті туралы
  kaz: 2011-2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-29
approved_by:
- '157019000002'
version_date:
  kaz: 2011-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/56595/kaz/20.06.2011
caused_by:
  code: '59354'
  requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 20 июня 2011 года № 29-305-IV. Зарегистрировано управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 27 июня 2011 года за № 5-18-126. Прекращено действие по истечении срока действия (письмо Урджарского районного маслихата от 26 декабря 2011 года № 163-03/11)
  title:
    rus: О внесении изменений и дополнений в решение от 29 декабря 2010 года № 25-268-IV «О районном бюджете на 2011-2013 годы»
    kaz: '"2011-2013 жылдарға арналған аудан бюджеті туралы" 2010 жылғы 29 желтоқсандағы № 25-268-IV шешімге өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/59354/rus
