act_code: '80181'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 17 апреля 2014 года № 22/162-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 мая 2014 года № 3344. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 24 октября 2023 года № 8/96-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и определения количества представителей сел, улиц, многоквартирных жилых домов для участия в сходах местного сообщества на территории Катон-Карагайского района
  kaz: Катонқарағай ауданының аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауылдар, көшелер, көппәтерлі тұрғын үйлер тұрғындары өкілдерінің санын айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-17
approved_by:
- '157014000002'
version_date:
  kaz: 2014-10-28
  rus: 2014-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/80181/kaz/28.10.2014
  rus: https://zan.gov.kz/client/#!/doc/80181/rus/28.10.2014
caused_by:
  code: '84525'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 28 октября 2014 года № 27/202-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 ноября 2014 года № 3563. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 24 октября 2023 года № 8/96-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение Катон-Карагайского районного маслихата от 17 апреля 2014 года № 22/162-V "Об утверждении Правил проведения раздельных сходов местного сообщества и определения количества представителей сел, улиц, многоквартирных жилых домов для участия в сходах местного сообщества на территории Катон-Карагайского района"
    kaz: '"Катонқарағай ауданының аумағындағы бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауылдар, көшелер, көппәтерлі тұрғын үйлер өкілдерінің санын айқындау қағидаларын бекіту туралы" Катонқарағай аудандық мәслихатының 2014 жылғы 17 сәуірдегі № 22/162-V шешіміне өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/84525/rus
