act_code: '204411'
requisite: Решение Восточно-Казахстанского областного маслихата от 13 декабря 2024 года № 19/142-VІІІ
title:
  rus: Об областном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-13
approved_by:
- '157000000002'
version_date:
  kaz: 2025-06-12
  rus: 2025-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/204411/kaz/12.06.2025
  rus: https://zan.gov.kz/client/#!/doc/204411/rus/12.06.2025
caused_by:
  code: '211343'
  requisite: Решение Восточно-Казахстанского областного маслихата от 12 июня 2025 года № 21/176-VІІІ
  title:
    rus: О внесении изменений в решение Восточно-Казахстанского областного маслихата от 13 декабря 2024 года № 19/142-VIII «Об областном бюджете на 2025-2027 годы»
    kaz: «2025-2027 жылдарға арналған облыстық бюджет туралы» Шығыс Қазақстан облыстық мәслихатының 2024 жылғы 13 желтоқсандағы № 19/142-VIII шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211343/rus
