act_code: '179013'
requisite: Решение акима Аккайнарского сельского округа Катон-Карагайского района Восточно-Казахстанской области от 13 марта 2023 года № 3. Отменен решением акима Аккайнарского сельского округа Катон-Карагайского района Восточно-Казахстанской области от 5 апреля 2023 № 4 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении карантина в селе Аккайнар Аккайнарского сельского округа Катон-Карагайского района Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысы Катонқарағай ауданы Аққайнар ауылдық округінің Аққайнар ауылында карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-03-13
approved_by:
- '157014014002'
version_date:
  kaz: 2023-03-13
  rus: 2023-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/179013/kaz/13.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179013/rus/13.03.2023
