act_code: '139491'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 13 января 2020 года № 51-11. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 21 января 2020 года № 6667. Утратило силу решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 67-11 (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Куйганского сельского округа Тарбагатайского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Тарбағатай ауданы Құйған ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '157017000002'
version_date:
  kaz: 2020-04-07
  rus: 2020-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/139491/kaz/07.04.2020
  rus: https://zan.gov.kz/client/#!/doc/139491/rus/07.04.2020
caused_by:
  code: '142094'
  requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 7 апреля 2020 года № 53-11. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 апреля 2020 года № 6939. Утратило силу решением Тарбагатайского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 67-11 (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Тарбагатайского районного маслихата от 13 января 2020 года № 51-11 «О бюджете Куйганского сельского округа Тарбагатайского района на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Тарбағатай ауданы Құйған ауылдық округінің бюджеті туралы» Тарбағатай аудандық маслихатының 2020 жылғы 13 қаңтардағы № 51-11 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142094/rus
