act_code: '62287'
requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 21 декабря 2011 года № 38/1-IV. Зарегистрировано Управлением юстиции Бескарагайского района Департамента юстиции Восточно-Казахстанской области 29 декабря 2011 года за № 5-7-107. Утратило силу решением Бескарагайского районного маслихата Восточно-Казахстанской области от 21 декабря 2012 года № 10/8-V
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-21
approved_by:
- '157009000002'
version_date:
  kaz: 2012-07-11
  rus: 2012-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/62287/kaz/11.07.2012
  rus: https://zan.gov.kz/client/#!/doc/62287/rus/11.07.2012
caused_by:
  code: '66638'
  requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 11 июля 2012 года № 6/5-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 июля 2012 года за № 2588. Утратило силу решением Бескарагайского районного маслихата Восточно-Казахстанской области от 21 декабря 2012 года № 10/8-V
  title:
    rus: О внесении изменений в решение от 21 декабря 2011 года № 38/1-IV "О районном бюджете на 2012-2014 годы
    kaz: '"2012-2014 жылдарға арналған аудандық бюджет туралы" 2011 жылғы 21 желтоқсандағы № 38/1-IV шешімге өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/66638/rus
