act_code: '31120'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 13 декабря 2006 года № 25/13-III. Зарегистрировано управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 3 января 2007 года за № 5-9-55. Утратило силу - решением Глубоковского районного маслихата Восточно-Казахстанской области от 18 февраля 2009 года № 14/5-IV
title:
  rus: О ставках фиксированного суммарного налога
  kaz: Тіркелген жиынтық салықтың ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-13
approved_by:
- '157010000002'
version_date:
  kaz: 2006-12-13
  rus: 2006-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/31120/kaz/13.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31120/rus/13.12.2006
