act_code: '2469'
requisite: Решение Акима Восточно-Казахстанской области от 24 ноября 1998 года N 612. Зарегистрировано управлением юстиции Восточно-Казахстанской области 4 декабря 1998 года за N 116.  Утратило силу решением акима ВКО от 24 сентября 2004 года N 100
title:
  rus: О подготовке и проведении Президентской Новогодней Елки
  kaz: Президенттің жаңа жылдық шыршасын өткізу және әзірлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-11-24
approved_by:
- '157000000001'
version_date:
  kaz: 1998-11-24
  rus: 1998-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/2469/kaz/24.11.1998
  rus: https://zan.gov.kz/client/#!/doc/2469/rus/24.11.1998
