act_code: '113707'
requisite: Решение маслихата Бородулихинского района Восточно-Казахстанской области от 27 июня 2017 года № 12-7-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 июля 2017 года № 5129. Утратило силу решением Бородулихинского районного маслихата области Абай от 25 декабря 2023 года № 13-13-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-06-27
approved_by:
- '157008000002'
version_date:
  kaz: 2019-06-07
  rus: 2019-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/113707/kaz/07.06.2019
  rus: https://zan.gov.kz/client/#!/doc/113707/rus/07.06.2019
caused_by:
  code: '132324'
  requisite: Решение маслихата Бородулихинского района Восточно-Казахстанской области от 7 июня 2019 года № 38-3-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 июня 2019 года № 6004. Утратило силу решением Бородулихинского районного маслихата области Абай от 25 декабря 2023 года № 13-13-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Бородулихинского районного маслихата от 27 июня 2017 года № 12-7-VI «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Бородулиха аудандық мәслихатының 2017 жылғы 27 маусымдағы № 12-7-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132324/rus
