act_code: '40526'
requisite: Шығыс Қазақстан облысы Көкпекті ауданы Самар селолық округі әкімінің 2008 жылғы 9 маусымдағы № 1 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Көкпекті аудандық Әділет басқармасында 2008 жылғы 25 маусымда № 5-15-40 тіркелді
title:
  rus: Көкпекті ауданының Самар ауылының көшелерінің атауын өзгерту туралы
  kaz: Көкпекті ауданының Самар ауылының көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-09
approved_by:
- '157015011001'
version_date:
  kaz: 2008-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/40526/kaz/09.06.2008
