act_code: '127577'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 21 декабря 2018 года № 27/2-VI. Зарегистрировано Управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 26 декабря 2018 года № 5-9-190. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 23 декабря 2019 года № 37/2-VI (вводится в действие с 01.01.2020)
title:
  rus: О Глубоковском районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Глубокое аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '157010000002'
version_date:
  kaz: 2019-02-26
  rus: 2019-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/127577/kaz/26.02.2019
  rus: https://zan.gov.kz/client/#!/doc/127577/rus/26.02.2019
caused_by:
  code: '129557'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 26 февраля 2019 года № 30/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 7 марта 2019 года № 5756. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 23 декабря 2019 года № 37/2-VI (вводится в действие с 01.01.2020)
  title:
    rus: О внесении изменений в решение Глубоковского районного маслихата от 21 декабря 2018 года № 27/2-VI «О Глубоковском районном бюджете на 2019-2021 годы»
    kaz: Глубокое аудандық мәслихатының 2018 жылғы 21 желтоқсандағы № 27/2-VІ «2019-2021 жылдарға арналған Глубокое аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/129557/rus
