act_code: '87093'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 16 февраля 2015 года № 31/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 3 марта 2015 года № 3716. Утратило силу решением Риддерского городского маслихата Восточно-Казахстанской области от 28 мая 2024 года № 14/8-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в городе Риддере
  kaz: Риддер қаласында тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-02-16
approved_by:
- '157005000002'
version_date:
  kaz: 2015-02-16
  rus: 2015-02-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/87093/kaz/16.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87093/rus/16.02.2015
