act_code: '125114'
requisite: Решение акима Бегенского сельского округа Бескарагайского района Восточно-Казахстанской области от 2 октября 2018 года № 1. Зарегистрировано Управлением юстиции Бескарагайского района Департамента юстиции Восточно-Казахстанской области 15 октября 2018 года № 5-7-135
title:
  rus: О переименовании улиц села Бегень Бегенского сельского округа Бескарагайского района
  kaz: Бесқарағай ауданы Беген ауылдық округінің Беген ауылының көшелерінің атауларын қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-02
approved_by:
- '157009003002'
version_date:
  kaz: 2018-10-02
  rus: 2018-10-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/125114/kaz/02.10.2018
  rus: https://zan.gov.kz/client/#!/doc/125114/rus/02.10.2018
