act_code: '73033'
requisite: Решение акима Каратальского сельского округа Урджарского района Восточно-Казахстанской области от 24 мая 2013 года № 5. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 июня 2013 года № 2978. Утратило силу решением акима Урджарского района от 27 января 2014 года № 02
title:
  rus: Об установлении ветеринарного режима карантинной зоны с введением ограничительных мероприятий в селе Бекет Каратальского сельского округа
  kaz: Қаратал ауылдық округінің Бекет ауылында шектеу іс-шараларын енгізе отырып карантин аймағының ветеринариялық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-05-24
approved_by:
- '157019020002'
version_date:
  kaz: 2013-05-24
  rus: 2013-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/73033/kaz/24.05.2013
  rus: https://zan.gov.kz/client/#!/doc/73033/rus/24.05.2013
