act_code: '46932'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 24 июня 2009 года № 16/10-IV. Зарегистрировано управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 14 июля 2009 года за № 5-9-108. Утратило силу - решением Глубоковского районного маслихата от 30 июля 2010 года № 25/11-IV
title:
  rus: Об утверждении Правил оказания малообеспеченным семьям (гражданам) жилищной помощи
  kaz: Аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-06-24
approved_by:
- '157010000002'
version_date:
  kaz: 2009-10-21
  rus: 2009-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/46932/kaz/21.10.2009
  rus: https://zan.gov.kz/client/#!/doc/46932/rus/21.10.2009
caused_by:
  code: '48594'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 21 октября 2009 года № 18/10-IV. Зарегистрировано управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 12 ноября 2009 года за № 5-9-115. Утратило силу - решением Глубоковского районного маслихата от 30 июля 2010 года № 25/11-IV
  title:
    rus: О внесении изменений и дополнений в решение от 24 июня 2009 года № 16/10-IV "Об утверждении Правил оказания малообеспеченным семьям (гражданам) жилищной помощи"
    kaz: '"Аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін беру Ережелерін бекіту туралы" 2009 жылғы 24 маусымдағы № 16/10-ІV шешіміне  өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/48594/rus
