act_code: '55039'
requisite: Шығыс Қазақстан облысы Күршім ауданы Күршім ауылдық округі әкімінің 2010 жылғы 11 қазандағы № 2 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Күршім аудандық Әділет басқармасында 2010 жылғы 27 қазанда № 5-14-116 тіркелді
title:
  rus: Күршім ауылының көшелерінің атауын өзгерту туралы
  kaz: Күршім ауылының көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-11
approved_by:
- '157016001002'
version_date:
  kaz: 2010-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/55039/kaz/11.10.2010
