act_code: '128841'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 28 декабря 2018 года № 24/214-VI. Зарегистрировано Управлением юстиции Катон-Карагайского района Департамента юстиции Восточно-Казахстанской области 23 января 2019 года № 5-13-160. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 6 января 2020 года № 35/314-VI (вводится в действие с 01.01.2020)
title:
  rus: О бюджетах Алтынбельского, Катон-Карагайского, Улкен Нарынского сельских округов на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Алтынбел, Катонқарағай, Үлкен Нарын ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '157014000002'
version_date:
  kaz: 2019-07-26
  rus: 2019-07-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/128841/kaz/26.07.2019
  rus: https://zan.gov.kz/client/#!/doc/128841/rus/26.07.2019
caused_by:
  code: '133722'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 26 июля 2019 года № 31/265-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 2 августа 2019 года № 6099. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 6 января 2020 года № 35/314-VI (вводится в действие с 01.01.2020)
  title:
    rus: О внесении изменений в решение Катон-Карагайского районного маслихата от 28 декабря 2018 года № 24/214-VI «О бюджетах Алтынбельского, Катон-Карагайского, Улкен Нарынского сельских округов на 2019-2021 годы»
    kaz: Катонқарағай аудандық мәслихатының 2018 жылғы 28 желтоқсандағы № 24/214–VI «2019-2021 жылдарға арналған Алтынбел, Катонқарағай, Үлкен Нарын ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133722/rus
