act_code: '65757'
requisite: Решение акима Тассайского сельского округа Кокпектинского района Восточно-Казахстанской области от 18 апреля 2012 года № 1. Зарегистрировано управлением юстиции Кокпектинского района департамента юстиции Восточно-Казахстанской области 25 мая 2012 года за № 5-15-106
title:
  rus: О переименовании улиц в селе Тассай
  kaz: Тассай ауылындағы көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-18
approved_by:
- '157015002002'
version_date:
  kaz: 2012-04-18
  rus: 2012-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/65757/kaz/18.04.2012
  rus: https://zan.gov.kz/client/#!/doc/65757/rus/18.04.2012
