act_code: '162488'
requisite: Решение маслихата Бородулихинского района Восточно-Казахстанской области от 24 декабря 2021 года № 12-7-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26100
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Бородулихинском районе
  kaz: Бородулиха ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '157008000002'
version_date:
  kaz: 2023-06-02
  rus: 2023-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/162488/kaz/02.06.2023
  rus: https://zan.gov.kz/client/#!/doc/162488/rus/02.06.2023
caused_by:
  code: '182655'
  requisite: Решение Бородулихинского районного маслихата области Абай от 2 июня 2023 года № 3-10-VIII. Зарегистрировано Департаментом юстиции области Абай 8 июня 2023 года № 92-18
  title:
    rus: О внесении изменений в решение Бородулихинского районного маслихата от 24 декабря 2021 года № 12-7-VII «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Бородулихинском районе»
    kaz: Бородулиха аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 12-7-VII «Бородулиха ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182655/rus
