act_code: '159386'
requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 29 сентября 2021 года № 9/65-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 11 октября 2021 года № 24698
title:
  rus: Об утверждении минимального размера расходов на управление объектов кондоминиума и содержание общего имущества объектов кондоминиума города Курчатов на 2021 год
  kaz: 2021 жылға Курчатов қаласының кондоминиум объектілерін басқаруға және кондоминиум объектілерінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-09-29
approved_by:
- '157004000002'
version_date:
  kaz: 2021-09-29
  rus: 2021-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/159386/kaz/29.09.2021
  rus: https://zan.gov.kz/client/#!/doc/159386/rus/29.09.2021
