act_code: '62819'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 22 декабря 2011 года № 01-02/37-8. Зарегистрировано управлением юстиции Аягозского района Департамента юстиции Восточно-Казахстанской области 20 января 2012 года за № 5-6-152. Утратило силу - решением Аягозского районного маслихата Восточно-Казахстанской области от 15 марта 2018 года № 20/149-VI
title:
  rus: О ставках фиксированного налога
  kaz: Тіркелген салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-22
approved_by:
- '157007000002'
version_date:
  kaz: 2011-12-22
  rus: 2011-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/62819/kaz/22.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62819/rus/22.12.2011
