act_code: '138123'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2019 года № 42/291-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 9 января 2020 года № 6482. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/522-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Аягозского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Аягөз ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '157007000002'
version_date:
  kaz: 2020-09-04
  rus: 2020-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/138123/kaz/04.09.2020
  rus: https://zan.gov.kz/client/#!/doc/138123/rus/04.09.2020
caused_by:
  code: '146272'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 4 сентября 2020 года № 52/432-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 сентября 2020 года № 7523. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/522-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 25 декабря 2019 года № 42/291-VI «О бюджете Аягозского района на 2020-2022 годы»
    kaz: Аягөз аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 42/291-VІ «2020-2022 жылдарға арналған Аягөз ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146272/rus
