act_code: '177851'
requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 27 декабря 2022 года № 30/6-VII
title:
  rus: О бюджете Курчумского сельского округа на 2023-2025 годы
  kaz: Күршім ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '157016000002'
version_date:
  kaz: 2023-12-22
  rus: 2023-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/177851/kaz/22.12.2023
  rus: https://zan.gov.kz/client/#!/doc/177851/rus/22.12.2023
caused_by:
  code: '190804'
  requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 22 декабря 2023 года № 13/5-VIII
  title:
    rus: О внесении изменений в решение Курчумского районного маслихата от 27 декабря 2022 года № 30/6-VII «О бюджете Курчумского сельского округа  на 2023-2025 годы»
    kaz: «Күршім ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы» Күршім аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 30/6-VII шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190804/rus
