act_code: '163979'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 30 декабря 2021 года № 126
title:
  rus: О бюджете сельских округов и поселков Уланского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Ұлан ауданының ауылдық округтер мен кенттер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '157018000002'
version_date:
  kaz: 2022-11-25
  rus: 2022-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/163979/kaz/25.11.2022
  rus: https://zan.gov.kz/client/#!/doc/163979/rus/25.11.2022
caused_by:
  code: '174539'
  requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 25 ноября 2022 года № 199
  title:
    rus: О внесении изменений в решение Уланского районного маслихата от 30 декабря 2021 года № 126 «О бюджете сельских округов и поселков Уланского района на 2022-2024 годы»
    kaz: Ұлан аудандық мәслихатының «2022-2024 жылдарға арналған Ұлан ауданының ауылдық округтер мен кенттер бюджеті туралы» 2021 жылдың 30 желтоқсандағы № 126 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174539/rus
