act_code: '208905'
requisite: Решение акима Жанааульского сельского округа Тарбагатайского района Восточно-Казахстанской области от 3 апреля 2025 года № 3. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 4 апреля 2025 года № 9165-16
title:
  rus: О снятии карантина и признании утратившим силу решения акима Жанааульского сельского округа Тарбагатайского района Восточно-Казахстанской области от 25 мая 2015 года № 7 "Об установлении карантина в селе Ахметбулак Жанааульского сельского округа Тарбагатайского района"
  kaz: Шығыс Қазақстан облысы Тарбағатай ауданы Жаңаауыл ауылдық округі әкімінің 2015 жылғы 25 мамырдағы "Тарбағатай ауданы Жаңаауыл ауылдық округінің Ахметбұлақ ауылында карантин белгілеу туралы" № 7 шешімінің күші жойылды деп және карантинді алып тастау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-04-03
approved_by:
- '157017014002'
version_date:
  kaz: 2025-04-03
  rus: 2025-04-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/208905/kaz/03.04.2025
  rus: https://zan.gov.kz/client/#!/doc/208905/rus/03.04.2025
