act_code: '152525'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 53/530-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 18 января 2021 года № 8352. Утратило силу решением Жарминского районного маслихата области Абай от 30 ноября 2023 года № 9/149-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерiн белгiлеудiң және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-12-30
approved_by:
- '157011000002'
version_date:
  kaz: 2021-03-29
  rus: 2021-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/152525/kaz/29.03.2021
  rus: https://zan.gov.kz/client/#!/doc/152525/rus/29.03.2021
caused_by:
  code: '154654'
  requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 29 марта 2021 года № 4/26-VII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 8 апреля 2021 года № 8571. Утратило силу решением Жарминского районного маслихата области Абай от 30 ноября 2023 года № 9/149-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение Жарминского районного маслихата от 30 декабря 2020 года № 53/530-VI «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Жарма аудандық мәслихатының 2020 жылғы 30 желтоқсандағы № 53/530-VI «Әлеуметтік көмек көрсетудің, оның мөлшерлерiн белгiлеудiң және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154654/rus
