act_code: '97870'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 23 декабря 2015 года № 40/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 12 января 2016 года № 4333. Утратило силу - решением Риддерского городского маслихата Восточно-Казахстанской области от 22 декабря 2016 года № 7/2-VI
title:
  rus: О бюджете города Риддера на 2016 - 2018 годы
  kaz: 2016-2018 жылдарға арналған Риддер қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '157005000002'
version_date:
  kaz: 2016-04-12
  rus: 2016-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/97870/kaz/12.04.2016
  rus: https://zan.gov.kz/client/#!/doc/97870/rus/12.04.2016
caused_by:
  code: '101752'
  requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 12 апреля 2016 года № 2/4-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 апреля 2016 года № 4501. Утратило силу - решением Риддерского городского маслихата Восточно-Казахстанской области от 22 декабря 2016 года № 7/2-VI
  title:
    rus: О внесении изменений и дополнений в решение Риддерского городского маслихата от 23 декабря 2015 года № 40/2-V «О бюджете города Риддера на 2016-2018 годы»
    kaz: «2016-2018 жылдарға арналған Риддер қаласының бюджеті туралы» Риддер қалалық мәслихатының 2015 жылғы 23 желтоқсандағы № 40/2-V шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101752/rus
