act_code: '122851'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 19 июня 2018 года № 28-288/VI. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 25 июня 2018 года № 5-18-157. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 24 сентября 2018 года № 32-340/VI
title:
  rus: Об утверждении Регламента собрания местного сообщества на территории населенных пунктов Урджарского района
  kaz: Үржар ауданының елді мекендері аумағындағы жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-06-19
approved_by:
- '157019000002'
version_date:
  kaz: 2018-06-19
  rus: 2018-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/122851/kaz/19.06.2018
  rus: https://zan.gov.kz/client/#!/doc/122851/rus/19.06.2018
