act_code: '163356'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 28 декабря 2021 года № 14/8-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 января 2022 года № 26392
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Шемонаихинском районе
  kaz: Шемонаиха ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '157020000002'
version_date:
  kaz: 2022-09-27
  rus: 2022-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/163356/kaz/27.09.2022
  rus: https://zan.gov.kz/client/#!/doc/163356/rus/27.09.2022
caused_by:
  code: '172604'
  requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 27 сентября 2022 года № 23/10-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 4 октября 2022 года № 29999
  title:
    rus: О внесении изменений в решение Шемонаихинского районного маслихата от 28 декабря 2021 года № 14/8-VII «Об определении порядка и размера возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Шемонаихинском районе»
    kaz: Шемонаиха аудандық мәслихатының 2021 жылғы 28 желтоқсандағы № 14/8-VII «Шемонаиха ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172604/rus
