act_code: '143240'
requisite: Решение акима Глуховского сельского округа Бескарагайского района Восточно-Казахстанской области от 22 мая 2020 года № 5. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 мая 2020 года № 7117. Утратило силу решением акима Глуховского сельского округа Бескарагайского района Восточно-Казахстанской области от 23 декабря 2020 года № 9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий по улицам Джамбула, Свердлова, Пионерская, Юбилейная села Глуховка Глуховского сельского округа Бескарагайского района
  kaz: Бесқарағай ауданы Глуховка ауылдық округінің Глуховка ауылында Жамбыл, Свердлов, Пионерский, Юбилейный көшелеріне шектеу іс- шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-05-22
approved_by:
- '157009004002'
version_date:
  kaz: 2020-05-22
  rus: 2020-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/143240/kaz/22.05.2020
  rus: https://zan.gov.kz/client/#!/doc/143240/rus/22.05.2020
