act_code: '85988'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 24 декабря 2014 года N 30/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 13 января 2015 года № 3623. Утратило силу решением Риддерского городского маслихата Восточно-Казахстанской области от 23.12.2015 № 40/2-V
title:
  rus: "О бюджете города Риддера  на 2015-2017 годы\t "
  kaz: '2015-2017 жылдарға арналған  Риддер қаласының бюджеті туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '157005000002'
version_date:
  kaz: 2015-07-14
  rus: 2015-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/85988/kaz/14.07.2015
  rus: https://zan.gov.kz/client/#!/doc/85988/rus/14.07.2015
caused_by:
  code: '92805'
  requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 14 июля 2015 года N 36/3-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 июля 2015 года № 4060. Утратило силу решением Риддерского городского маслихата Восточно-Казахстанской области от 23.12.2015 № 40/2-V
  title:
    rus: О внесении изменений и дополнения в решение Риддерского городского маслихата от 24 декабря 2014 года № 30/2-V «О бюджете города Риддера на 2015-2017 годы»
    kaz: «2015-2017 жылдарға арналған Риддер қаласының бюджеті туралы» Риддер қалалық мәслихатының 2014 жылғы 24 желтоқсандағы № 30/2-V шешіміне өзгерістер мен толыктыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/92805/rus
