act_code: '85988'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 24 декабря 2014 года N 30/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 13 января 2015 года № 3623. Утратило силу решением Риддерского городского маслихата Восточно-Казахстанской области от 23.12.2015 № 40/2-V
title:
  rus: "О бюджете города Риддера  на 2015-2017 годы\t "
  kaz: '2015-2017 жылдарға арналған  Риддер қаласының бюджеті туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '157005000002'
version_date:
  kaz: 2015-04-08
  rus: 2015-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/85988/kaz/08.04.2015
  rus: https://zan.gov.kz/client/#!/doc/85988/rus/08.04.2015
caused_by:
  code: '88763'
  requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 08 апреля 2015 года N 33/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 апреля 2015 года № 3875. Утратило силу решением Риддерского городского маслихата Восточно-Казахстанской области от 23.12.2015 № 40/2-V
  title:
    rus: 'О внесении изменений в решение Риддерского  городского маслихата от 24 декабря 2014 года №30/2-V «О бюджете города Риддера на 2015-2017 годы» '
    kaz: '2015-2017 жылдарға арналған Риддер қаласының бюджеті туралы» 2014 жылғы 24 желтоқсандағы № 30/2 -V Риддер қалалық мәслихатының шешіміне өзгерістер енгізу туралы '
  link: https://zan.gov.kz/client/#!/doc/88763/rus
