act_code: '123484'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 25 июня 2018 года № 23/8-VI. Зарегистрировано Управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 12 июля 2018 года № 5-9-175. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 4 октября 2019 года № 35/3-VI
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылық мақсатындағы жерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-25
approved_by:
- '157010000002'
version_date:
  kaz: 2018-06-25
  rus: 2018-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/123484/kaz/25.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123484/rus/25.06.2018
