act_code: '28450'
requisite: Решение XХV сессии Шемонаихинского районного маслихата III созыва Восточно-Казахстанской области от 12 мая 2006 года № 25/6-III. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 30 мая 2006 года № 5-19-33. Утратило силу - решением Шемонаихинского районного маслихата от 26 декабря 2008 года № 14/5-IV
title:
  rus: Об утверждении стоимости разовых талонов для лиц, занимающихся реализацией товаров, выполняющих работы и оказывающих услуги на рынках района
  kaz: Аудан базарында тауар сатумен айналысатын, жұмыс істейтін және қызмет көрсететін жеке тұлғаларға арналған біржолғы талондардың құнын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-05-12
approved_by:
- '157020000002'
version_date:
  kaz: 2006-05-12
  rus: 2006-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/28450/kaz/12.05.2006
  rus: https://zan.gov.kz/client/#!/doc/28450/rus/12.05.2006
