act_code: '128329'
requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 26 декабря 2018 года № 32/3-VI. Зарегистрировано Управлением юстиции Курчумского района Департамента юстиции Восточно-Казахстанской области 11 января 2019 года № 5-14-190. Утратило силу решением Курчумского районного маслихата Восточно-Казахстанской области от 24 декабря 2019 года № 45/3-VI (вводится в действие с 01.01.2020)
title:
  rus: О бюджете Курчумского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Күршім ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '157016000002'
version_date:
  kaz: 2019-08-01
  rus: 2019-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/128329/kaz/01.08.2019
  rus: https://zan.gov.kz/client/#!/doc/128329/rus/01.08.2019
caused_by:
  code: '133961'
  requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 1 августа 2019 года № 40/5-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 6 августа 2019 года № 6110. Утратило силу решением Курчумского районного маслихата Восточно-Казахстанской области от 24 декабря 2019 года № 45/3-VI (вводится в действие с 01.01.2020)
  title:
    rus: О внесении изменений в решение Курчумского районного маслихата от 26 декабря 2018 года № 32/3-VI «О бюджете Курчумского района на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған Күршім ауданының бюджеті туралы» Күршім аудандық мәслихатының 2018 жылғы 26 желтоқсандағы № 32/3-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133961/rus
