act_code: '96124'
requisite: Решение акима Ленинского сельского округа Бородулихинского района Восточно-Казахстанской области от 12 ноября 2015 года № 1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 4 декабря 2015 года № 4254
title:
  rus: О переименовании улицы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-12
approved_by:
- '157008010001'
version_date:
  kaz: 2015-11-12
  rus: 2015-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/96124/kaz/12.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96124/rus/12.11.2015
