act_code: '138789'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 10 января 2020 года № 43/309-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 января 2020 года № 6595. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/538-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Емельтауского сельского округа Аягозского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Аягөз ауданының Емельтау ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '157007000002'
version_date:
  kaz: 2020-06-02
  rus: 2020-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/138789/kaz/02.06.2020
  rus: https://zan.gov.kz/client/#!/doc/138789/rus/02.06.2020
caused_by:
  code: '143762'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 2 июня 2020 года № 48/388-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 июня 2020 года № 7172. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/538-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 10 января 2020 года № 43/309-VІ «О бюджете Емельтауского сельского округа Аягозского района на 2020-2022 годы»
    kaz: Аягөз аудандық мәслихатының 2020 жылғы 10 қаңтардағы № 43/309-VІ «2020-2022 жылдарға арналған Аягөз ауданының Емельтау ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143762/rus
