act_code: '39760'
requisite: Шығыс Қазақстан облысы Зайсан аудандық мәслихатының 2008 жылғы 22 сәуірдегі № 6-6/1 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Зайсан аудандық Әділет басқармасында 2008 жылғы 20 мамырда № 5-11-78 тіркелді. Күші жойылды - ШҚО Зайсан аудандық мәслихатының 2012 жылғы 25 шілдедегі № 6-2/1 шешімімен
title:
  rus: Қала мен елді мекендердің аумақтарын көріктендіру, инфрақұрылым обьектілерін сақтау, жасыл желекті күтіп ұстау және қорғау Ережесін бекіту туралы
  kaz: Қала мен елді мекендердің аумақтарын көріктендіру, инфрақұрылым обьектілерін сақтау, жасыл желекті күтіп ұстау және қорғау Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-22
approved_by:
- '157012000002'
version_date:
  kaz: 2008-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/39760/kaz/22.04.2008
