act_code: '56875'
requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 30 декабря 2010 года № 33/2-IV. Зарегистрировано управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 31 декабря 2010 года за № 5-12-114. Утратило силу - письмо маслихата Зыряновского района от 20 апреля 2012 года № 07-07-134
title:
  rus: О бюджете Зыряновского района на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған Зырян ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-30
approved_by:
- '157013000002'
version_date:
  kaz: 2011-11-15
  rus: 2011-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/56875/kaz/15.11.2011
  rus: https://zan.gov.kz/client/#!/doc/56875/rus/15.11.2011
caused_by:
  code: '62192'
  requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 15 ноября 2011 года № 40/2-IV. Зарегистрировано управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 25 ноября 2011 года № 5-12-126. Утратило силу - письмо маслихата Зыряновского района от 20 апреля 2012 года № 07-07-134
  title:
    rus: О внесении изменений и дополнений в решение от 30 декабря 2010 года № 33/2-IV "О бюджете Зыряновского района на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған Зырян ауданының бюджеті туралы" 2010 жылғы 30 желтоқсандағы № 33/2-IV шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/62192/rus
