act_code: '49725'
requisite: Шығыс Қазақстан облысы Ұлан аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 162 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Ұлан аудандық Әділет басқармасында 2010 жылғы 11 қаңтарда № 5-17-122 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Ұлан аудандық мәслихатының 2011 жылғы 13 қаңтардағы № 7 хаты
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '157018000002'
version_date:
  kaz: 2010-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/49725/kaz/28.05.2010
caused_by:
  code: '53279'
  requisite: Шығыс Қазақстан облысы Ұлан аудандық мәслихатының 2010 жылғы 28 мамырдағы № 188 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Ұлан аудандық әділет басқармасында 2010 жылғы 23 маусымда № 5-17-131 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Ұлан аудандық мәслихатының 2011 жылғы 13 қаңтардағы № 7 хаты
  title:
    rus: 2009 жылғы 25 желтоқсандағы № 162 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешімге өзгерістер енгізу туралы
    kaz: 2009 жылғы 25 желтоқсандағы № 162 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешімге өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/53279/rus
