act_code: '49725'
requisite: Шығыс Қазақстан облысы Ұлан аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 162 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Ұлан аудандық Әділет басқармасында 2010 жылғы 11 қаңтарда № 5-17-122 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Ұлан аудандық мәслихатының 2011 жылғы 13 қаңтардағы № 7 хаты
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '157018000002'
version_date:
  kaz: 2010-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/49725/kaz/23.01.2010
caused_by:
  code: '50698'
  requisite: Шығыс Қазақстан облысы Ұлан аудандық мәслихатының 2010 жылғы 23 қаңтардағы № 164 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Ұлан аудандық Әділет басқармасында 2010 жылғы 3 ақпанда № 5-17-124 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Ұлан аудандық мәслихатының 2011 жылғы 13 қаңтардағы № 7 хаты
  title:
    rus: 2009 жылғы 25 желтоқсандағы № 162 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешімге өзгерістер мен толықтырулар енгізу туралы
    kaz: 2009 жылғы 25 желтоқсандағы № 162 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешімге өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/50698/rus
