act_code: '160151'
requisite: Решение маслихата Абайского района Восточно-Казахстанской области от 3 ноября 2021 года № 14/3-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 ноября 2021 года № 25141
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей  с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Абайском районе
  kaz: Абай ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсалған шығындарды өтеу мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-11-03
approved_by:
- '157006000002'
version_date:
  kaz: 2022-10-05
  rus: 2022-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/160151/kaz/05.10.2022
  rus: https://zan.gov.kz/client/#!/doc/160151/rus/05.10.2022
caused_by:
  code: '172929'
  requisite: Решение маслихата Абайского района области Абай от 5 октября 2022 года № 28/7-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 октября 2022 года № 30181
  title:
    rus: О внесении изменений в решение Абайского районного маслихата от 3 ноября 2021 года № 14/3-VІІ «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Абайском районе»
    kaz: Абай аудандық мәслихатының 2021 жылғы 3 қарашадағы № 14/3-VІІ «Абай ауданында мүгедектер қатарындағы кемтар балаларды  жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшері мен тәртібін айқындау туралы»  шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172929/rus
