act_code: '58843'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 27 апреля 2011 года № 32/8-IV. Зарегистрировано управлением юстиции города Риддера Департамента юстиции Восточно-Казахстанской области 16 мая 2011 года за № 5-4-148. Утратило силу - решением Риддерского городского маслихата от 21 декабря 2012 года № 11/9-V
title:
  rus: Об утверждении инструкции по оказанию социальной помощи отдельным категориям нуждающихся граждан по решению местных представительных органов
  kaz: Жергілікті өкілді органдардың шешімі бойынша мұқтаж азаматтардың жеке санаттарына әлеуметтік көмек көрсету жөнінде нұсқаулықты бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-27
approved_by:
- '157005000002'
version_date:
  kaz: 2011-04-27
  rus: 2011-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/58843/kaz/27.04.2011
  rus: https://zan.gov.kz/client/#!/doc/58843/rus/27.04.2011
