act_code: '56446'
requisite: Шығыс Қазақстан облысы Күршім аудандық мәслихатының 2010 жылғы 29 желтоқсандағы № 26-5 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Күршім аудандық әділет басқармасында 2010 жылғы 31 желтоқсанда № 5-14-120 тіркелді. Шешімінің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Күршім аудандық мәслихатының 2012 жылғы 3 қаңтардағы № 20 хаты)
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-29
approved_by:
- '157016000002'
version_date:
  kaz: 2011-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/56446/kaz/17.03.2011
caused_by:
  code: '57896'
  requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 17 марта 2011 года № 27-6. Зарегистрировано управлением юстиции Курчумского района Департамента юстиции Восточно-Казахстанской области 29 марта 2011 года за № 5-14-124. Прекращено действие по истечении срока действия (письмо Курчумского районного маслихата от 3 января 2012 года № 20)
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 29 декабря 2010 года № 26-5 "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" 2010 жылғы 29 желтоқсандағы № 26-5 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/57896/rus
