act_code: '144123'
requisite: Решение акима Каратальского сельского округа Зайсанского района Восточно-Казахстанской области от 19 июня 2020 года № 6. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 23 июня 2020 года № 7210. Утратило силу решением акима Каратальского сельского округа Зайсанского района Восточно-Казахстанской области от 20 октября 2020 года № 11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий в крестьянском хозяйстве «Куат» находящегося в зимовке Жиде Каратальского сельского округа
  kaz: Қаратал ауылдық округіне қарасты Жиде қыстағындағы «Қуат» шаруа қожалығына шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-19
approved_by:
- '157012008002'
version_date:
  kaz: 2020-06-19
  rus: 2020-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/144123/kaz/19.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144123/rus/19.06.2020
