act_code: '62102'
requisite: Решение Восточно-Казахстанского областного маслихата от 8 декабря 2011 года № 34/397-IV. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 21 декабря 2011 года за № 2560. Прекращено действие по истечении срока, на который решение было принято (письмо Восточно-Казахстанского областного маслихата от 27 декабря 2012 года № 660/01-06)
title:
  rus: Об областном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-08
approved_by:
- '157000000002'
version_date:
  kaz: 2011-12-08
  rus: 2011-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/62102/kaz/08.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62102/rus/08.12.2011
