act_code: '52507'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 16 апреля 2010 года N 28/5-IV. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 17 мая 2010 года за N 5-19-119. Утратило силу - решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 30.01.2015 года N 25/2-V
title:
  rus: Об утверждении Правил о размере и порядке оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсетудің мөлшері мен тәртібі туралы қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-04-16
approved_by:
- '157020000002'
version_date:
  rus: 2012-12-21
source:
  rus: https://zan.gov.kz/client/#!/doc/52507/rus/21.12.2012
caused_by:
  code: '70403'
  requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 21 декабря 2012 года № 8/6-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 22 января 2013 года № 2831. Утратило силу - решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 30.01.2015 № 25/2-V
  title:
    rus: О внесении изменений в решение от 16 апреля 2010 года 28/5-IV "Об утверждении Правил о размере и порядке оказания жилищной помощи"
    kaz: '"Тұрғын үй көмегін көрсетудің мөлшері мен тәртібі туралы ережесін бекіту туралы" 2010 жылғы 16 сәуірдегі № 28/5–IV шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/70403/rus
