act_code: '78162'
requisite: Решение акима Кокпектинского района Восточно-Казахстанской области от 17 февраля 2014 года № 1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 марта 2014 года № 3207. Утратило силу - решением акима Кокпектинского района от 23 апреля 2014 года № 4
title:
  rus: Об образовании избирательных участков по Кокпектинскому району
  kaz: Көкпекті ауданының аумағында сайлау участкелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-17
approved_by:
- '157015000001'
version_date:
  kaz: 2014-02-17
  rus: 2014-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/78162/kaz/17.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78162/rus/17.02.2014
