act_code: '121371'
requisite: Решение Восточно-Казахстанского областного маслихата от 12 апреля 2018 года № 19/228-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 апреля 2018 года № 5627. Утратило силу решением Восточно-Казахстанского областного маслихата от 27 августа 2026 года № 30/268-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О ставках платы за пользование лесными и растительными ресурсами на участках государственного лесного фонда Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысының мемлекеттік орман қоры учаскелерінде орман және өсімдіктер ресурстарын пайдаланғаны үшін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-04-12
approved_by:
- '157000000002'
version_date:
  kaz: 2018-04-12
  rus: 2018-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/121371/kaz/12.04.2018
  rus: https://zan.gov.kz/client/#!/doc/121371/rus/12.04.2018
