act_code: '129717'
requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 5 марта 2019 года № 29/218-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 18 марта 2019 года № 5785. Утратило силу решением Курчатовского городского маслихата области Абай от 28 сентября 2023 года № 10/57-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О приостановлении действия решения Курчатовского городского маслихата от 30 ноября 2017 года № 17/125-VI «Об утверждении тарифов на сбор, вывоз и захоронение твердых бытовых отходов по городу Курчатов»
  kaz: «Курчатов қаласы бойынша тұрмыстық қатты қалдықтарды жинауға, әкетуге және көмуге арналған тарифтерді бекіту туралы» Курчатов қалалық мәслихатының 2017 жылғы 30 қарашадағы № 17/125-VI шешімінің қолданылуын тоқтата тұру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-05
approved_by:
- '157004000002'
version_date:
  kaz: 2019-03-05
  rus: 2019-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/129717/kaz/05.03.2019
  rus: https://zan.gov.kz/client/#!/doc/129717/rus/05.03.2019
