act_code: '54021'
requisite: Шығыс Қазақстан облысы Жарма аудандық мәслихатының 2010 жылғы 27 шілдедегі № 23/184-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Жарма аудандық әділет басқармасында 2010 жылғы 16 тамызда № 5-10-103 тіркелді. Күші жойылды - Жарма аудандық мәслихатының 2012 жылғы 5 маусымдағы № 3/39-V шешімімен
title:
  rus: Жарма ауданының елді мекендерінде мысықтар мен иттерді күтіп ұстау Ережесін бекіту туралы
  kaz: Жарма ауданының елді мекендерінде мысықтар мен иттерді күтіп ұстау Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-07-27
approved_by:
- '157011000002'
version_date:
  kaz: 2010-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/54021/kaz/27.07.2010
