act_code: '80291'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 19 апреля 2014 года № 24/169-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 мая 2014 года № 3351. Утратило силу - решением Аягозского районного маслихата Восточно-Казахстанской области от 9 июня 2016 года № 3/25-VI
title:
  rus: Об утверждении регламента Аягозского районного маслихата
  kaz: Аягөз аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-04-19
approved_by:
- '157007000002'
version_date:
  kaz: 2014-04-19
  rus: 2014-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/80291/kaz/19.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80291/rus/19.04.2014
