act_code: '205076'
requisite: Решение маслихата района Үлкен Нарын Восточно-Казахстанской области от 24 декабря 2024 года № 9/87-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 декабря 2024 года № 9121-16
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, и норм их предельной заполнямости, требований к их материально-техническому и организационному обеспечению, порядка их использования, границ прилегающих территорий, в которых запрещено проведение пикетирования по району Үлкен Нарын
  kaz: Үлкен Нарын ауданы бойынша бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды және олардың шекті толу нормаларын, оларды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пайдалану тәртібін, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '157022000002'
version_date:
  kaz: 2024-12-24
  rus: 2024-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/205076/kaz/24.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205076/rus/24.12.2024
