act_code: '166258'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 30 марта 2022 года № 16/170-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 апреля 2022 года № 27446
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по Катон-Карагайскому району
  kaz: Катонқарағай ауданы бойынша шетелдіктер үшін жарнаны 2022 жылға бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-30
approved_by:
- '157014000002'
version_date:
  kaz: 2022-03-30
  rus: 2022-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/166258/kaz/30.03.2022
  rus: https://zan.gov.kz/client/#!/doc/166258/rus/30.03.2022
