act_code: '107697'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 19 октября 2016 года № 6/51-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 31 октября 2016 года № 4718. Утратило силу - решением Аягозского районного маслихата Восточно-Казахстанской области от 27 марта 2018 года № 21/153-VI
title:
  rus: О повышении базовых ставок земельного налога и единого земельного налога на не используемые земли сельскохозяйственного назначения по Аягозскому району
  kaz: Аягөз ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-19
approved_by:
- '157007000002'
version_date:
  kaz: 2016-10-19
  rus: 2016-10-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/107697/kaz/19.10.2016
  rus: https://zan.gov.kz/client/#!/doc/107697/rus/19.10.2016
