act_code: '146537'
requisite: Решение акима поселка Ауэзов Жарминского района Восточно-Казахстанской области от 4 сентября 2020 года № 8. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 22 сентября 2020 года № 7557
title:
  rus: О переименование улицы поселка Ауэзов Жарминского района
  kaz: Жарма ауданы Әуезов кентінің көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-04
approved_by:
- '157011003001'
version_date:
  kaz: 2020-09-04
  rus: 2020-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/146537/kaz/04.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146537/rus/04.09.2020
