act_code: '59934'
requisite: Решение акима Благодарненского сельского округа Урджарского района Восточно-Казахстанской области от 18 июля 2011 года № 12. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 8 августа 2011 года за № 5-18-127. Утратило силу решением акима Благодарненского сельского округа Урджарского района от 3 ноября 2011 года № 16
title:
  rus: Об установлении ограничения в связи со вспышкой бруцеллеза мелкого рогатого скота на территории Благодарненского сельского округа
  kaz: Благодарное ауылдық округі аймағында мүйізді ұсақ малдарынан бруцеллез індетінің шығуына байланысты шектеу қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-07-18
approved_by:
- '157019008002'
version_date:
  kaz: 2011-07-18
  rus: 2011-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/59934/kaz/18.07.2011
  rus: https://zan.gov.kz/client/#!/doc/59934/rus/18.07.2011
