act_code: '134889'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 18 сентября 2019 года № 34/8-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 25 сентября 2019 года № 6172. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 5 июня 2024 года № 12/5-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-09-18
approved_by:
- '157010000002'
version_date:
  kaz: 2020-04-03
  rus: 2020-04-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/134889/kaz/03.04.2020
  rus: https://zan.gov.kz/client/#!/doc/134889/rus/03.04.2020
caused_by:
  code: '141524'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 3 апреля 2020 года № 39/9-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 апреля 2020 года № 6886. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 5 июня 2024 года № 12/5-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Глубоковского районного маслихата от 18 сентября 2019 года № 34/8-VI «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Глубокое аудандық мәслихатының 2019 жылғы 18 қыркүйектегі № 34/8-VІ «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141524/rus
