act_code: '138779'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 10 января 2020 года № 43/316-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 января 2020 года № 6586. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/545-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Мамырсуского сельского округа Аягозского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Аягөз ауданы Мамырсу ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '157007000002'
version_date:
  kaz: 2020-09-16
  rus: 2020-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/138779/kaz/16.09.2020
  rus: https://zan.gov.kz/client/#!/doc/138779/rus/16.09.2020
caused_by:
  code: '146731'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 16 сентября 2020 года № 52/461-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 25 сентября 2020 года № 7576. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/545-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 10 января 2020 года № 43/316-VI «О бюджете Мамырсуского сельского округа Аягозского района на 2020-2022 годы»
    kaz: Аягөз аудандық мәслихатының 2020 жылғы 10 қаңтардағы № 43/316-VІ «2020-2022 жылдарға арналған Аягөз ауданының Мамырсу ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146731/rus
