act_code: '127943'
requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 24 декабря 2018 года № 34/2-VI. Зарегистрировано Управлением юстиции Бескарагайского района Департамента юстиции Восточно-Казахстанской области 29 декабря 2018 года № 5-7-152. Утратило силу решением Бескарагайского районного маслихата Восточно-Казахстанской области от 6 января 2020 года № 48/3-VI (вводится в действие с 01.01.2020)
title:
  rus: О бюджете Бескарагайского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Бесқарағай ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '157009000002'
version_date:
  kaz: 2019-07-25
  rus: 2019-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/127943/kaz/25.07.2019
  rus: https://zan.gov.kz/client/#!/doc/127943/rus/25.07.2019
caused_by:
  code: '133767'
  requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 25 июля 2019 года № 40/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 1 августа 2019 года № 6097. Утратило силу решением Бескарагайского районного маслихата Восточно-Казахстанской области от 6 января 2020 года № 48/3-VI (вводится в действие с 01.01.2020)
  title:
    rus: О внесении изменений в решение Бескарагайского районного маслихата от 24 декабря 2018 года № 34/2-VІ «О бюджете Бескарагайского района на 2019-2021 годы»
    kaz: Бесқарағай аудандық мәслихатының 2018 жылғы 24 желтоқсандағы № 34/2-VІ «2019-2021 жылдарға арналған Бесқарағай ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133767/rus
