act_code: '146034'
requisite: Решение акима Кызылкесикского сельского округа Тарбагатайского района Восточно-Казахстанской области от 4 сентября 2020 года № 18. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 7 сентября 2020 года № 7506
title:
  rus: О присвоении наименования безымянной улице в селе Кызылкесик Кызылкесикского сельского округа
  kaz: Қызылкесік ауылдық округінің Қызылкесік ауылындағы атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-04
approved_by:
- '157017008002'
version_date:
  kaz: 2020-09-04
  rus: 2020-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/146034/kaz/04.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146034/rus/04.09.2020
