act_code: '2554'
requisite: Решение Акима Восточно-Казахстанской области от 11 мая 1998 года N 515. Зарегистрировано управлением юстиции Восточно-Казахстанской области 19 мая 1998 года за N 37. Утратило силу решением акима ВКО от 24 сентября 2004 года N 100
title:
  rus: Об улучшении социально-бытовых условий семей репатриантов
  kaz: Оралмандар отбасыларының әлеуметтік-тұрмыстық жағдайларын жақсарту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-05-10
approved_by:
- '157000000001'
version_date:
  kaz: 1998-05-10
  rus: 1998-05-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/2554/kaz/10.05.1998
  rus: https://zan.gov.kz/client/#!/doc/2554/rus/10.05.1998
