act_code: '151271'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 23 декабря 2020 года № 66-2. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 декабря 2020 года № 8141
title:
  rus: О бюджете Тарбагатайского района на 2021–2023 годы
  kaz: 2021-2023 жылдарға арналған Тарбағатай ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '157017000002'
version_date:
  kaz: 2021-03-17
  rus: 2021-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/151271/kaz/17.03.2021
  rus: https://zan.gov.kz/client/#!/doc/151271/rus/17.03.2021
caused_by:
  code: '153739'
  requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 17 марта 2021 года № 3-2. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 марта 2021 года № 8462
  title:
    rus: О внесении изменений и дополнения в решение Тарбагатайского районного маслихата от 23 декабря 2020 года № 66-2 «О бюджете Тарбагатайского района на 2021-2023 годы»
    kaz: Тарбағатай аудандық мәслихатының 2020 жылғы 23 желтоқсандағы № 66-2 «2021-2023 жылдарға арналған Тарбағатай ауданының бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153739/rus
