act_code: '56321'
requisite: Решение Восточно-Казахстанского областного маслихата от 24 декабря 2010 года № 26/310-IV. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 декабря 2010 года за № 2541. Прекращено действие по истечении срока, на который решение было принято (письмо аппарата Восточно-Казахстанского областного маслихата от 22 декабря 2011 года № 521/01-06)
title:
  rus: Об областном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '157000000002'
version_date:
  kaz: 2011-09-27
  rus: 2011-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/56321/kaz/27.09.2011
  rus: https://zan.gov.kz/client/#!/doc/56321/rus/27.09.2011
caused_by:
  code: '60627'
  requisite: Решение Восточно-Казахстанского областного маслихата от 27 сентября 2011 года № 32/379-IV. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 сентября 2011 года за № 2555. Прекращено действие по истечении срока, на который решение было принято (письмо аппарата Восточно-Казахстанского областного маслихата от 22 декабря 2011 года № 521/01-06)
  title:
    rus: О внесении изменений в решение от 24 декабря 2010 года № 26/310-IV "Об областном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған облыстық бюджет туралы" 2010 жылғы 24 желтоқсандағы № 26/310-IV шешімге өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/60627/rus
