act_code: '128671'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 29 декабря 2018 года № 33/219-VI. Зарегистрировано Управлением юстиции города Семей Департамента юстиции Восточно-Казахстанской области 14 января 2019 года № 5-2-204. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 30 декабря 2019 года № 48/329-VI (вводится в действие с 01.01.2020)
title:
  rus: «О бюджете Приречного сельского округа на 2019-2021 годы»
  kaz: «Приречный ауылдық округінің 2019-2021 жылдарға арналған бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '157003000002'
version_date:
  kaz: 2019-12-06
  rus: 2019-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/128671/kaz/06.12.2019
  rus: https://zan.gov.kz/client/#!/doc/128671/rus/06.12.2019
caused_by:
  code: '137339'
  requisite: Решение маслихата города Семей Восточно-Казахстанской области от 6 декабря 2019 года № 46/301-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 24 декабря 2019 года № 6435. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 30 декабря 2019 года № 48/329-VI (вводится в действие с 01.01.2020)
  title:
    rus: О внесении изменений в решение маслихата города Семей от 29 декабря 2018 года № 33/219-VI «О бюджете Приречного сельского округа на 2019-2021 годы»
    kaz: Семей қаласы мәслихатының 2018 жылғы 29 желтоқсандағы № 33/219-VI «Приречный ауылдық округінің 2019-2021 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137339/rus
