act_code: '197701'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 5 июня 2024 года № 12/5-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 июня 2024 года № 9041-16
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-05
approved_by:
- '157010000002'
version_date:
  kaz: 2024-06-05
  rus: 2024-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/197701/kaz/05.06.2024
  rus: https://zan.gov.kz/client/#!/doc/197701/rus/05.06.2024
