act_code: '200078'
requisite: Решение акима района Үлкен Нарын Восточно-Казахстанской области от 21 августа 2024 года № 1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 августа 2024 года № 9063-16
title:
  rus: Об образовании избирательных участков по району Үлкен Нарын
  kaz: Үлкен Нарын ауданы бойынша сайлау учаскелерiн құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-21
approved_by:
- '157022000003'
version_date:
  kaz: 2024-08-21
  rus: 2024-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/200078/kaz/21.08.2024
  rus: https://zan.gov.kz/client/#!/doc/200078/rus/21.08.2024
