act_code: '128256'
requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 27 декабря 2018 года № 38/2-VI. Зарегистрировано Управлением юстиции города Усть-Каменогорска Департамента юстиции Восточно-Казахстанской области 10 января 2019 года № 5-1-207. Утратило силу решением Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 23 декабря 2019 года № 52/2-VI (вводится в действие с 01.01.2020)
title:
  rus: О бюджете города Усть-Каменогорска на 2019-2021 годы
  kaz: Өскемен қаласының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '157002000002'
version_date:
  kaz: 2018-12-27
  rus: 2018-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/128256/kaz/27.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128256/rus/27.12.2018
