act_code: '39351'
requisite: Шығыс Қазақстан облысы Абай аудандық мәслихатының 2008 жылғы 18 сәуірдегі № 5-4 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Абай ауданындағы Әділет басқармасында 2008 жылғы 29 сәуірде № 5-5-79 тіркелді. Күші жойылды - Шығыс Қазақстан облысы Абай аудандық мәслихатының 2013 жылғы 26 сәуірдегі № 12/3-V шешімімен
title:
  rus: Жерлерге салынатын базалық салық ставкалары туралы
  kaz: Жерлерге салынатын базалық салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-18
approved_by:
- '157006000002'
version_date:
  kaz: 2008-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/39351/kaz/18.04.2008
