act_code: '63778'
requisite: Решение акима Белкарагайского сельского округа Катон-Карагайского района Восточно-Казахстанской области от 14 февраля 2012 года № 01. Зарегистрировано управлением юстиции Катон-Карагайского района Департамента юстиции Восточно-Казахстанской области 27 февраля 2012 года за № 5-13-115
title:
  rus: О наименовании и переименовании улиц населенных пунктов Белкарагайского сельского округа
  kaz: Белқарағай ауылдық округі елді мекендерінің көшелеріне атау беру және  атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-02-14
approved_by:
- '157014001002'
version_date:
  kaz: 2012-02-14
  rus: 2012-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/63778/kaz/14.02.2012
  rus: https://zan.gov.kz/client/#!/doc/63778/rus/14.02.2012
