act_code: '176848'
requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 26 декабря 2022 года № 27-7
title:
  rus: О бюджете города Зайсан Зайсанского района на 2023-2025 годы
  kaz: 2023 -2025 жылдарға арналған Зайсан ауданы Зайсан қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-26
approved_by:
- '157012000002'
version_date:
  kaz: 2023-05-15
  rus: 2023-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/176848/kaz/15.05.2023
  rus: https://zan.gov.kz/client/#!/doc/176848/rus/15.05.2023
caused_by:
  code: '181724'
  requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 15 мая 2023 года № 01-03/VIII-4-3
  title:
    rus: О внесении изменений и дополнения в решение Зайсанского районного маслихата от 26 декабря 2022 года № 27-7 «О бюджете города Зайсан Зайсанского района на 2023-2025 годы»
    kaz: Зайсан аудандық мәслихатының 2022 жылғы 26 желтоқсандағы «2023-2025  жылдарға арналған Зайсан ауданы Зайсан қаласының бюджеті туралы» №27-7 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181724/rus
