act_code: '177843'
requisite: Решение маслихата района Алтай Восточно-Казахстанской области от 29 декабря 2022 года № 29/15-VII
title:
  rus: О бюджете Северного сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Северный ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '157013000002'
version_date:
  kaz: 2022-12-29
  rus: 2022-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/177843/kaz/29.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177843/rus/29.12.2022
