act_code: '43640'
requisite: Шығыс Қазақстан облысы Көкпекті аудандық мәслихатының 10 сессиясының 2008 жылғы 23 желтоқсандағы № 10-3 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Көкпекті аудандық әділет басқармасында 2009 жылғы 9 қаңтарда № 5-15-45 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Көкпекті аудандық мәслихатының 2010 жылғы 2 наурыздағы № 45 хаты
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '157015000002'
version_date:
  kaz: 2009-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43640/kaz/24.07.2009
caused_by:
  code: '47247'
  requisite: Шығыс Қазақстан облысы Көкпекті аудандық мәслихатының 2009 жылғы 24 шілдедегі № 16-5/1 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Көкпекті аудандық әділет басқармасында 2009 жылғы 5 тамызда № 5-15-56 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Көкпекті аудандық мәслихатының 2010 жылғы 02 наурыздағы № 45 хаты
  title:
    rus: 2008 жылғы 23 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 10-3 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: 2008 жылғы 23 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 10-3 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47247/rus
