act_code: '43640'
requisite: Шығыс Қазақстан облысы Көкпекті аудандық мәслихатының 10 сессиясының 2008 жылғы 23 желтоқсандағы № 10-3 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Көкпекті аудандық әділет басқармасында 2009 жылғы 9 қаңтарда № 5-15-45 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Көкпекті аудандық мәслихатының 2010 жылғы 2 наурыздағы № 45 хаты
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '157015000002'
version_date:
  kaz: 2009-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43640/kaz/23.11.2009
caused_by:
  code: '49303'
  requisite: Шығыс Қазақстан облысы Көкпекті аудандық мәслихатының 2009 жылғы 23 қарашадағы № 18-2 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Көкпекті аудандық әділет басқармасында 2009 жылғы 9 желтоқсанда № 5-15-63 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Көкпекті аудандық мәслихатының 2010 жылғы 2 наурыздағы № 45 хаты
  title:
    rus: 2008 жылғы 23 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 10-3 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: 2008 жылғы 23 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 10-3 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49303/rus
