act_code: '152137'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 29 декабря 2020 года № 57-765/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 31 декабря 2020 года № 8198. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 30 декабря 2021 года № 12-198/VII (вводится в действие с 01.01.2022)
title:
  rus: О бюджете Келдимуратовского сельского округа Урджарского района на 2021-2023 годы
  kaz: Үржар ауданы Келдімұрат ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '157019000002'
version_date:
  kaz: 2020-12-29
  rus: 2020-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/152137/kaz/29.12.2020
  rus: https://zan.gov.kz/client/#!/doc/152137/rus/29.12.2020
