act_code: '42624'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 3 декабря 2008 года № 13-2-IV. Зарегистрировано в Управлении юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 3 декабря 2008 года за № 5-8-70. Утратило силу решением Бородулихинского районного маслихата Восточно-Казахстанской области от 11 августа 2009 года № 19-4-IV
title:
  rus: Об утверждении Инструкция оказания социальных выплат семьям из числа получателей государственной адресной социальной помощи и государственного пособия на детей до 18 лет, в связи с удорожанием цен на продукты питания"
  kaz: Тамақ өнімдеріне арналған бағаның қымбаттағанына байланысты мемлекеттік атаулы әлеуметтік көмек және 18 жасқа дейінгі балаларына мемлекеттік жәрдемақы алатындардың ішінен шыққан жанұяларға әлеуметтік көмек көрсетудің нұсқаулық бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-03
approved_by:
- '157008000002'
version_date:
  kaz: 2008-12-03
  rus: 2008-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/42624/kaz/03.12.2008
  rus: https://zan.gov.kz/client/#!/doc/42624/rus/03.12.2008
