act_code: '154410'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 4 марта 2021 года № 3/6-VII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 7 апреля 2021 года № 8537. Утратило силу решением Риддерского городского маслихата Восточно-Казахстанской области от 19 мая 2022 года № 15/2-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-04
approved_by:
- '157005000002'
version_date:
  kaz: 2021-03-04
  rus: 2021-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/154410/kaz/04.03.2021
  rus: https://zan.gov.kz/client/#!/doc/154410/rus/04.03.2021
