act_code: '23213'
requisite: Решение XII сессии Усть-Каменогорского городского Маслихата третьего созыва от 3 марта 2005 года № 12/4. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 марта 2005 года за № 2223. Утратило силу - решением Усть-Каменогорского городского маслихата от 23 июля 2010 года № 26/4
title:
  rus: Правила о порядке оказания жилищной помощи малообеспеченным гражданам
  kaz: Тұрмысы төмен азаматтарға тұрғын үй көмегін көрсету тәртібі туралы ереже
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-03-03
approved_by:
- '157002000002'
version_date:
  kaz: 2008-04-17
  rus: 2008-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/23213/kaz/17.04.2008
  rus: https://zan.gov.kz/client/#!/doc/23213/rus/17.04.2008
caused_by:
  code: '39926'
  requisite: Решение Усть-Каменогорского городского маслихата от 17 апреля 2008 года № 6/9. Зарегистрировано управлением юстиции города Усть-Каменогорска Восточно-Казахстанской области 5 мая 2008 года за № 5-1-83. Утратило силу решением Усть-Каменогорского городского маслихата от 23 июля 2010 года № 26/4
  title:
    rus: О внесении изменений и дополнений в решение от 3 марта 2005 года № 12/4 "Правила о порядке оказания жилищной помощи малообеспеченным гражданам"
    kaz: '"Тұрмысы төмен азаматтарға тұрғын үй көмегін көрсету тәртібі туралы ереже" 2005 жылғы 3 наурыздағы № 12/4 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/39926/rus
