act_code: '62100'
requisite: Решение акима города Курчатова Восточно-Казахстанской области от 5 декабря 2011 года № 22. Зарегистрировано Управлением юстиции города Курчатова Департамента юстиции Восточно-Казахстанской области 22 декабря 2011 года за № 5-3-112. Прекращено действие по истечении срока, на который решение было принято, на основании письма акима города Курчатова Восточно-Казахстанской области от 4 мая 2012 года № 1694/02-31
title:
  rus: О проведении приписки граждан мужского пола Республики Казахстан, которым в год приписки исполняется семнадцать лет, а также юношей старших возрастов, не прошедших ранее приписку, к призывному участку отдела по делам обороны города Курчатова в 2012 году
  kaz: 2012 жылы Курчатов қаласының қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне тіркеу жылы он жеті жасқа толатын, сондай-ақ шақыру учаскесіне бұрын тіркелмеген Қазақстан Республикасының еркек жынысты азаматтарын тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-05
approved_by:
- '157004000001'
version_date:
  kaz: 2011-12-05
  rus: 2011-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/62100/kaz/05.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62100/rus/05.12.2011
