act_code: '56181'
requisite: Решение акима города Усть-Каменогорска Восточно-Казахстанской области от 13 декабря 2010 года № 15. Зарегистрировано Управлением юстиции города Усть-Каменогорск Департамента юстиции Восточно-Казахстанской области 27 декабря 2010 года за № 5-1-154. Утратило силу в связи с истечением срока действия (письмо аппарата акима города Усть-Каменогорска от 11 апреля 2011 года № Шн-5/229)
title:
  rus: Об организации и обеспечении приписки к призывному участку граждан мужского пола, которым в 2011 году исполняется семнадцать лет
  kaz: 2011 жылы жасы он жетіге толатын ер жынысындағы азаматтарды шақыру учаскесіне есепке тіркеуді ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-13
approved_by:
- '157002000001'
version_date:
  kaz: 2010-12-13
  rus: 2010-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/56181/kaz/13.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56181/rus/13.12.2010
