act_code: '225603'
requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 20 мая 2026 года № 50/1-VIII
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по Зайсанскому району на 2026-2030 годы
  kaz: Зайсан ауданы бойынша 2026-2030 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-20
approved_by:
- '157012000002'
version_date:
  kaz: 2026-05-20
  rus: 2026-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/225603/kaz/20.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225603/rus/20.05.2026
