act_code: '115605'
requisite: Решение Восточно-Казахстанского областного маслихата от 6 октября 2017 года № 14/156-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 октября 2017 года № 5262. Утратило силу решением Восточно-Казахстанского областного маслихата от 18 ноября 2025 года № 26/203-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении правил общего водопользования в Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысында ортақ су пайдалану ережелерін белгілеу туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-10-06
approved_by:
- '157000000002'
version_date:
  kaz: 2023-05-31
  rus: 2023-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/115605/kaz/31.05.2023
  rus: https://zan.gov.kz/client/#!/doc/115605/rus/31.05.2023
caused_by:
  code: '182527'
  requisite: Решение Восточно-Казахстанского областного маслихата от 31 мая 2023 года № 3/25-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 5 июня 2023 года № 8856-16. Утратило силу решением Восточно-Казахстанского областного маслихата от 18 ноября 2025 года № 26/203-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Восточно-Казахстанского областного маслихата от 6 октября 2017 года № 14/156-VI«Об установлении правил общего водопользования в Восточно-Казахстанской области»
    kaz: 2017 жылғы 6 қазандағы № 14/156-VI «Шығыс Қазақстан облысында ортақ су пайдалану ережелерін белгілеу туралы» Шығыс Қазақстан облыстық мәслихатының шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182527/rus
