act_code: '128713'
requisite: Решение акима Соловьевского сельского округа Зыряновского района Восточно-Казахстанской области от 25 декабря 2018 года № 1. Зарегистрировано Управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 18 января 2019 года № 5-12-190
title:
  rus: О переименовании улиц в селе Соловьево, Маяк, Подорленок Соловьевского сельского округа Зыряновского района
  kaz: Зырян ауданы Соловьево селолық округінің Соловьево, Маяк, Подорленок ауылдарының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '157013012002'
version_date:
  kaz: 2018-12-25
  rus: 2018-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/128713/kaz/25.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128713/rus/25.12.2018
