act_code: '11222'
requisite: Решение ХII сессии Восточно-Казахстанского областного маслихата II созыва от 21 декабря 2001 года № 12/12-II зарегистрировано управлением юстиции Восточно-Казахстанской области 24 января 2002 года за № 653. Прекращено действие по истечении срока, на который решение было принято (письмо Восточно-Казахстанского областного маслихата от 20 мая 2011 года № 170/01-06)
title:
  rus: Об утверждении областной схемы зонирования земель и корректировке базовых налоговых ставок на землю на 2002 год
  kaz: Жерлерді аймақтарға бөлудің облыстық схемасын бекіту және 2002 жылы жерге салынатын негізгі салық ставкаларын түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-21
approved_by:
- '157000000002'
version_date:
  kaz: 2001-12-21
  rus: 2001-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/11222/kaz/21.12.2001
  rus: https://zan.gov.kz/client/#!/doc/11222/rus/21.12.2001
