act_code: '40065'
requisite: Решение Зыряновского районного маслихата Восточно-Казахстанской области от 13 мая 2008 года № 8/3-IV. Зарегистрировано Управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 30 мая 2008 года за № 5-12-63. Утратило силу на основании письма аппарата маслихата Зыряновского района от 6 мая 2009 года № 02-05/135
title:
  rus: Об утверждении Правил предоставления жилищной помощи на оплату за содержание жилища, потребленные коммунальные услуги и услуги связи
  kaz: Тұрғын үй көмегін, тұрғын үйді ұстау, коммуналдық қызметтерді тұтыну және байланыс қызметтерін көрсету Ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2008-05-13
approved_by:
- '157013000002'
version_date:
  kaz: 2008-07-10
  rus: 2008-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/40065/kaz/10.07.2008
  rus: https://zan.gov.kz/client/#!/doc/40065/rus/10.07.2008
caused_by:
  code: '40928'
  requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 10 июля 2008 года № 9/5-IV. Зарегистрировано Управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 24 июля 2008 года за № 5-12-66. Утратило силу на основании письма аппарата маслихата Зыряновского района от 6 мая 2009 года № 02-05/135
  title:
    rus: О внесении дополнений в решение от 13 мая 2008 года № 8/3-1V "Об утверждении Правил предоставления жилищной помощи на оплату за содержание жилища, потребленные коммунальные услуги и услуги связи"
    kaz: '"Тұрғын үй көмегін, тұрғын үйді ұстау, коммуналдық қызметтерді тұтыну және байланыс қызметтерін көрсету Ережелерін бекіту туралы" 2008 жылғы 13 мамырдағы № 8/3-IV шешімге толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/40928/rus
