act_code: '58992'
requisite: Решение акима Акжарского сельского округа Урджарского района Восточно-Казахстанской области от 5 мая 2011 года № 06. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 27 мая 2011 года за № 5-18-125
title:
  rus: О переименовании улицы в селе Амангельды
  kaz: Амангелді ауылындағы көшенің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-05-05
approved_by:
- '157019002001'
version_date:
  kaz: 2011-05-05
  rus: 2011-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/58992/kaz/05.05.2011
  rus: https://zan.gov.kz/client/#!/doc/58992/rus/05.05.2011
