act_code: '109608'
requisite: Решение акима Таргыского сельского округа Уланского района Восточно-Казахстанской области от 30 декабря 2016 года № 5. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 26 января 2017 года № 4864
title:
  rus: О переименовании улицы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-30
approved_by:
- '157018017002'
version_date:
  kaz: 2016-12-30
  rus: 2016-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/109608/kaz/30.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109608/rus/30.12.2016
