act_code: '139027'
requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 30 декабря 2019 года № 46/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 января 2020 года № 6654. Утратило силу решением Курчумского районного маслихата Восточно-Казахстанской области от 28 декабря 2020 года № 59/2-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете сельских округов Курчумского района на 2020-2022 годы
  kaz: Күршім ауданының ауылдық округтерінің 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '157016000002'
version_date:
  kaz: 2020-07-16
  rus: 2020-07-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/139027/kaz/16.07.2020
  rus: https://zan.gov.kz/client/#!/doc/139027/rus/16.07.2020
caused_by:
  code: '145083'
  requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 16 июля 2020 года № 51/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 24 июля 2020 года № 7408. Утратило силу решением Курчумского районного маслихата Восточно-Казахстанской области от 28 декабря 2020 года № 59/2-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Курчумского районного маслихата от 30 декабря 2019 года № 46/2-VI «О бюджете сельских округов Курчумского района на 2020-2022 годы»
    kaz: «Күршім ауданының ауылдық округтерінің 2020-2022 жылдарға арналған бюджеті туралы» Күршім аудандық мәслихатының 2019 жылғы 30 желтоқсандағы № 46/2-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145083/rus
