act_code: '204418'
requisite: Решение маслихата района Марқакөл Восточно-Казахстанской области от 12 декабря 2024 года № 15/2-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 декабря 2024 года № 9116-16
title:
  rus: Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах района Марқакөл
  kaz: Марқакөл ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебiнен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидасы мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-12
approved_by:
- '157023000002'
version_date:
  kaz: 2024-12-12
  rus: 2024-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/204418/kaz/12.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204418/rus/12.12.2024
