act_code: '125981'
requisite: Решение акима Егинсуского сельского округа Уланского района Восточно-Казахстанской области от 7 ноября 2018 года № 1. Зарегистрировано Управлением юстиции Уланского района Департамента юстиции Восточно-Казахстанской области 16 ноября 2018 года № 5-17-205
title:
  rus: О переименовании улиц
  kaz: Көше атауларын қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-07
approved_by:
- '157018009002'
version_date:
  kaz: 2018-11-07
  rus: 2018-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/125981/kaz/07.11.2018
  rus: https://zan.gov.kz/client/#!/doc/125981/rus/07.11.2018
