act_code: '156018'
requisite: Решение акима Шемонаихинского района Восточно-Казахстанской области от 30 апреля 2021 года № 04. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 мая 2021 года № 8761
title:
  rus: Об образовании избирательных участков по Шемонаихинскому району
  kaz: Шемонаиха ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-30
approved_by:
- '157020000003'
version_date:
  kaz: 2021-04-30
  rus: 2021-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/156018/kaz/30.04.2021
  rus: https://zan.gov.kz/client/#!/doc/156018/rus/30.04.2021
