act_code: '41446'
requisite: Шығыс Қазақстан облысы Зайсан аудандық мәслихатының 2008 жылғы 11 шілдедегі № 7-5/3 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Зайсан аудандық Әділет басқармасында 2008 жылғы 22 тамызда № 5-11-84 тіркелді. Күші жойылды - Зайсан аудандық мәслихатының 2009 жылғы 29 желтоқсандағы № 17-6/2 шешімімен
title:
  rus: Зайсан қаласының жер учаскелері үшін төлемақылардың базалық ставкаларына және жер салығының базалық ставкаларына түзету коэффициенттерін бекіту туралы
  kaz: Зайсан қаласының жер учаскелері үшін төлемақылардың базалық ставкаларына және жер салығының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-07-11
approved_by:
- '157012000002'
version_date:
  kaz: 2008-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/41446/kaz/11.07.2008
