act_code: '145451'
requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 30 июля 2020 года № 59/3-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 августа 2020 года № 7442
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования, норм их предельной заполняемости, требований к их материально-техническому и организационному обеспечению, границ прилегающих территорий, в которых запрещено проведение пикетирования по городу Усть-Каменогорску
  kaz: Өскемен қаласы бойынша бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, оларды пайдалану тәртібін, олардың шекті толу нормаларын, оларды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-30
approved_by:
- '157002000002'
version_date:
  kaz: 2020-07-30
  rus: 2020-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/145451/kaz/30.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145451/rus/30.07.2020
