act_code: '23284'
requisite: Решение XIII сессии Шемонаихинского районного маслихата Восточно-Казахстанской области от 18 февраля 2005 года № 13/9-III. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 марта 2005 года № 2229. Утратило силу на основании решения Шемонаихинского районного маслихата от 14 февраля 2006 года № 5-19-13
title:
  rus: Об утверждении Положения о порядке назначения и осуществления социальных выплат отдельным категориям граждан
  kaz: Азаматтардың жеке санаттарына әлеуметтік төлемдерді белгілеу және төлеу тәртібі туралы Ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2005-02-18
approved_by:
- '157020000002'
version_date:
  rus: 2005-02-18
source:
  rus: https://zan.gov.kz/client/#!/doc/23284/rus/18.02.2005
