act_code: '5938'
requisite: Решение Акима Восточно-Казахстанской области от 25 апреля 2000 года N 849к. Зарегистрировано управлением юстиции Восточно-Казахстанской области 10 мая 2000 года за N 324. Утратило силу решением акима ВКО от 28 июля 2004 года N 90
title:
  rus: Об итогах работы объектов жилищного, социально-культурного и административно-хозяйственного назначения области в отопительный период 1999-2000 г.г. и задачах по подготовке к зиме 2000-2001 г.г.
  kaz: Облыстың тұрғын үй, әлеуметтiк-мәдени және әкiмшiлiк-шаруашылық бағыттағы объектiлерiнің 1999-2000 жылдардағы от жағу маусымындағы жұмыс қорытындылары және 2000-2001 жылдардағы қыс кезiне дайындық жөнiндегi мiндеттер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-04-24
approved_by:
- '157000000001'
version_date:
  kaz: 2000-04-24
  rus: 2000-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/5938/kaz/24.04.2000
  rus: https://zan.gov.kz/client/#!/doc/5938/rus/24.04.2000
