act_code: '28474'
requisite: Шығыс Қазақстан облысы Аягөз ауданы әкімінің 2006 жылғы 15 мамырдағы № 01 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Аягөз аудандық Әділет басқармасында 2006 жылғы 16 маусымда № 5-6-29 тіркелді.
title:
  rus: Су пайдалану нормасын бекіту туралы
  kaz: Су пайдалану нормасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-05-15
approved_by:
- '157007000003'
version_date:
  kaz: 2006-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/28474/kaz/15.05.2006
