act_code: '229744'
requisite: Решение акима района Самар Восточно-Казахстанской области от 3 сентября 2026 года № 3
title:
  rus: Об отмене решения акима района Самар от 2 сентября 2026 года № 2 «Об объявлении чрезвычайной ситуации техногенного характера местного масштаба на территории населенных пунктов Самарское, Мариногорка, Палатцы и Аққала района Самар Восточно-Казахстанской области»
  kaz: «Шығыс Қазақстан облысының Самар ауданындағы Самар, Мариногорка, Палатцы және Аққала елді мекендерінің аумағында жергілікті ауқымдағы техногендік сипаттағы төтенше жағдайды жариялау туралы» Самар ауданы әкімінің 2026 жылғы 2 қыркүйектегі № 2 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-09-03
approved_by:
- '157021000003'
version_date:
  kaz: 2026-09-03
  rus: 2026-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/229744/kaz/03.09.2026
  rus: https://zan.gov.kz/client/#!/doc/229744/rus/03.09.2026
