act_code: '62794'
requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 21 декабря 2011 года № 42/2-IV. Зарегистрировано управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 30 декабря 2011 года за № 5-12-130. Утратило силу (письмо маслихата Зыряновского района от 10 января 2013 года № 04-07-13)
title:
  rus: О бюджете Зыряновского района на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған Зырян ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-21
approved_by:
- '157013000002'
version_date:
  kaz: 2012-11-23
  rus: 2012-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/62794/kaz/23.11.2012
  rus: https://zan.gov.kz/client/#!/doc/62794/rus/23.11.2012
caused_by:
  code: '68745'
  requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 23 ноября 2012 года № 11/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 28 ноября 2012 года за № 2742. Утратило силу (письмо маслихата Зыряновского района от 10 января 2013 года № 04-07-13)
  title:
    rus: О внесении изменений и дополнения в решение от 21 декабря 2011 года № 42/2-IV "О бюджете Зыряновского района на 2012-2014 годы"
    kaz: '"2012-2014 жылдарға арналған Зырян ауданының бюджеті туралы" 2011 жылғы 21 желтоқсандағы № 42/2-IV шешімге өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/68745/rus
