act_code: '192202'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 26 декабря 2023 года № 10/134-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 9 января 2024 года № 8950-16
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '157014000002'
version_date:
  kaz: 2025-09-12
  rus: 2025-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/192202/kaz/12.09.2025
  rus: https://zan.gov.kz/client/#!/doc/192202/rus/12.09.2025
caused_by:
  code: '214210'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 12 сентября 2025 года № 30/338-VIII
  title:
    rus: О внесении изменения в решение маслихата Катон-Карагайского района от 26 декабря 2023 года № 10/134-VIІІ «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Катонқарағай аудандық мәслихатының 2023 жылғы  26 желтоқсанындағы № 10/134-VIII «Әлеуметтік көмек көрсетудің, мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214210/rus
