act_code: '54375'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 30 июля 2010 года № 25/11-IV. Зарегистрировано управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 9 сентября 2010 года за N 5-9-135. Утратило силу - решением Глубоковского районного маслихата Восточно-Казахстанской области от 25 февраля 2015 года № 33/2-V
title:
  rus: Об утверждении Правил оказания малообеспеченным семьям (гражданам) жилищной помощи
  kaz: Аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-07-30
approved_by:
- '157010000002'
version_date:
  kaz: 2010-07-30
  rus: 2010-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/54375/kaz/30.07.2010
  rus: https://zan.gov.kz/client/#!/doc/54375/rus/30.07.2010
