act_code: '156572'
requisite: Решение акима Биржанского сельского округа Зайсанского района Восточно-Казахстанской области от 15 июня 2021 года № 3. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 июня 2021 года № 23159. Утратило силу решением акима Биржанского сельского округа Зайсанского района Восточно-Казахстанской области от 25 октября 2021 года № 5 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-06-15
approved_by:
- '157012006002'
version_date:
  kaz: 2021-06-15
  rus: 2021-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/156572/kaz/15.06.2021
  rus: https://zan.gov.kz/client/#!/doc/156572/rus/15.06.2021
