act_code: '169864'
requisite: Решение акима Каратальского сельского округа Зайсанского района Восточно-Казахстанской области от 8 июля 2022 года № 3. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 июля 2022 года № 28820
title:
  rus: О присвоении наименовании улицам села Улкен Каратал Каратальского сельского округа Зайсанского района Восточно - Казахстанской области
  kaz: Шығыс Қазақстан облысы Зайсан ауданы Қаратал ауылдық округі Үлкен Қаратал ауылының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-07-08
approved_by:
- '157012008002'
version_date:
  kaz: 2022-07-08
  rus: 2022-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/169864/kaz/08.07.2022
  rus: https://zan.gov.kz/client/#!/doc/169864/rus/08.07.2022
