act_code: '117382'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 27 декабря 2017 года № 17/144-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 4 января 2018 года № 5385. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 21 декабря 2018 года № 28/238-VI
title:
  rus: О бюджете Жарминского района на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Жарма ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-27
approved_by:
- '157011000002'
version_date:
  kaz: 2018-04-28
  rus: 2018-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/117382/kaz/28.04.2018
  rus: https://zan.gov.kz/client/#!/doc/117382/rus/28.04.2018
caused_by:
  code: '121521'
  requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 28 апреля 2018 года № 20/190-VI. Зарегистрировано Управлением юстиции Жарминского района Департамента юстиции Восточно-Казахстанской области 4 мая 2018 года № 5-10-140. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 21 декабря 2018 года № 28/238-VI
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 27 декабря 2017 года № 17/144-VI «О бюджете Жарминского района на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған Жарма ауданының бюджеті туралы» Жарма аудандық мәслихатының 2017 жылғы 27 желтоқсандағы № 17/144-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121521/rus
