act_code: '2744'
requisite: Решение Восточно-Казахстанского областного маслихата от 18 марта 1998 года № 16/3. Зарегистрировано управлением юстиции Восточно-Казахстанской области 31 июля 1998 года № 64. Утратило силу в связи с истечением срока действия (письмо начальника департамента юстиции Восточно-Казахстанской области от 27 декабря 2004 года)
title:
  rus: О региональной программе по борьбе с преступностью на 1998-2000 годы в свете Послания Президента страны народу Казахстана
  kaz: Ел Президентiнiң Қазақстан халқына Жолдауы тұрғысында 1998-2000 жылдарға қылмыскерлiкпен күресу жөнiндегi аймақтық бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-03-18
approved_by:
- '157000000002'
version_date:
  kaz: 1998-03-18
  rus: 1998-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/2744/kaz/18.03.1998
  rus: https://zan.gov.kz/client/#!/doc/2744/rus/18.03.1998
