act_code: '22554'
requisite: Решение акима Восточно-Казахстанской области от 31 декабря 2004 года № 03. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 января 2005 года № 2122. Утратило силу в связи с истечением срока действие (письмо акимата Восточно-Казахстанской от 16 мая 2006 года № 6/1637)
title:
  rus: О проведении приписки граждан 1988 года рождения к призывным участкам в 2005 году
  kaz: 1988 жылы туған азаматтарды 2005 жылы шақыру учаскелеріне тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-31
approved_by:
- '157000000001'
version_date:
  kaz: 2004-12-31
  rus: 2004-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/22554/kaz/31.12.2004
  rus: https://zan.gov.kz/client/#!/doc/22554/rus/31.12.2004
