act_code: '36914'
requisite: Шығыс Қазақстан облысы Абай аудандық мәслихатының 2007 жылғы 24 желтоқсандағы № 3-9 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Абай ауданындағы әділет басқармасында 2008 жылғы 22 қаңтарда № 5-5-67 тіркелді. Күші жойылды - Шығыс Қазақстан облысы Абай аудандық мәслихатының 2012 жылғы 21 тамыздағы № 6-4 шешімімен
title:
  rus: Бюджетпен бір күндік талон алу арқылы есеп айырысатын жеке тұлғалар үшін ұсынылған біркүндік алым ставкалары туралы
  kaz: Бюджетпен бір күндік талон алу арқылы есеп айырысатын жеке тұлғалар үшін ұсынылған біркүндік алым ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '157006000002'
version_date:
  kaz: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/36914/kaz/24.12.2007
