act_code: '229076'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 18 августа 2026 года № 38/416-VIII
title:
  rus: Об утверждении Положения государственного учреждения "Аппарат Катон-Карагайского районного маслихата"
  kaz: '"Катонқарағай аудандық мәслихатының аппараты" мемлекеттік мекемесі туралы  ережені бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-18
approved_by:
- '157014000002'
version_date:
  kaz: 2026-08-18
  rus: 2026-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/229076/kaz/18.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229076/rus/18.08.2026
