act_code: '132549'
requisite: Решение акима Ушановского сельского округа Глубоковского района Восточно-Казахстанской области от 17 июня 2019 года № 4. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 июня 2019 года № 6021. Утратило силу решением акима Ушановского сельского округа Глубоковского района Восточно-Казахстанской области от 19 декабря 2019 года № 8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий на крупно-рогатый скот в селе Ушаново Ушановского сельского округа Глубоковского района
  kaz: Глубокое ауданы Ушаново ауылдық округі Ушаново ауылының ірі қара малдарына шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-17
approved_by:
- '157010007002'
version_date:
  kaz: 2019-06-17
  rus: 2019-06-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/132549/kaz/17.06.2019
  rus: https://zan.gov.kz/client/#!/doc/132549/rus/17.06.2019
