act_code: '179484'
requisite: Решение акима Аккайнарского сельского округа Катон-Карагайского района Восточно-Казахстанской области от 5 апреля 2023 года № 4
title:
  rus: О снятии ветеринарного карантина и отмене решения акима Аккайнарского сельского округа Катон - Карагайского района Восточно-Казахстанской области от 13 марта 2023 года № 3 «Об установлении карантина в селе Аккайнар Аккайнарского сельского округа Катон-Карагайского района Восточно-Казахстанской области»
  kaz: Ветеринариялық карантинді алу және «Шығыс Қазақстан облысы Катонқарағай ауданы Аққайнар ауылдық округінің Аққайнар ауылында карантин белгілеу туралы» Шығыс Қазақстан облысы Катонқарағай ауданы Аққайнар ауылдық округі әкімінің 2023 жылғы 13 наурыздағы № 3 шешімін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-04-05
approved_by:
- '157014014002'
version_date:
  kaz: 2023-04-05
  rus: 2023-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/179484/kaz/05.04.2023
  rus: https://zan.gov.kz/client/#!/doc/179484/rus/05.04.2023
