act_code: '161886'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 30 ноября 2021 года № 10/3-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 декабря 2021 года № 25855
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану
  kaz: Мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-11-30
approved_by:
- '157017000002'
version_date:
  kaz: 2022-11-30
  rus: 2022-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/161886/kaz/30.11.2022
  rus: https://zan.gov.kz/client/#!/doc/161886/rus/30.11.2022
caused_by:
  code: '174761'
  requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 30 ноября 2022 года № 28/3-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 декабря 2022 года № 30873
  title:
    rus: О внесении изменений в решение Тарбагатайского районного маслихата от 30 ноября 2021 года № 10/3-VII «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Тарбагатайском районе»
    kaz: Тарбағатай аудандық мәслихатының 2021 жылғы 30 қарашадағы № 10/3-VII «Тарбағатай ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174761/rus
