act_code: '96242'
requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 18 ноября 2015 года № 51/3-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 23 ноября 2015 года № 4239. Утратило силу - решением маслихата Зыряновского района Восточно-Казахстанской области от 30 сентября 2016 года № 8/9-VI
title:
  rus: О социальных гарантиях и социальной поддержке специалистам государственных организаций, работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде жұмыс істейтін мемлекеттік ұйымдардың мамандарына әлеуметтік кепілдіктер және әлеуметтік қолдау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-18
approved_by:
- '157013000002'
version_date:
  kaz: 2015-11-18
  rus: 2015-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/96242/kaz/18.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96242/rus/18.11.2015
