act_code: '118587'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 4 января 2018 года № 17/152-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 24 января 2018 года № 5467
title:
  rus: Об утверждении проекта (схемы) зонирования земель Жарминского района
  kaz: Жарма ауданының жерлерін аймақтарға бөлу жобасын (сызбасын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-04
approved_by:
- '157011000002'
version_date:
  kaz: 2018-01-04
  rus: 2018-01-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/118587/kaz/04.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118587/rus/04.01.2018
