act_code: '55343'
requisite: Шығыс Қазақстан облысы Ұлан ауданы Молодежный кенті әкімінің 2010 жылғы 14 қазандағы № 1 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Ұлан аудандық әділет басқармасында 2010 жылғы 9 қарашада № 5-17-136 тіркелді
title:
  rus: Молодежный кентіндегі аты жоқ көшені атау туралы
  kaz: Молодежный кентіндегі аты жоқ көшені атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-14
approved_by:
- '157018001001'
version_date:
  kaz: 2010-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/55343/kaz/14.10.2010
