act_code: '19851'
requisite: Решение Акима Восточно-Казахстанской области от 21 апреля 2004 года № 82. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 мая 2004 года за № 1796. Утратило силу - постановлением акимата ВКО от 19 марта 2005 года № 124
title:
  rus: Об утверждении регламента аппарата акима Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысы әкімі аппаратының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2004-04-20
approved_by:
- '157000000001'
version_date:
  rus: 2004-04-20
source:
  rus: https://zan.gov.kz/client/#!/doc/19851/rus/20.04.2004
