act_code: '54754'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 10 сентября 2010 года № 30/210-IV. Зарегистрировано Управлением юстиции города Семей Департамента юстиции Восточно-Казахстанской области 7 октября 2010 года за № 5-2-135. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 15 мая 2012 года № 5/38-V
title:
  rus: Об утверждении Правил содержания собак и кошек в городе Семей
  kaz: Семей қаласында иттер мен мысықтарды ұстау ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-10
approved_by:
- '157003000002'
version_date:
  kaz: 2010-09-10
  rus: 2010-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/54754/kaz/10.09.2010
  rus: https://zan.gov.kz/client/#!/doc/54754/rus/10.09.2010
