act_code: '62532'
requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 20 декабря 2011 года № 31-3. Зарегистрировано управлением юстиции Курчумского района Департамента юстиции Восточно-Казахстанской области 30 декабря 2011 года за № 5-14-146. Прекращено действие по истечении срока действия (письмо Курчумского районного маслихата от 29 декабря 2012 года № 215)
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '157016000002'
version_date:
  kaz: 2012-11-21
  rus: 2012-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/62532/kaz/21.11.2012
  rus: https://zan.gov.kz/client/#!/doc/62532/rus/21.11.2012
caused_by:
  code: '68744'
  requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 21 ноября 2012 года № 6-5. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 ноября 2012 года № 2741. Прекращено действие по истечении срока действия (письмо Курчумского районного маслихата от 29 декабря 2012 года № 215)
  title:
    rus: О внесении изменений в решение от 20 декабря 2011 года № 31-3 "О районном бюджете на 2012-2014 годы"
    kaz: '"2012-2014 жылдарға арналған аудандық бюджет туралы" 2011 жылғы 20 желтоқсандағы № 31-3 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/68744/rus
