act_code: '150782'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 22 декабря 2020 года № 57-745/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 28 декабря 2020 года № 8048. Утратило силу решением Урджарского районного маслихата области Абай от 10 апреля 2024 года № 14-251/VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Урджарском районе
  kaz: Үржар ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-22
approved_by:
- '157019000002'
version_date:
  kaz: 2023-04-26
  rus: 2023-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/150782/kaz/26.04.2023
  rus: https://zan.gov.kz/client/#!/doc/150782/rus/26.04.2023
caused_by:
  code: '180583'
  requisite: Решение Урджарского районного маслихата области Абай от 26 апреля 2023 года № 2-30/VIII. Зарегистрировано Департаментом юстиции области Абай 2 мая 2023 года № 59-18. Утратило силу решением Урджарского районного маслихата области Абай от 10 апреля 2024 года № 14-251/VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Урджарского районного маслихата от 22 декабря 2020 года № 57-745/VI «Об определении размера и порядка оказания жилищной помощи в Урджарском районе»
    kaz: Үржар аудандық мәслихатының 2020 жылғы 22 желтоқсандағы № 57-745/VI «Үржар ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180583/rus
