act_code: '121318'
requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 30 марта 2018 года № 27/9-VI. Зарегистрировано Управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 25 апреля 2018 года № 5-12-154
title:
  rus: Об установлении категорий автостоянок (паркингов) и увеличении базовых ставок налога на земли, выделенные под автостоянки (паркинги) по району Алтай
  kaz: Алтай ауданы бойынша автотұрақтар (паркингтер) санаттарын белгілеу және автотұрақтар (паркингтер) үшін бөлінген жерлерге базалық салық мөлшерлемелерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-30
approved_by:
- '157013000002'
version_date:
  kaz: 2022-09-09
  rus: 2022-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/121318/kaz/09.09.2022
  rus: https://zan.gov.kz/client/#!/doc/121318/rus/09.09.2022
caused_by:
  code: '172038'
  requisite: Решение маслихата района Алтай Восточно-Казахстанской области от 9 сентября 2022 года № 20/7-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 сентября 2022 года № 29788
  title:
    rus: О внесении изменений  в решение маслихата Зыряновского района от 30 марта 2018 года № 27/9-VI «Об установлении категорий автостоянок (паркингов) и увеличении базовых ставок налога на земли, выделенные под автостоянки (паркинги) по Зыряновскому району»
    kaz: Зырян ауданының мәслихатының 2018 жылғы 30 наурыздағы № 27/9-VI «Зырян ауданы бойынша автотұрақтар (паркингтер) санаттарын белгілеу және автотұрақтарға (паркингтерге) бөлінген жерлерге базалық салықтық мөлшерлемелерін ұлғайту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172038/rus
