act_code: '194498'
requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 11 марта 2024 года № 01-03/VIII-19-2/1
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества на территории Зайсанского района
  kaz: Зайсан ауданының аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-11
approved_by:
- '157012000002'
version_date:
  kaz: 2024-03-11
  rus: 2024-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/194498/kaz/11.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194498/rus/11.03.2024
