act_code: '217074'
requisite: Решение Восточно-Казахстанского областного маслихата от 18 ноября 2025 года № 25/202-VІІІ
title:
  rus: Об утверждении правил общего водопользования в Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысында ортақ су пайдалану қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-18
approved_by:
- '157000000002'
version_date:
  kaz: 2025-11-18
  rus: 2025-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/217074/kaz/18.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217074/rus/18.11.2025
