act_code: '202085'
requisite: Решение маслихата района Үлкен Нарын Восточно-Казахстанской области от 28 октября 2024 года № 7/50-VIII
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества и определения количества представителей жителей села, микрорайона, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в районе Үлкен Нарын
  kaz: Үлкен Нарын ауданында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, шағын аудан, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2024-10-28
approved_by:
- '157022000002'
version_date:
  kaz: 2024-10-28
  rus: 2024-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/202085/kaz/28.10.2024
  rus: https://zan.gov.kz/client/#!/doc/202085/rus/28.10.2024
