act_code: '66952'
requisite: Решение Кокпектинского районного маслихата Восточно-Казахстанской области от 12 июля 2012 года № 5-3/2). Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 июля 2012 года № 2620. Утратило силу - решением Кокпектинского районного маслихата от 27 мая 2014 года № 24-4/2
title:
  rus: Об определении отдельных категорий нуждающихся граждан и перечня документов, необходимых для получения социальной помощи
  kaz: Әлеуметтік көмек алу үшін мұқтаж азаматтардың жекелеген санаттарын және қажетті құжаттардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-07-12
approved_by:
- '157015000002'
version_date:
  kaz: 2012-07-12
  rus: 2012-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/66952/kaz/12.07.2012
  rus: https://zan.gov.kz/client/#!/doc/66952/rus/12.07.2012
