act_code: '36975'
requisite: Решение акима города Курчатов от 29 декабря 2007 года № 3. Зарегистрировано в Управлении юстиции города Курчатов Департамента юстиции Восточно-Казахстанской области 22 января 2008 года № 5-3-52. Утратило силу решением акима города Курчатова Восточно-Казахстанской области от 9 февраля 2009 года № 13
title:
  rus: О проведении приписки граждан мужского пола РК, которым в год приписки исполняется семнадцать лет, к призывному участку отдела по делам обороны города Курчатов в 2008 году
  kaz: О проведении приписки граждан мужского пола РК, которым в год приписки исполняется семнадцать лет, к призывному участку отдела по делам обороны города Курчатов в 2008 году
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-22
approved_by:
- '157004000003'
version_date:
  rus: 2008-01-22
source:
  rus: https://zan.gov.kz/client/#!/doc/36975/rus/22.01.2008
