act_code: '20603'
requisite: Решение VI сессии Восточно-Казахстанского областного маслихата III созыва от 3 июля 2004 года № 6/80-III. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 13 июля 2004 года за № 1883. Утратило силу - решением Восточно-Казахстанского областного маслихата от 11 марта 2005 года № 10/144-III
title:
  rus: Об утверждении Правил предоставления малообеспеченным гражданам жилищной помощи на содержание жилья и оплату жилищно-коммунальных услуг, услуг связи
  kaz: Тұрмысы төмен азаматтарға үйді ұстауға және үй-коммуналдық қызметке және байланыс қызметтеріне ақы төлеу үшін тұрғын үй жәрдемақыларын беру Ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-07-02
approved_by:
- '157000000002'
version_date:
  kaz: 2004-07-02
  rus: 2004-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/20603/kaz/02.07.2004
  rus: https://zan.gov.kz/client/#!/doc/20603/rus/02.07.2004
