act_code: '165012'
requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 27 декабря 2021 года № 14/16-VII. Утратило силу решением Курчумского районного маслихата Восточно-Казахстанской области от 18 июня 2026 года № 54/11-VIII (вступает в силу по истечении десяти календарных дней после дня первого официального опубликования)
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Сарыоленскому сельскому округу на 2021-2022 годы
  kaz: Сарыөлең ауылдық округі бойынша жайылымдарды басқару және оларды пайдалану жөніндегі 2021-2022 жылдарға арналған жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2021-12-27
approved_by:
- '157016000002'
version_date:
  kaz: 2021-12-27
  rus: 2021-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/165012/kaz/27.12.2021
  rus: https://zan.gov.kz/client/#!/doc/165012/rus/27.12.2021
