act_code: '52581'
requisite: Шығыс Қазақстан облысы Үржар аудандық мәслихатының 2010 жылғы 19 сәуірдегі № 19-191-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Үржар аудандық әділет басқармасында 2010 жылғы 19 мамырда № 5-18-97 тіркелді. Күші жойылды - Үржар аудандық мәслихатының 2012 жылғы 9 шілдедегі № 4-41/V шешімімен
title:
  rus: Тұрмысы төмен азаматтарға тұрғын үй көмегін көрсету Ережесін бекіту туралы
  kaz: Тұрмысы төмен азаматтарға тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-18
approved_by:
- '157019000002'
version_date:
  kaz: 2010-11-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/52581/kaz/01.11.2010
caused_by:
  code: '55820'
  requisite: Шығыс Қазақстан облысы Үржар аудандық мәслихатының 2010 жылғы 1 қарашадағы № 23-259-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Үржар аудандық әділет басқармасында 2010 жылғы 9 желтоқсанда № 5-18-106 тіркелді. Күші жойылды - Үржар аудандық мәслихатының 2012 жылғы 9 шілдедегі № 4-41/V шешімімен
  title:
    rus: '"Тұрмысы төмен азаматтарға тұрғын үй көмегін көрсету Ережесін бекіту туралы" 2010 жылғы 19 сәуірдегі № 19-191-IV шешімге өзгерістер енгізу туралы'
    kaz: '"Тұрмысы төмен азаматтарға тұрғын үй көмегін көрсету Ережесін бекіту туралы" 2010 жылғы 19 сәуірдегі № 19-191-IV шешімге өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/55820/rus
