act_code: '120671'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 20 марта 2018 года № 25-262/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 апреля 2018 года № 5603
title:
  rus: Об установлении категорий автостоянок (паркингов)и увеличении базовых ставок налога на земли, выделенные под автостоянки (паркинги)
  kaz: Автотұрақтар (паркингтер) санаттарын белгілеу және автотұрақтарға (паркингтерге) бөлінген жерлерге базалық салық мөлшерлемелерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-20
approved_by:
- '157019000002'
version_date:
  kaz: 2018-03-20
  rus: 2018-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/120671/kaz/20.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120671/rus/20.03.2018
