act_code: '61707'
requisite: Решение акима Курчумского района Восточно-Казахстанской области от 22 ноября 2011 года № 54. Зарегистрировано управлением юстиции Курчумского района Департамента юстиции Восточно-Казахстанской области 30 ноября 2011 года за № 5-14-142. Утратило силу решением акима Курчумского района от 1 июля 2013 года № 66
title:
  rus: Об образовании окружных избирательных участков
  kaz: Округтік сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-22
approved_by:
- '157016000001'
version_date:
  kaz: 2011-11-22
  rus: 2011-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/61707/kaz/22.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61707/rus/22.11.2011
