act_code: '139218'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 13 января 2020 года № 42/349-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 января 2020 года № 6649. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 53/538-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете поселка Ауэзова Жарминского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Жарма ауданы Әуезов кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '157011000002'
version_date:
  kaz: 2020-04-29
  rus: 2020-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/139218/kaz/29.04.2020
  rus: https://zan.gov.kz/client/#!/doc/139218/rus/29.04.2020
caused_by:
  code: '142821'
  requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 29 апреля 2020 года № 45/388-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 мая 2020 года № 7082. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 53/538-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 13 января 2020 года № 42/349-VI «О бюджете поселка Ауэзова Жарминского района на 2020-2022 годы»
    kaz: Жарма аудандық мәслихатының 2020 жылғы 13 қаңтардағы № 42/349-VI «2020-2022 жылдарға арналған Жарма ауданы Әуезов кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142821/rus
