act_code: '129408'
requisite: Решение маслихата района Алтай Восточно-Казахстанской области от 26 февраля 2019 года № 45/2-VI. Зарегистрировано Управлением юстиции района Алтай Департамента юстиции Восточно-Казахстанской области 28 февраля 2019 года № 5-12-192. Утратило силу решением маслихата района Алтай Восточно-Казахстанской области от 26 июля 2022 года № 19/4-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат маслихата района Алтай»
  kaz: «Алтай ауданының мәслихат аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2019-02-26
approved_by:
- '157013000002'
version_date:
  kaz: 2019-02-26
  rus: 2019-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/129408/kaz/26.02.2019
  rus: https://zan.gov.kz/client/#!/doc/129408/rus/26.02.2019
