act_code: '168079'
requisite: Решение акима Акжарского сельского округа Тарбагатайского района Восточно-Казахстанской области от 19 мая 2022 года № 63. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 мая 2022 года № 28189
title:
  rus: О переименовании улицы села Акжар Акжарского сельского округа Тарбагатайского района
  kaz: Тарбағатай ауданы Ақжар ауылдық округі Ақжар ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-05-19
approved_by:
- '157017001002'
version_date:
  kaz: 2022-05-19
  rus: 2022-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/168079/kaz/19.05.2022
  rus: https://zan.gov.kz/client/#!/doc/168079/rus/19.05.2022
