act_code: '165873'
requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 28 декабря 2021 года № 15/12-VII
title:
  rus: О бюджете Сарыоленского сельского округа Курчумского района на 2022-2024 годы
  kaz: Сарыөлең ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '157016000002'
version_date:
  kaz: 2022-12-07
  rus: 2022-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/165873/kaz/07.12.2022
  rus: https://zan.gov.kz/client/#!/doc/165873/rus/07.12.2022
caused_by:
  code: '176041'
  requisite: Решение Курчумского районного маслихата Восточно-Казахстанской области от 7 декабря 2022 года № 28/12-VII
  title:
    rus: О внесении изменений в решение Курчумского районного маслихата от 28 декабря 2021 года №  15/12-VII «О бюджете Сарыоленского сельского округа  Курчумского  района на 2022-2024 годы»
    kaz: «Сарыөлең ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы» Күршім аудандық мәслихатының 2021 жылғы 28 желтоқсандағы № 15/12-VII шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/176041/rus
