act_code: '120673'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 20 марта 2018 года № 25-263/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 апреля 2018 года № 5604. Утратило силу решением Урджарского районного маслихата области Абай от 11 апреля 2023 года № 1-13/VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Урджарского районного маслихата»
  kaz: «Үржар аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-03-20
approved_by:
- '157019000002'
version_date:
  kaz: 2018-03-20
  rus: 2018-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/120673/kaz/20.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120673/rus/20.03.2018
