act_code: '120673'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 20 марта 2018 года № 25-263/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 апреля 2018 года № 5604. Утратило силу решением Урджарского районного маслихата области Абай от 11 апреля 2023 года № 1-13/VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Урджарского районного маслихата»
  kaz: «Үржар аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-03-20
approved_by:
- '157019000002'
version_date:
  kaz: 2022-04-06
  rus: 2022-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/120673/kaz/06.04.2022
  rus: https://zan.gov.kz/client/#!/doc/120673/rus/06.04.2022
caused_by:
  code: '166408'
  requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 6 апреля 2022 года № 14-228/VII. Утратило силу решением Урджарского районного маслихата области Абай от 11 апреля 2023 года № 1-13/VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Урджарского районного маслихата от 20 марта 2018 года № 25-263/VI «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Урджарского районного маслихата»
    kaz: «Үржар аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы» Үржар аудандық мәслихатының 2018  жылғы 20 наурыздағы № 25-263/VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166408/rus
