act_code: '8616'
requisite: Решение VIII сессии Восточно-Казахстанского областного маслихата II созыва от 27 марта 2001 года № 8/10-II. Зарегистрировано Управлением юстиции Восточно-Казахстанской области от 11 апреля 2001 года № 468. Утратило силу - решением Восточно-Казахстанского областного маслихата от 1 февраля 2006 года № 16/225-III
title:
  rus: О правилах работы мелкорозничой торговой сети
  kaz: Ұсақ бөлшек сауда жүйесі жұмысының ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2001-03-26
approved_by:
- '157000000002'
version_date:
  kaz: 2001-03-26
  rus: 2001-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/8616/kaz/26.03.2001
  rus: https://zan.gov.kz/client/#!/doc/8616/rus/26.03.2001
