act_code: '138792'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 10 января 2020 года № 43/300-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 января 2020 года № 6599. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/529-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете города Аягоза Аягозского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Аягөз ауданының Аягөз қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '157007000002'
version_date:
  kaz: 2020-12-08
  rus: 2020-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/138792/kaz/08.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138792/rus/08.12.2020
caused_by:
  code: '149662'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 8 декабря 2020 года № 54/506-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 декабря 2020 года № 7943. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/529-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 10 января 2020 года № 43/300-VI «О бюджете города Аягоза Аягозского района на 2020-2022 годы»
    kaz: Аягөз аудандық мәслихатының 2020 жылғы 10 қаңтардағы № 43/300-VІ «2020-2022 жылдарға арналған Аягөз ауданының Аягөз қаласының бюджеті туралы»  шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149662/rus
