act_code: '149684'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 30 ноября 2020 года № 49/5-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 декабря 2020 года № 7964
title:
  rus: О корректировке базовых ставок земельного налога
  kaz: Жер салығының базалық мөлшерлемелерін түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-30
approved_by:
- '157005000002'
version_date:
  kaz: 2022-08-31
  rus: 2022-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/149684/kaz/31.08.2022
  rus: https://zan.gov.kz/client/#!/doc/149684/rus/31.08.2022
caused_by:
  code: '171265'
  requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 31 августа 2022 года № 17/2-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 сентября 2022 года № 29415
  title:
    rus: О внесении изменений в решение Риддерского городского маслихата от 30 ноября 2020 года № 49/5-VI «О корректировке базовых ставок земельного налога»
    kaz: Риддер қалалық мәслихатының 2020 жылғы 30 қарашадағы № 49/5-VI «Жер салығының базалық мөлшерлемелерін түзету туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171265/rus
