act_code: '54310'
requisite: Шығыс Қазақстан облысы Зайсан аудандық мәслихатының 2010 жылғы 29 шілдедегі № 23-3/6 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Зайсан аудандық әділет басқармасында 2010 жылғы 3 қыркүйекте № 5-11-120 тіркелді. Күші жойылды - Шығыс Қазақстан облысы Зайсан аудандық мәслихатының 2012 жылғы 12 сәуірдегі № 3-3/17 шешімімен
title:
  rus: Зайсан ауданының аз қамтамасыз етілген отбасыларына (азаматтарына) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу ережесін бекіту туралы
  kaz: Зайсан ауданының аз қамтамасыз етілген отбасыларына (азаматтарына) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-29
approved_by:
- '157012000002'
version_date:
  kaz: 2010-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/54310/kaz/29.07.2010
