act_code: '52791'
requisite: Шығыс Қазақстан облысы Ұлан аудандық мәслихатының 2010 жылғы 15 сәуірдегі № 182 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Ұлан аудандық әділет басқармасында 2010 жылғы 21 мамырда № 5-17-130 тіркелді
title:
  rus: Ұлан ауданында жер учаскелерi үшiн төлемақының базалық ставкаларына түзету коэффициенттерiн бекіту туралы
  kaz: Ұлан ауданында жер учаскелерi үшiн төлемақының базалық ставкаларына түзету коэффициенттерiн бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-15
approved_by:
- '157018000002'
version_date:
  kaz: 2015-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/52791/kaz/05.03.2015
caused_by:
  code: '88461'
  requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 5 марта 2015 года № 239. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 1 апреля 2015 года № 3804. Утратило силу - решением Уланского районного маслихата Восточно-Казахстанской области от 14 февраля 2018 года № 165
  title:
    rus: О внесении изменений в решение Уланского районного маслихата от 15 апреля 2010 года № 182 "Об уточнении базовых ставок на земельный налог Уланского района"
    kaz: '"Ұлан ауданының жер салығының базалық ставкаларын түзету туралы" Ұлан аудандық мәслихатының 2010 жылғы 15 сәуірдегі № 182 шешімге өзгертулер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/88461/rus
