act_code: '52791'
requisite: Шығыс Қазақстан облысы Ұлан аудандық мәслихатының 2010 жылғы 15 сәуірдегі № 182 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Ұлан аудандық әділет басқармасында 2010 жылғы 21 мамырда № 5-17-130 тіркелді
title:
  rus: Ұлан ауданында жер учаскелерi үшiн төлемақының базалық ставкаларына түзету коэффициенттерiн бекіту туралы
  kaz: Ұлан ауданында жер учаскелерi үшiн төлемақының базалық ставкаларына түзету коэффициенттерiн бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-15
approved_by:
- '157018000002'
version_date:
  kaz: 2010-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/52791/kaz/15.04.2010
