act_code: '65338'
requisite: Решение маслихата Зыряновского района Восточно-Казахстанской области от 29 марта 2012 года № 2/8-V. Зарегистрировано управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 3 мая 2012 года за № 5-12-138. Утратило силу - решением маслихата Зыряновского района Восточно-Казахстанской области от 16 февраля 2015 года № 39/2-V
title:
  rus: О корректировке базовых налоговых ставок по Зыряновскому району
  kaz: Зырян ауданы бойынша базалық салық ставкаларын түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-03-29
approved_by:
- '157013000002'
version_date:
  kaz: 2012-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/65338/kaz/29.03.2012
