act_code: '39350'
requisite: Шығыс Қазақстан облысы Абай аудандық мәслихатының 2008 жылғы 18 сәуірдегі № 5-3 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Абай ауданындағы Әділет басқармасында 2008 жылғы 29 сәуірде № 5-5-78 тіркелді. Күші жойылды - Шығыс Қазақстан облысы Абай аудандық мәслихатының 2009 жылғы 21 сәуірдегі № 14-6 шешімімен
title:
  rus: Тұрғын үйді ұстауға және коммуналдық қызметке ақы төлеу үшін тұрғын үй жәрдемақыларын беру нұсқаулығы туралы
  kaz: Тұрғын үйді ұстауға және коммуналдық қызметке ақы төлеу үшін тұрғын үй жәрдемақыларын беру нұсқаулығы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-18
approved_by:
- '157006000002'
version_date:
  kaz: 2008-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/39350/kaz/18.04.2008
