act_code: '180176'
requisite: Решение маслихата района Алтай Восточно-Казахстанской области от 24 апреля 2023 года № 2/3-VIII. Отменен решением маслихата района Алтай Восточно-Казахстанской области от 21 августа 2025 года № 31/4-VIII (вводится в действие со дня принятия)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат маслихата района Алтай»
  kaz: «Алтай ауданының мәслихат аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-04-24
approved_by:
- '157013000002'
version_date:
  kaz: 2023-04-24
  rus: 2023-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/180176/kaz/24.04.2023
  rus: https://zan.gov.kz/client/#!/doc/180176/rus/24.04.2023
