act_code: '123506'
requisite: Решение Кокпектинского районного маслихата Восточно-Казахстанской области от 20 июня 2018 года № 23-6/6. Зарегистрировано Управлением юстиции Кокпектинского района Департамента юстиции Восточно-Казахстанской области 10 июля 2018 года № 5-15-118
title:
  rus: О повышении ставок единого земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения Кокпектинского района
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес пайдаланылмайтын Көкпекті ауданының ауыл шаруашылығы мақсатындағы жерлерге бірыңғай жер салығының базалық мөлшерлемелерін жоғарлату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-20
approved_by:
- '157015000002'
version_date:
  kaz: 2018-06-20
  rus: 2018-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/123506/kaz/20.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123506/rus/20.06.2018
