act_code: '715'
requisite: Решение Акима Восточно-Казахстанской области от 31 марта 1998 года № 491-к. Зарегистрировано Управлением юстиции Восточно-Казахстанской области 30 апреля 1998 года за № 10. Утратило силу - решением Акима Восточно-Казахстанской области № 691-к от 25 мая 1999 года
title:
  rus: О подготовке к работе в осенне-зимний период 1998-1999 г.г. объектов энергетики, соцкультбыта и жилищно-коммунального хозяйства области
  kaz: Облыстың энергетика, әлеуметтiк, мәдени-тұрмыстық және тұрғын үй-коммуналдық шаруашылығы объектiлерiн 1998-1999 жылдардағы күзгi-қысқы кездегi жұмысқа әзiрлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-03-30
approved_by:
- '157000000003'
version_date:
  kaz: 1998-03-30
  rus: 1998-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/715/kaz/30.03.1998
  rus: https://zan.gov.kz/client/#!/doc/715/rus/30.03.1998
