act_code: '107537'
requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 19 октября 2016 года № 7/46-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 ноября 2016 года № 4739. Утратило силу решением Курчатовского городского маслихата Восточно-Казахстанской области от от 29 декабря 2021 года № 12/87-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану
  kaz: Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өтеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-19
approved_by:
- '157004000002'
version_date:
  kaz: 2020-03-31
  rus: 2020-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/107537/kaz/31.03.2020
  rus: https://zan.gov.kz/client/#!/doc/107537/rus/31.03.2020
caused_by:
  code: '141911'
  requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 31 марта 2020 года № 38/296-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 апреля 2020 года № 6907. Утратило силу решением Курчатовского городского маслихата Восточно-Казахстанской области от от 29 декабря 2021 года № 12/87-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Курчатовского городского маслихата от 19 октября 2016 года № 7/46-VI «О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану»
    kaz: Курчатов қалалық мәслихатының 2016 жылғы 19 қазандағы № 7/46-VI «Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өтеу туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141911/rus
