act_code: '50181'
requisite: Решение Восточно-Казахстанского областного маслихата от 21 декабря 2009 года № 17/234-IV. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 22 января 2010 года за № 2524. Утратило силу - решением Восточно-Казахстанского областного маслихата от 12 апреля 2018 года № 19/220-VI
title:
  rus: О ставках платы за эмиссии в окружающую среду Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысының қоршаған ортаға эмиссияға төлемақы мөлшерлемелері
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '157000000002'
version_date:
  kaz: 2009-12-21
  rus: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/50181/kaz/21.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50181/rus/21.12.2009
