act_code: '85802'
requisite: Решение №28-322/V от 23.12.2014, Маслихат Урджарского района. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 08 января 2015 года № 3614. Утратило силу - решением маслихата Урджарского района Восточно-Казахстанской области от 23.12.2015 № 38-462/V.
title:
  rus: 'О бюджете  Урджарского  района  на 2015-2017 годы '
  kaz: '2015-2017 жылдарға  арналған   Үржар ауданының  бюджеті туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '157019000002'
version_date:
  kaz: 2014-12-23
  rus: 2014-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/85802/kaz/23.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85802/rus/23.12.2014
