act_code: '205575'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 30 декабря 2024 года № 194
title:
  rus: О бюджете сельских округов и поселков Уланского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ұлан ауданының ауылдық округтер мен кенттер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '157018000002'
version_date:
  kaz: 2025-05-16
  rus: 2025-05-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/205575/kaz/16.05.2025
  rus: https://zan.gov.kz/client/#!/doc/205575/rus/16.05.2025
caused_by:
  code: '210642'
  requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 16 мая 2025 года № 226
  title:
    rus: О внесении изменений в решение Уланского районного маслихата от 30 декабря 2024 года № 194 «О бюджете сельских округов и поселков Уланского района на 2025-2027 годы»
    kaz: Ұлан аудандық мәслихатының «2025-2027 жылдарға арналған Ұлан ауданының ауылдық округтер мен кенттер бюджеті туралы» 2024 жылдың 30 желтоқсандағы № 194 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210642/rus
