act_code: '151596'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 46/432-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 31 декабря 2020 года № 8287
title:
  rus: О бюджете Солдатовского сельского округа на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Солдатово ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-30
approved_by:
- '157014000002'
version_date:
  kaz: 2021-07-23
  rus: 2021-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/151596/kaz/23.07.2021
  rus: https://zan.gov.kz/client/#!/doc/151596/rus/23.07.2021
caused_by:
  code: '157338'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 23 июля 2021 года № 9/90-VII
  title:
    rus: О внесении изменений в решение Катон–Карагайского районного от 30 декабря 2020 года № 46/432 – VI «О бюджете Солдатовского сельского округа на 2021-2023 годы»
    kaz: Катонқарағай аудандық мәслихатының 2020 жылғы 30 желтоқсандағы № 46/432–VI «2021-2023 жылдарға арналған Солдатово ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157338/rus
