act_code: '5968'
requisite: Решение Акима Восточно-Казахстанской области от 6 апреля 2000 года № 837. Зарегистрировано управлением юстиции Восточно-Казахстанской обл. 13.04.2000 г. за № 294. Утратило силу в связи с истечением срока действия письмом акимата ВКО от 4 июля 2007 года № 6/3063
title:
  rus: О мерах по усилению противопожарной защиты лесов области и населенных пунктов
  kaz: О мерах по усилению противопожарной защиты лесов области и населенных пунктов
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-04-05
approved_by:
- '157000000003'
version_date:
  rus: 2001-02-26
source:
  rus: https://zan.gov.kz/client/#!/doc/5968/rus/26.02.2001
caused_by:
  code: '8306'
  requisite: Решение Акима Восточно-Казахстанской области от 26 февраля 2001 года № 996. Зарегистрировано управлением юстиции Восточно-Казахстанской области 28 февраля 2001 года за № 448. Утратило силу - в связи с истечением срока действия письмом акимата ВКО от 4 июля 2007 года № 6/3063
  title:
    rus: О внесении изменений в решение от 6 апреля 2000 г. № 837 "О мерах по усилению защиты лесов области и населенных пунктов"
    kaz: '"Облыс ормандары мен елді мекендерін өрттен қорғауды күшейту жөніндегі шаралар туралы" 2000 жылғы 6 сәуірдегі № 837 шешімге өзгертулер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/8306/rus
