act_code: '45706'
requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 23 апреля 2009 года № 18/136-IV. Зарегистрировано Управлением юстиции города Курчатова Департамента юстиции Восточно-Казахстанской области 8 мая 2009 года за № 5-3-75. Утратило силу решением Курчатовского городского маслихата Восточно-Казахстанской области от 21 декабря 2012 года № 10/73-V
title:
  rus: Об утверждении стоимости разовых талонов
  kaz: Біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-23
approved_by:
- '157004000002'
version_date:
  kaz: 2009-04-23
  rus: 2009-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/45706/kaz/23.04.2009
  rus: https://zan.gov.kz/client/#!/doc/45706/rus/23.04.2009
