act_code: '59935'
requisite: Решение акима Жана тилекского сельского округа Урджарского района Восточно-Казахстанской области от 18 июля 2011 года № 6. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 8 августа 2011 года за № 5-18-128. Утратило силу - решением акима Жана тилекского сельского округа Урджарского района ВКО от 29 ноября 2011 года № 11
title:
  rus: Об установлении ограничения в связи со вспышкой бруцеллеза мелкого  рогатого скота на территории Жана тилекского сельского округа
  kaz: Жаңа тілек ауылдық округі аймағында мүйізді ұсақ малдарынан бруцеллез індетінің шығуына байланысты шектеу қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-07-18
approved_by:
- '157019009001'
version_date:
  kaz: 2011-07-18
  rus: 2011-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/59935/kaz/18.07.2011
  rus: https://zan.gov.kz/client/#!/doc/59935/rus/18.07.2011
