act_code: '197464'
requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 4 июня 2024 года № 22/3-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 7 июня 2024 года № 9032-16
title:
  rus: Об определении размера и правил оказания жилищной помощи в городе Усть-Каменогорске
  kaz: Өскемен қаласында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-04
approved_by:
- '157002000002'
version_date:
  kaz: 2026-03-31
  rus: 2026-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/197464/kaz/31.03.2026
  rus: https://zan.gov.kz/client/#!/doc/197464/rus/31.03.2026
caused_by:
  code: '223465'
  requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 31 марта 2026 года № 43/2-VIII. Зарегистрировано в Министерстве юстиции Республики Казахстан 3 апреля 2026 года № 38295
  title:
    rus: О внесении изменений в решение Усть-Каменогорского городского маслихата от 4 июня 2024 года № 22/3-VIII «Об определении размера и правил оказания жилищной помощи в городе Усть-Каменогорске»
    kaz: «Өскемен қаласында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын айқындау туралы» Өскемен қалалық мәслихатының 2024 жылғы 4 маусымдағы № 22/3 VIII шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223465/rus
