act_code: '43397'
requisite: Шығыс Қазақстан облысы Күршім аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 10-3 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Күршім аудандық әділет басқармасында 2009 жылғы 8 қаңтарда № 5-14-76 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Күршім аудандық мәслихатының 2010 жылғы 11 қаңтардағы № 5 хаты
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '157016000002'
version_date:
  kaz: 2009-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43397/kaz/24.07.2009
caused_by:
  code: '47168'
  requisite: Шығыс Қазақстан облысы Күршім аудандық мәслихатының 2009 жылғы 24 шілдедегі № 15-6 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Күршім аудандық әділет басқармасында 2009 жылғы 3 тамызда № 5-14-87 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Күршім аудандық мәслихатының 2010 жылғы 11 қаңтардағы № 5 хаты
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" 2008 жылғы 26 желтоқсандағы № 10-3 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" 2008 жылғы 26 желтоқсандағы № 10-3 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/47168/rus
