act_code: '219589'
requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 19 декабря 2025 года № 40/8-VIII
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по городу Усть-Каменогорску
  kaz: Өскемен қаласы бойынша әлеуметтік көмек көрсетудің, мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2025-12-19
approved_by:
- '157002000002'
version_date:
  kaz: 2026-07-14
  rus: 2026-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/219589/kaz/14.07.2026
  rus: https://zan.gov.kz/client/#!/doc/219589/rus/14.07.2026
caused_by:
  code: '227865'
  requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 14 июля 2026 года № 48/2-VIII
  title:
    rus: О внесении изменений и дополнений в решение Усть-Каменогорского городского маслихата от 19 декабря 2025 года № 40/8-VIII «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по городу Усть-Каменогорску»
    kaz: «Өскемен қаласы бойынша әлеуметтік көмек көрсетудің, мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Өскемен қалалық мәслихатының 2025 жылғы 19 желтоқсандағы № 40/8-VIII шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/227865/rus
