act_code: '118044'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 28 декабря 2017 года № 18-2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 января 2018 года № 5428. Утратило силу решением Бородулихинского районного маслихата Восточно-Казахстанской области от 28 декабря 2018 года № 32-7-VI
title:
  rus: О бюджетах Бель-Агачского, Бородулихинского, Новопокровского, Новошульбинского, Переменовского сельских и Жезкентского поселкового округов Бородулихинского района на 2018 – 2020 годы
  kaz: 2018-2020 жылдарға арналған Бородулиха ауданының Белағаш, Бородулиха, Новопокровка, Новошульба, Переменовка ауылдық және Жезкент кенттік округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-28
approved_by:
- '157008000002'
version_date:
  kaz: 2018-05-29
  rus: 2018-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/118044/kaz/29.05.2018
  rus: https://zan.gov.kz/client/#!/doc/118044/rus/29.05.2018
caused_by:
  code: '122601'
  requisite: Решение маслихата Бородулихинского района Восточно-Казахстанской области от 29 мая 2018 года № 22-2-VI. Зарегистрировано Управлением юстиции Бородулихинского района Департамента юстиции Восточно-Казахстанской области 12 июня 2018 года № 5-8-158. Утратило силу решением Бородулихинского районного маслихата Восточно-Казахстанской области от 28 декабря 2018 года № 32-7-VI
  title:
    rus: О внесении изменений в решение Бородулихинского районного маслихата от 28 декабря 2017 года № 18-2-VI «О бюджетах Бель-Агачского, Бородулихинского, Новопокровского, Новошульбинского, Переменовского сельских и Жезкентского поселкового округов Бородулихинского района на 2018 – 2020 годы»
    kaz: «2018-2020 жылдарға арналған Бородулиха ауданының Белағаш, Бородулиха, Новопокровка, Новошульба, Переменовка ауылдық және Жезкент кенттік округтерінің бюджеттері туралы» Бородулиха аудандық мәслихатының 2017 жылғы 28 желтоқсандағы № 18-2-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122601/rus
