act_code: '2809'
requisite: Решение Акима Восточно-Казахстанской области от 4 мая 1999 года N 678. Зарегистрировано управлением юстиции Восточно-Казахстанской области 7 мая 1999 года за N 175. Утратило силу решением акима ВКО от 19 августа 2004 года N 94
title:
  rus: О порядке финансирования государственных предприятий и учреждений здравоохранения, оказывающих медицинские услуги в рамках государственного заказа
  kaz: Мемлекеттік тапсырыс шеңберінде медициналық қызмет көрсетуші мемлекеттік денсаулық сақтау кәсіпорындары мен мекемелерін қаржыландыру тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-05-03
approved_by:
- '157000000001'
version_date:
  kaz: 1999-05-03
  rus: 1999-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/2809/kaz/03.05.1999
  rus: https://zan.gov.kz/client/#!/doc/2809/rus/03.05.1999
