act_code: '138774'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 10 января 2020 года № 43/301-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 января 2020 года № 6581. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/530-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Актогайского поселкового округа Аягозского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Аягөз ауданының Ақтоғай кенттік округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '157007000002'
version_date:
  kaz: 2020-07-15
  rus: 2020-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/138774/kaz/15.07.2020
  rus: https://zan.gov.kz/client/#!/doc/138774/rus/15.07.2020
caused_by:
  code: '144965'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 15 июля 2020 года № 49/417-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 июля 2020 года № 7377. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/530-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 10 января 2020 года № 43/301-VI «О бюджете Актогайского поселкового округа Аягозского района на 2020-2022 годы»
    kaz: Аягөз аудандық мәслихатының 2020 жылғы 10 қаңтардағы № 43/301-VІ «2020-2022 жылдарға арналған Аягөз ауданының Ақтоғай кенттік округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144965/rus
