act_code: '70054'
requisite: Решение маслихата Урджарского района Восточно-Казахстанской области от 21 декабря 2012 года № 9-78/V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 января 2013 года № 2816. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 16 ноября 2018 года № 34-353/VI
title:
  rus: О социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алуға әлеуметтік көмек туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '157019000002'
version_date:
  kaz: 2018-03-12
  rus: 2018-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/70054/kaz/12.03.2018
  rus: https://zan.gov.kz/client/#!/doc/70054/rus/12.03.2018
caused_by:
  code: '119872'
  requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 12 марта 2018 года № 24-247/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 26 марта 2018 года № 5556. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 16 ноября 2018 года № 34-353/VI
  title:
    rus: О внесении изменения в решение Урджарского районного маслихата от 21 декабря 2012 года № 9-78/V «О социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах»
    kaz: «Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алуға әлеуметтік көмек туралы» Үржар аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 9-78/V шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/119872/rus
