act_code: '128304'
requisite: Решение акима Акшокинского сельского округа Урджарского района Восточно-Казахстанской области от 6 декабря 2018 года № 4. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 26 декабря 2018 года № 5-18-186
title:
  rus: О переименовании улиц села Подгорное Акшокинского сельского округа Урджарского района
  kaz: Үржар ауданы Ақшоқы ауылдық округі Подгорный ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-06
approved_by:
- '157019004002'
version_date:
  kaz: 2018-12-06
  rus: 2018-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/128304/kaz/06.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128304/rus/06.12.2018
