act_code: '215094'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 29 сентября 2025 года № 30/6-VIII
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твёрдых бытовых отходов по городу Риддеру
  kaz: Риддер қаласы бойынша халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-29
approved_by:
- '157005000002'
version_date:
  kaz: 2025-09-29
  rus: 2025-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/215094/kaz/29.09.2025
  rus: https://zan.gov.kz/client/#!/doc/215094/rus/29.09.2025
