act_code: '67527'
requisite: Решение Абайского районного маслихата Восточно-Казахстанской области от 21 августа 2012 года № 6-2. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 12 сентября 2012 года за № 2645. Утратило силу решением Абайского районного маслихата Восточно-Казахстанской области 22 июля 2014 года № 22/5-V
title:
  rus: Об оказании социальной помощи отдельным категориям нуждающихся граждан
  kaz: Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-08-21
approved_by:
- '157006000002'
version_date:
  kaz: 2012-08-21
  rus: 2012-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/67527/kaz/21.08.2012
  rus: https://zan.gov.kz/client/#!/doc/67527/rus/21.08.2012
