act_code: '43263'
requisite: Шығыс Қазақстан облысы Аягөз аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 01-02/12-2 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Аягөз аудандық әділет басқармасында 2009 жылғы 5 қаңтарда № 5-6-88 тіркелді. Күші жойылды - қабылданған мерзімінің бітуіне байланысты (Аягөз аудандық әділет басқармасының 2010 жылғы 09 ақпандағы № 1057 хаты)
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '157007000002'
version_date:
  kaz: 2009-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43263/kaz/24.11.2009
caused_by:
  code: '48865'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 26 октября 2009 года № 153. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 23 ноября 2009 года за № 3-12-101. Утратило силу решением Хромтауского районного маслихата Актюбинской области от 22 декабря 2011 года № 283
  title:
    rus: О внесений изменений в решение районного маслихата № 138 "Об утверждении Правил благоустройства территорий города Хромтау" от 24 июля 2009 года
    kaz: '"Хромтау қаласының аумағын көркейту Ережесін бекіту туралы" аудандық мәслихаттың 2009 жылдың 21 шілдесіндегі 138 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/48865/rus
