act_code: '43263'
requisite: Шығыс Қазақстан облысы Аягөз аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 01-02/12-2 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Аягөз аудандық әділет басқармасында 2009 жылғы 5 қаңтарда № 5-6-88 тіркелді. Күші жойылды - қабылданған мерзімінің бітуіне байланысты (Аягөз аудандық әділет басқармасының 2010 жылғы 09 ақпандағы № 1057 хаты)
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '157007000002'
version_date:
  kaz: 2009-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/43263/kaz/18.08.2009
caused_by:
  code: '47531'
  requisite: Шығыс Қазақстан облысы Аягөз аудандық мәслихатының 2009 жылғы 18 тамыздағы № 01-02/18-2 шешімі. Шығыс Қазақстан облысы Аягөз ауданының әділет басқармасында 2009 жылғы 18 тамызда № 5-6-96 тіркелді. Күші жойылды - қабылданған мерзімінің бітуіне байланысты (Аягөз аудандық әділет басқармасының 2010 жылғы 9 ақпандағы № 1057 хаты)
  title:
    rus: 2008 жылғы 24 желтоқсандағы № 01-02/12-2 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: 2008 жылғы 24 желтоқсандағы № 01-02/12-2 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47531/rus
