act_code: '62295'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 14 декабря 2011 года № 34/2-IV. Зарегистрировано управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 30 декабря 2011 года за № 5-9-159. Прекращено действие по истечении срока действия (письмо Глубоковского районного маслихата от 20 декабря 2012 года № 298)
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-14
approved_by:
- '157010000002'
version_date:
  kaz: 2012-12-07
  rus: 2012-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/62295/kaz/07.12.2012
  rus: https://zan.gov.kz/client/#!/doc/62295/rus/07.12.2012
caused_by:
  code: '69329'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 7 декабря 2012 года № 11/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 декабря 2012 года за № 2775. Прекращено действие по истечении срока действия (письмо Глубоковского районного маслихата от 20 декабря 2012 года № 298)
  title:
    rus: О внесении изменений в решение от 14 декабря 2011 года № 34/2-IV "О районном бюджете на 2012-2014 годы"
    kaz: '"2012-2014 жылдарға арналған аудандық бюджет туралы" 2011 жылғы 14 желтоқсандағы № 34/2-IV шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/69329/rus
