act_code: '114442'
requisite: Решение акима Тоскаинского сельского округа Курчумского района Восточно-Казахстанской области от 7 августа 2017 года № 01. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 4 сентября 2017 года № 5186. Утратило силу - решением акима Тоскаинского сельского округа Курчумского района Восточно-Казахстанской области от 22 февраля 2018 года № 1
title:
  rus: Об установлении ограничительных мероприятий в селе Шанагаты Тоскаинского сельского округа Курчумского района
  kaz: Күршім ауданы Төсқайың ауылдық округінің Шанағаты ауылына шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-08-07
approved_by:
- '157016012002'
version_date:
  kaz: 2017-08-07
  rus: 2017-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/114442/kaz/07.08.2017
  rus: https://zan.gov.kz/client/#!/doc/114442/rus/07.08.2017
