act_code: '41277'
requisite: Шығыс Қазақстан облысы Үржар аудандық мәслихатының 2008 жылғы 8 шілдедегі № 6-69-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Үржар аудандық Әділет басқармасында 2008 жылғы 12 тамызда № 5-18-67 тіркелді. Күші жойылды - Үржар аудандық мәслихатының 2012 жылғы 9 шілдедегі № 4-41/V шешімімен
title:
  rus: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау және фармацевтикалық, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу Нұсқаулықты бекіту туралы
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау және фармацевтикалық, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу Нұсқаулықты бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-07-08
approved_by:
- '157019000002'
version_date:
  kaz: 2008-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/41277/kaz/08.07.2008
