act_code: '127262'
requisite: Решение Восточно-Казахстанского областного маслихата от 13 декабря 2018 года № 25/280-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 декабря 2018 года № 5704
title:
  rus: Об областном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-13
approved_by:
- '157000000002'
version_date:
  kaz: 2019-06-14
  rus: 2019-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/127262/kaz/14.06.2019
  rus: https://zan.gov.kz/client/#!/doc/127262/rus/14.06.2019
caused_by:
  code: '132600'
  requisite: Решение Восточно-Казахстанского областного маслихата от 14 июня 2019 года № 30/329-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 июня 2019 года № 6024
  title:
    rus: О внесении изменений и дополнений в решение Восточно-Казахстанского областного маслихата от 13 декабря 2018 года № 25/280-VI «Об областном бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған облыстық бюджет туралы» Шығыс Қазақстан облыстық мәслихатының 2018 жылғы 13 желтоқсандағы № 25/280-VI шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132600/rus
