act_code: '127262'
requisite: Решение Восточно-Казахстанского областного маслихата от 13 декабря 2018 года № 25/280-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 декабря 2018 года № 5704
title:
  rus: Об областном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-13
approved_by:
- '157000000002'
version_date:
  kaz: 2019-04-12
  rus: 2019-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/127262/kaz/12.04.2019
  rus: https://zan.gov.kz/client/#!/doc/127262/rus/12.04.2019
caused_by:
  code: '130729'
  requisite: Решение Восточно-Казахстанского областного маслихата от 12 апреля 2019 года № 29/313-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 18 апреля 2019 года № 5871
  title:
    rus: О внесении изменений в решение Восточно-Казахстанского областного маслихата от 13 декабря 2018 года № 25/280-VI «Об областном бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған облыстық бюджет туралы» Шығыс Қазақстан облыстық мәслихатының 2018 жылғы 13 желтоқсандағы № 25/280-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130729/rus
