act_code: '138775'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 10 января 2020 года № 43/303-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 января 2020 года № 6582. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/532-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Акшатауского сельского округа Аягозского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Аягөз ауданының Ақшатау ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '157007000002'
version_date:
  kaz: 2020-12-08
  rus: 2020-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/138775/kaz/08.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138775/rus/08.12.2020
caused_by:
  code: '149811'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 8 декабря 2020 года № 54/509-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 декабря 2020 года № 7971. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/532-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 10 января 2020 года № 43/303-VI «О бюджете Акшатауского сельского округа Аягозского района на 2020-2022 годы»
    kaz: Аягөз аудандық мәслихатының 2020 жылғы 10 қаңтардағы № 43/303-VІ «2020-2022 жылдарға арналған Аягөз ауданының Ақшатау ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149811/rus
