act_code: '61436'
requisite: Решение акима Жогаргы Егинсуйского сельского округа Урджарского района Восточно-Казахстанской области от 28 октября 2011 года № 9. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 18 ноября 2011 года за № 5-18-134
title:
  rus: О переименовании улицы в селе Жогаргы Егинсу
  kaz: Жоғарғы Егінсу ауылындағы көшенің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-10-28
approved_by:
- '157019024001'
version_date:
  kaz: 2011-10-28
  rus: 2011-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/61436/kaz/28.10.2011
  rus: https://zan.gov.kz/client/#!/doc/61436/rus/28.10.2011
