act_code: '52326'
requisite: Шығыс Қазақстан облысы Аягөз аудандық мәслихатының 2010 жылғы 16 сәуірдегі № 01-02/24-13 шешімі. Шығыс Қазақстан облысы Аягөз ауданының Әділет басқармасында 2010 жылғы 12 мамырда № 5-6-106 тіркелді. Күші жойылды - Шығыс Қазақстан облысы Аягөз аудандық мәслихатының 2015 жылғы 25 ақпандағы № 33/234-V шешімімен
title:
  rus: Жерге салынатын базалық салық ставкаларын түзету туралы
  kaz: Жерге салынатын базалық салық ставкаларын түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-16
approved_by:
- '157007000002'
version_date:
  kaz: 2010-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/52326/kaz/16.04.2010
