act_code: '100602'
requisite: Решение Кокпектинского районного маслихата Восточно-Казахстанской области от 17 марта 2016 года № 45-2. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 29 марта 2016 года № 4449. Утратило силу решением Кокпектинского районного маслихата Восточно-Казахстанской области от 3 июля 2020 года № 48-5/2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций
  kaz: Жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-03-17
approved_by:
- '157015000002'
version_date:
  kaz: 2016-03-17
  rus: 2016-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/100602/kaz/17.03.2016
  rus: https://zan.gov.kz/client/#!/doc/100602/rus/17.03.2016
