act_code: '43478'
requisite: Шығыс Қазақстан облысы Тарбағатай аудандық мәслихатының 2008 жылғы 25 желтоқсандағы № 10-8 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Тарбағатай аудандық Әділет басқармасында 2009 жылғы 12 қаңтарда № 5-16-66 тіркелді. Күші жойылсын-Тарбағатай аудандық мәслихатының 2010 жылғы 27 шілдедегі № 23-8 шешімімен
title:
  rus: Тұрмысы төмен азаматтарға тұрғын үйді ұстауға және тұрғын үй-коммуналдық қызметке ақы төлеу үшін тұрғын үй жәрдемақыларын беру тәртібі туралы ережені бекіту туралы
  kaz: Тұрмысы төмен азаматтарға тұрғын үйді ұстауға және тұрғын үй-коммуналдық қызметке ақы төлеу үшін тұрғын үй жәрдемақыларын беру тәртібі туралы ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '157017000002'
version_date:
  kaz: 2008-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/43478/kaz/25.12.2008
