act_code: '121478'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 13 апреля 2018 года № 17/160-VI. Зарегистрировано Управлением юстиции Катон-Карагайского района Департамента юстиции Восточно-Казахстанской области 3 мая 2018 года № 5-13-135. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 8 июля 2020 года № 40/359-VI (вводится в действие с 01.01.2020)
title:
  rus: О ставках фиксированного налога
  kaz: Тіркелген салықтың мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-04-13
approved_by:
- '157014000002'
version_date:
  kaz: 2018-06-20
  rus: 2018-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/121478/kaz/20.06.2018
  rus: https://zan.gov.kz/client/#!/doc/121478/rus/20.06.2018
caused_by:
  code: '123362'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 20 июня 2018 года № 18/171-VI. Зарегистрировано Управлением юстиции Катон-Карагайского района Департамента юстиции Восточно-Казахстанской области 11 июля 2018 года № 5-13-143. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 8 июля 2020 года № 40/359-VI (вводится в действие с 01.01.2020)
  title:
    rus: О внесении изменений в решение Катон-Карагайского районного маслихата от 13 апреля 2018 года № 17/160-VІ «Об установлении единых ставок фиксированного налога по Катон-Карагайскому району»
    kaz: «Катонқарағай ауданы бойынша бірыңғай тіркелген салық мөлшерлемелерін белгілеу туралы» Катонқарағай аудандық мәслихатының 2018 жылғы 13 сәуірдегі № 17/160-VІ шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123362/rus
