act_code: '49720'
requisite: Шығыс Қазақстан облысы Үржар аудандық мәслихатының 2009 жылғы 28 желтоқсандағы № 16-166-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Үржар аудандық әділет басқармасында 2010 жылғы 6 қаңтарда № 5-18-88 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Үржар аудандық мәслихатының 2010 жылғы 31 желтоқсандағы № 159-03/IV хаты
title:
  rus: 2010-2012 жылдарға арналған аудан бюджеті туралы
  kaz: 2010-2012 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-28
approved_by:
- '157019000002'
version_date:
  kaz: 2010-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/49720/kaz/02.08.2010
caused_by:
  code: '54038'
  requisite: Шығыс Қазақстан облысы Үржар аудандық мәслихатының 2010 жылғы 2 тамыздағы № 21-223-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Үржар аудандық әділет басқармасында 2010 жылғы 12 тамызда № 5-18-100 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Үржар аудандық мәслихатының 2010 жылғы 31 желтоқсандағы № 159-03/IV хаты
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" 2009 жылғы 28 желтоқсандағы № 16-166-IV шешімге өзгерістер енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" 2009 жылғы 28 желтоқсандағы № 16-166-IV шешімге өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/54038/rus
