act_code: '65129'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 16 апреля 2012 года № 3/3-V. Зарегистрировано управлением юстиции города Риддера Департамента юстиции Восточно-Казахстанской области 2 мая 2012 года за № 5-4-168. Утратило силу - решением Риддерского городского маслихата Восточно-Казахстанской области от 16 февраля 2015 года № 31/2-V
title:
  rus: Об утверждении Правил о размере и порядке оказания жилищной помощи в городе Риддере
  kaz: Риддер қаласында тұрғын үй көмегін көрсету мөлшері және тәртібі туралы Қағиданы бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-04-16
approved_by:
- '157005000002'
version_date:
  kaz: 2013-12-20
  rus: 2013-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/65129/kaz/20.12.2013
  rus: https://zan.gov.kz/client/#!/doc/65129/rus/20.12.2013
caused_by:
  code: '76988'
  requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 20 декабря 2013 года N 23/4-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 23 января 2014 года № 3181. Утратило силу - решением Риддерского городского маслихата Восточно-Казахстанской области от 16 февраля 2015 года N 31/2-V
  title:
    rus: О внесении изменений в решение Риддерского городского маслихата от 16 апреля 2012 года № 3/3-V "Об утверждении Правил о размере и порядке оказания жилищной помощи в городе Риддере"
    kaz: '"Риддер қаласында тұрғын үй көмегiн көрсету мөлшерi және тәртiбi туралы Ереженi бекiту туралы" 2012 жылғы 16 сәуiрдегi № 3/3-V Риддер қалалық мәслихатының шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/76988/rus
