act_code: '138122'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 24 декабря 2019 года № 47-525/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 9 января 2020 года № 6485. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 22 декабря 2020 года № 57-742/VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Урджарского района на 2020-2022 годы
  kaz: Үржар ауданының 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '157019000002'
version_date:
  kaz: 2020-11-24
  rus: 2020-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/138122/kaz/24.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138122/rus/24.11.2020
caused_by:
  code: '149349'
  requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 24 ноября 2020 года № 56-727/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 4 декабря 2020 года № 7917. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 22 декабря 2020 года № 57-742/VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Урджарского районного маслихата от 24 декабря 2019 года № 47-525/VI «О бюджете Урджарского района на 2020-2022 годы»
    kaz: Үржар аудандық мәслихатының 2019 жылғы 24 желтоқсандағы № 47-525/VI «Үржар ауданының 2020-2022 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149349/rus
