act_code: '126299'
requisite: Решение акима Бескарагайского района Восточно-Казахстанской области от 23 ноября 2018 года № 4. Зарегистрировано Управлением юстиции Бескарагайского района Департамента юстиции Восточно-Казахстанской области 26 ноября 2018 года № 5-7-146
title:
  rus: Об образовании избирательных участков по Бескарагайскому району
  kaz: Бесқарағай ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-23
approved_by:
- '157009000003'
version_date:
  kaz: 2018-11-23
  rus: 2018-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/126299/kaz/23.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126299/rus/23.11.2018
