act_code: '87268'
requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 20 января 2015 года № 30-1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 февраля 2015 года № 3676
title:
  rus: Об определении размера и правил оказания жилищной помощи в Зайсанском районе Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысы Зайсан ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-01-20
approved_by:
- '157012000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/87268/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/87268/rus/27.12.2019
caused_by:
  code: '138528'
  requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 27 декабря 2019 года № 49-4/3. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 января 2020 года № 6509
  title:
    rus: О внесении изменения и дополнения в решение Зайсанского районного маслихата от 20 января 2015 года № 30-1 «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: Зайсан аудандық мәслихатының 2015 жылғы 20 қаңтардағы № 30-1 «Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы Қағиданы бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/138528/rus
