act_code: '121744'
requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 4 мая 2018 года № 20/153-VI. Зарегистрировано Управлением юстиции города Курчатова Департамента юстиции Восточно-Казахстанской области 15 мая 2018 года № 5-3-121
title:
  rus: Об установлении категорий автостоянок (паркингов) и увеличении базовых ставок налога на земли, выделенные под автостоянки (паркинги)
  kaz: Автотұрақтар (паркингтер) санаттарын белгілеу және автотұрақтарға (паркингтерге) бөлінген жерлерге базалық салық мөлшерлемелерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-04
approved_by:
- '157004000002'
version_date:
  kaz: 2018-05-04
  rus: 2018-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/121744/kaz/04.05.2018
  rus: https://zan.gov.kz/client/#!/doc/121744/rus/04.05.2018
