act_code: '139201'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 13 января 2020 года № 42/357-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 января 2020 года № 6641. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 53/546-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Калбатауского сельского округа Жарминского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Жарма ауданы Қалбатау ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '157011000002'
version_date:
  kaz: 2020-06-24
  rus: 2020-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/139201/kaz/24.06.2020
  rus: https://zan.gov.kz/client/#!/doc/139201/rus/24.06.2020
caused_by:
  code: '144435'
  requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 24 июня 2020 года № 47/426-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 2 июля 2020 года № 7252. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 53/546-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 13 января 2020 года № 42/357-VI «О бюджете Калбатауского сельского округа Жарминского района на 2020-2022 годы»
    kaz: Жарма аудандық мәслихатының 2020 жылғы 13 қантардағы № 42/357-VI «2020-2022 жылдарға арналған Жарма ауданы Қалбатау ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144435/rus
