act_code: '97720'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 23 декабря 2015 года № 47/258-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 12 января 2016 года № 4330. Утратило силу - решением маслихата города Семей Восточно-Казахстанской области от 21 декабря 2016 года № 9/66-VI
title:
  rus: О бюджете города Семей на 2016-2018 годы
  kaz: Семей қаласының 2016-2018 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '157003000002'
version_date:
  kaz: 2016-11-29
  rus: 2016-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/97720/kaz/29.11.2016
  rus: https://zan.gov.kz/client/#!/doc/97720/rus/29.11.2016
caused_by:
  code: '108050'
  requisite: Решение маслихата города Семей Восточно-Казахстанской области от 29 ноября 2016 года № 8/56-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 8 декабря 2016 года № 4764. Утратило силу - решением маслихата города Семей Восточно-Казахстанской области от 21 декабря 2016 года № 9/66-VI
  title:
    rus: О внесении изменений в решение маслихата города Семей от 23 декабря 2015 года № 47/258-V «О бюджете города Семей на 2016-2018 годы»
    kaz: Семей қаласы мәслихатының 2015 жылғы 23 желтоқсандағы № 47/258-V «Семей қаласының 2016-2018 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108050/rus
