act_code: '85885'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 24 декабря 2014 года № 28-2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 12 января 2015 года № 3616. Утратило силу решением маслихата Бородулихинского района Восточно-Казахстанской области от 23.12.2015 № 38-2-V
title:
  rus: О бюджете Бородулихинского района на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған  Бородулиха ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '157008000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/85885/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85885/rus/24.12.2014
