act_code: '166255'
requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 29 марта 2022 года № 17/5-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 апреля 2022 года № 27402
title:
  rus: Об утверждении Положения о награждении Почетной грамотой Бескарагайского района
  kaz: Бесқарағай ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-29
approved_by:
- '157009000002'
version_date:
  kaz: 2022-03-29
  rus: 2022-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/166255/kaz/29.03.2022
  rus: https://zan.gov.kz/client/#!/doc/166255/rus/29.03.2022
