act_code: '70162'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 21 декабря 2012 года № 11/9-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 января 2013 года за № 2824. Утратило силу - решением Риддерского городского маслихата от 16 апреля 2014 года № 26/9-V
title:
  rus: Об определении категорий физических лиц и перечня документов, необходимых для получения социальной помощи отдельным категориям нуждающихся граждан
  kaz: Мұқтаж азаматтардың кейбiр санаттарына әлеуметтiк көмек алу үшін жеке тұлғалардың санаттарын және қажетті құжаттардың тізімін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '157005000002'
version_date:
  kaz: 2013-03-19
  rus: 2013-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/70162/kaz/19.03.2013
  rus: https://zan.gov.kz/client/#!/doc/70162/rus/19.03.2013
caused_by:
  code: '71997'
  requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 19 марта 2013 года № 13/6-IV. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 апреля 2013 года № 2931. Утратило силу - решением Риддерского городского маслихата от 16 апреля 2014 года № 26/9-V
  title:
    rus: О внесении изменения в решение от 21 декабря 2012 года № 11/9-V "Об определении категорий физических лиц и перечня документов, необходимых для получения социальной помощи отдельным категориям нуждающихся граждан"
    kaz: 2012 жылғы 21 желтоқсандағы № 11/9-V "Мұқтаж азаматтардың кейбір санаттарына әлеуметтік көмек алу үшін жеке тұлғалардың санаттарын және қажетті құжаттардың тізімін белгілеу туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/71997/rus
