act_code: '24705'
requisite: Решение акима Жарминского района Восточно-Казахстанской области от 23 мая 2005 года № 7. Зарегистрировано управлением юстиции Жарминского района Департамента юстиции Восточно- Казахстанской области 6 июня 2005 года № 5-10-1
title:
  rus: О проведении призыва граждан на срочную военную службу в апреле-июне, октябре-декабре 2005 года
  kaz: Азаматтарды 2005 жылдың сәуір-маусым, қазан-желтоқсанында мерзімді әскери қызметке шақыруды өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-05-23
approved_by:
- '157011000003'
version_date:
  kaz: 2005-05-23
  rus: 2005-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/24705/kaz/23.05.2005
  rus: https://zan.gov.kz/client/#!/doc/24705/rus/23.05.2005
