act_code: '41445'
requisite: Шығыс Қазақстан облысы Зайсан аудандық мәслихатының 2008 жылғы 11 шілдедегі № 7-5/2 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Зайсан аудандық Әділет басқармасында 2008 жылғы 22 тамыздағы № 5-11-83 тіркелді
title:
  rus: Зайсан қаласының жер учаскелерін аймақтарға бөлу жобаларын бекіту туралы
  kaz: Зайсан қаласының жер учаскелерін аймақтарға бөлу жобаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-07-11
approved_by:
- '157012000002'
version_date:
  kaz: 2008-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/41445/kaz/11.07.2008
