act_code: '131340'
requisite: Решение акима Шемонаихинского района Восточно-Казахстанской области от 4 мая 2019 года № 02. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 6 мая 2019 года № 5925. Утратило силу решением акима Шемонаихинского района Восточно-Казахстанской области от 28 октября 2019 года № 03 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков по Шемонаихинскому району
  kaz: Шемонаиха ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-04
approved_by:
- '157020000003'
version_date:
  kaz: 2019-05-04
  rus: 2019-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/131340/kaz/04.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131340/rus/04.05.2019
