act_code: '112141'
requisite: Решение акима Биржанского сельского округа Зайсанского района Восточно-Казахстанской области от 30 ноября 2015 года № 2
title:
  rus: О признании утратившим силу решение акима Биржанского сельского округа «Об установлении ограничительных мероприятий в селе Куаныш Биржанского сельского округа» № 1 от 31 октября 2014 года
  kaz: Біржан ауылдық округі әкімінің 2014 жылғы 31 қазандағы «Біржан ауылдық округіндегі Қуаныш ауылында шектеу іс-шараларын белгілеу туралы» № 1 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-30
approved_by:
- '157012006002'
version_date:
  kaz: 2015-11-30
  rus: 2015-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/112141/kaz/30.11.2015
  rus: https://zan.gov.kz/client/#!/doc/112141/rus/30.11.2015
