act_code: '125794'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 25 октября 2018 года № 29/7-VI. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 2 ноября 2018 года № 5-19-193. Утратило силу решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 29 марта 2024 года № 15/4-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Шемонаихинском районе
  kaz: Шемонаиха ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-10-25
approved_by:
- '157020000002'
version_date:
  kaz: 2022-10-10
  rus: 2022-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/125794/kaz/10.10.2022
  rus: https://zan.gov.kz/client/#!/doc/125794/rus/10.10.2022
caused_by:
  code: '172924'
  requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 10 октября 2022 года № 24/3-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 октября 2022 года № 30188. Утратило силу решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 29 марта 2024 года № 15/4-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Шемонаихинского районного маслихата от 25 октября 2018 года № 29/7-VI «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: Шемонаиха аудандық мәслихатының 2018 жылғы 25 қазандағы № 29/7-VІ «Тұрғын үй көмегiн көрсетудiң мөлшерi мен тәртiбiн айқындау қағидаларын бекiту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172924/rus
