act_code: '85550'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 23 декабря 2014 года N 28/206-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 декабря 2014 года N 3607. Утратило силу - решением маслихата Катон-Каргайского района Восточно-Казахстанской области от 23.12.2015 № 35/274-V
title:
  rus: О бюджете Катон-Карагайского района на 2015-2017 годы
  kaz: Катонқарағай ауданының 2015-2017 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '157014000002'
version_date:
  kaz: 2015-04-07
  rus: 2015-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/85550/kaz/07.04.2015
  rus: https://zan.gov.kz/client/#!/doc/85550/rus/07.04.2015
caused_by:
  code: '89171'
  requisite: 'Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 07 апреля 2015 года N 30/234-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 апреля 2015 года N 3878. Утратило силу - решением маслихата Катон-Каргайского района Восточно-Казахстанской области от 23.12.2015 № 35/274-V '
  title:
    rus: 'О внесении изменений в решение Катон-Карагайского районного маслихата от 23 декабря 2014 года № 28/206-V «О бюджете Катон-Карагайского района на 2015-2017 годы» '
    kaz: '«Катонқарағай  ауданының 2015-2017 жылдарға  арналған бюджеті туралы» Катонқарағай аудандық мәслихатының 2014 жылғы 23 желтоқсандағы № 28/206–V шешіміне өзгерістер енгізу туралы   '
  link: https://zan.gov.kz/client/#!/doc/89171/rus
