act_code: '43477'
requisite: Шығыс Қазақстан облысы Тарбағатай аудандық мәслихатының 2008 жылғы 25 желтоқсандағы № 10-2 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Тарбағатай аудандық әділет басқармасында 2008 жылғы 26 желтоқсанда № 5-16-65 тіркелді. Күші жойылды - Тарбағатай аудандық мәслихатының 2010 жылғы 21 сәуірдегі № 46 хаты
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '157017000002'
version_date:
  kaz: 2009-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43477/kaz/23.10.2009
caused_by:
  code: '48367'
  requisite: Шығыс Қазақстан облысы Тарбағатай аудандық мәслихатының 2009 жылғы 23 қазандағы № 16-5 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Тарбағатай аудандық әділет басқармасында 2009 жылғы 28 қазанда № 5-16-84 тіркелді. Күші жойылды - Тарбағатай аудандық мәслихатының 2010 жылғы 5 сәуірдегі № 31 хаты
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" 2008 жылғы 25 желтоқсандағы № 10-2 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" 2008 жылғы 25 желтоқсандағы № 10-2 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/48367/rus
