act_code: '86186'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 23 декабря 2014 года № 28/214-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 января 2015 года № 3643. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 12 апреля 2024 года № 15/180-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Катон-Карагайском районе
  kaz: Катонқарағай ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '157014000002'
version_date:
  kaz: 2015-04-07
  rus: 2015-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/86186/kaz/07.04.2015
  rus: https://zan.gov.kz/client/#!/doc/86186/rus/07.04.2015
caused_by:
  code: '89686'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 7 апреля 2015 года № 30/237-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 апреля 2015 года № 3919. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 12 апреля 2024 года № 15/180-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Катон-Карагайского районного маслихата № 28/214-V от 23 декабря 2014 года «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: «Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау қағидасын бекіту туралы» Катонқарағай  аудандық мәслихатының 2014 жылғы 23 желтоқсандағы № 28/214-V  шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/89686/rus
