act_code: '86186'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 23 декабря 2014 года № 28/214-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 января 2015 года № 3643. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 12 апреля 2024 года № 15/180-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Катон-Карагайском районе
  kaz: Катонқарағай ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '157014000002'
version_date:
  kaz: 2018-10-19
  rus: 2018-10-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/86186/kaz/19.10.2018
  rus: https://zan.gov.kz/client/#!/doc/86186/rus/19.10.2018
caused_by:
  code: '126007'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 19 октября 2018 года № 21/187-VI. Зарегистрировано Управлением юстиции Катон-Карагайского района Департамента юстиции Восточно-Казахстанской области 20 ноября 2018 года № 5-13-151. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 12 апреля 2024 года № 15/180-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Катон-Карагайского районного маслихата от 23 декабря 2014 года № 28/214-V «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: «Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау қағидасын бекіту туралы» Катонқарағай аудандық мәслихатының 2014 жылғы 23 желтоқсандағы № 28/214-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126007/rus
