act_code: '86186'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 23 декабря 2014 года № 28/214-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 января 2015 года № 3643. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 12 апреля 2024 года № 15/180-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Катон-Карагайском районе
  kaz: Катонқарағай ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '157014000002'
version_date:
  kaz: 2023-04-28
  rus: 2023-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/86186/kaz/28.04.2023
  rus: https://zan.gov.kz/client/#!/doc/86186/rus/28.04.2023
caused_by:
  code: '181399'
  requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 28 апреля 2023 года № 3/37-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 16 мая 2023 года № 8846-16. Утратило силу решением Катон-Карагайского районного маслихата Восточно-Казахстанской области от 12 апреля 2024 года № 15/180-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Катон-Карагайского районного маслихата от 23 декабря 2014 года № 28/214-V «Об определении размера и порядка оказания жилищной помощи в Катон-Карагайском районе»
    kaz: Катонқарағай аудандық  мәслихатының 2014 жылғы 23 желтоқсандағы № 28/214-V «Катонқарағай ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгеріс  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181399/rus
