act_code: '109210'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 30 ноября 2016 года № 7/5-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 28 декабря 2016 года № 4794. Утратило силу - решением Глубоковского районного маслихата Восточно-Казахстанской области от 15 марта 2018 года № 20/13-VI
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланымайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-11-30
approved_by:
- '157010000002'
version_date:
  kaz: 2016-11-30
  rus: 2016-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/109210/kaz/30.11.2016
  rus: https://zan.gov.kz/client/#!/doc/109210/rus/30.11.2016
