act_code: '3334'
requisite: Решение Акима Восточно-Казахстанской области от 31 мая 1999 года N 692. Зарегистрировано управлением юстиции Восточно-Казахстанской области 3 июня 1999 года за N 190. Утратило силу решением акима ВКО от 10 января 2007 года N 31
title:
  rus: О мерах по усилению контроля за использованием и охраной сельскохозяйственных земель области
  kaz: Облыстың ауылшаруашылығы жерлерін қорғау мен пайдаланылуына бақылау жасауды күшейту жөніндегі шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-05-30
approved_by:
- '157000000001'
version_date:
  kaz: 1999-05-30
  rus: 1999-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/3334/kaz/30.05.1999
  rus: https://zan.gov.kz/client/#!/doc/3334/rus/30.05.1999
