act_code: '151241'
requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 29 декабря 2020 года № 62/11-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 декабря 2020 года № 8109
title:
  rus: О бюджете Ерназаровского сельского округа на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Ерназар ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '157009000002'
version_date:
  kaz: 2021-09-21
  rus: 2021-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/151241/kaz/21.09.2021
  rus: https://zan.gov.kz/client/#!/doc/151241/rus/21.09.2021
caused_by:
  code: '159047'
  requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 21 сентября 2021 года № 9/11-VII
  title:
    rus: О внесении изменений в решение Бескарагайского районного маслихата от 29 декабря 2020 года № 62/11-VI «О бюджете Ерназаровского сельского округа на 2021-2023 годы»
    kaz: Бесқарағай аудандық мәслихатының 2020 жылғы 29 желтоқсандағы № 62/11-VI «2021-2023 жылдарға арналған Ерназар ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159047/rus
