act_code: '66371'
requisite: Решение акима Парыгинского сельского округа Зыряновского района Восточно-Казахстанской области от 1 июня 2012 года № 1. Зарегистрировано управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 20 июня 2012 года за № 5-12-143
title:
  rus: О присвоении наименований улицам поселений Бобровка и Теплый Ключ Парыгинского сельского округа Зыряновского района Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысының Зырян ауданы Парыгино селолық округінің Бобровка және Теплый Ключ елді мекендерінің көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-06-01
approved_by:
- '157013008002'
version_date:
  kaz: 2012-06-01
  rus: 2012-06-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/66371/kaz/01.06.2012
  rus: https://zan.gov.kz/client/#!/doc/66371/rus/01.06.2012
