act_code: '39536'
requisite: Решение акима Глубоковского района Восточно-Казахстанской области от 19 марта 2008 года № 10. Зарегистрировано Управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 24 апреля 2008 года № 5-9-81. Утратило силу в связи с истечением срока действия решения на основании письма аппарата акима Глубоковского района от 13 апреля 2009 года № 1388-02-11
title:
  rus: О проведении учета налога на имущество земельного налога, налога на транспорт физических лиц на 2008 год
  kaz: О проведении учета налога на имущество земельного налога, налога на транспорт физических лиц на 2008 год
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-19
approved_by:
- '157010000003'
version_date:
  rus: 2008-03-19
source:
  rus: https://zan.gov.kz/client/#!/doc/39536/rus/19.03.2008
