act_code: '4569'
requisite: Решение Акима Восточно-Казахстанской области от 8 ноября 1999 года № 775. Зарегистрировано управлением юстиции Восточно-Казахстанской области 15 ноября 1999 года за № 245. Утратило силу решением акима ВКО от 19 августа 2004 года № 94
title:
  rus: О мерах по обеспечению теплоснабжения поселка Первомайский
  kaz: Первомайскі кентін жылумен қамтамасыз ету жөніндегі шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-11-08
approved_by:
- '157000000003'
version_date:
  kaz: 1999-11-08
  rus: 1999-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/4569/kaz/08.11.1999
  rus: https://zan.gov.kz/client/#!/doc/4569/rus/08.11.1999
