act_code: '125179'
requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 14 сентября 2018 года № 24/191-VI. Зарегистрировано Управлением юстиции города Курчатова Департамента юстиции Восточно-Казахстанской области 12 октября 2018 года № 5-3-130. Утратило силу решением Курчатовского городского маслихата области Абай от 30 ноября 2023 года № 12/72-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в городе Курчатов
  kaz: Курчатов қаласында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-09-14
approved_by:
- '157004000002'
version_date:
  kaz: 2020-03-31
  rus: 2020-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/125179/kaz/31.03.2020
  rus: https://zan.gov.kz/client/#!/doc/125179/rus/31.03.2020
caused_by:
  code: '141909'
  requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 31 марта 2020 года № 38/297-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 апреля 2020 года № 6906. Утратило силу решением Курчатовского городского маслихата области Абай от 30 ноября 2023 года № 12/72-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Курчатовского городского маслихата от 14 сентября 2018 года № 24/191-VI «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: Курчатов қалалық мәслихатының 2018 жылғы 14 қыркүйектегі № 24/191-VI «Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу қағидасы туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141909/rus
