act_code: '54223'
requisite: Шығыс Қазақстан облысы Күршім ауданы Күршім ауылдық округінің 2010 жылғы 14 тамыздағы № 1 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Күршім аудандық Әділет басқармасында 2010 жылғы 26 тамызда № 5-14-112 тіркелді
title:
  rus: Күршім ауылының көшелерінің атауын өзгерту туралы
  kaz: Күршім ауылының көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-14
approved_by:
- '157016001002'
version_date:
  kaz: 2010-08-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/54223/kaz/14.08.2010
