act_code: '198585'
requisite: Решение  маслихата района Үлкен Нарын Восточно-Казахстанской области от 4 июля 2024 года № 4/23-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 июля 2024 года № 9053-16
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-04
approved_by:
- '157022000002'
version_date:
  kaz: 2024-07-04
  rus: 2024-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/198585/kaz/04.07.2024
  rus: https://zan.gov.kz/client/#!/doc/198585/rus/04.07.2024
