act_code: '166249'
requisite: Решение маслихата Бородулихинского района Восточно-Казахстанской области от 29 марта 2021 года № 13-11-VII
title:
  rus: О бюджете Кунарлинского сельского округа Бородулихинского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Бородулиха ауданы Құнарлы ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '157008000002'
version_date:
  kaz: 2022-12-12
  rus: 2022-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/166249/kaz/12.12.2022
  rus: https://zan.gov.kz/client/#!/doc/166249/rus/12.12.2022
caused_by:
  code: '176000'
  requisite: Решение Бородулихинского районного маслихата области Абай от 12 декабря 2022 года № 24-11-VII
  title:
    rus: О внесении изменений в решение Бородулихинского районного маслихата от 29 декабря 2021 года № 13-11-VII «О бюджете Кунарлинского сельского округа Бородулихинского района на 2022-2024 годы»
    kaz: Бородулиха аудандық мәслихатының 2021 жылғы 29 желтоқсандағы № 13-11-VII «2022-2024 жылдарға арналған Бородулиха ауданы Құнарлы ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/176000/rus
