act_code: '151248'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 28 декабря 2020 года № 417. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 декабря 2020 года № 8112
title:
  rus: О бюджете Уланского района на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Ұлан ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-28
approved_by:
- '157018000002'
version_date:
  kaz: 2021-06-30
  rus: 2021-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/151248/kaz/30.06.2021
  rus: https://zan.gov.kz/client/#!/doc/151248/rus/30.06.2021
caused_by:
  code: '156927'
  requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 30 июня 2021 года № 57. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 июля 2021 года № 23474
  title:
    rus: О внесении изменений в решение Уланского районного маслихата «О бюджете Уланского района на 2021-2023 годы» от 28 декабря 2020 года № 417
    kaz: Ұлан аудандық мәслихатының 2020 жылғы 28 желтоқсандағы № 417 «2021-2023 жылдарға арналған Ұлан ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156927/rus
