act_code: '198753'
requisite: Решение  маслихата района Үлкен Нарын Восточно-Казахстанской области от 5 июля 2024 года № 4/21-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 12 июля 2024 года № 9055-16
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в районе Үлкен Нарын
  kaz: Үлкен Нарын ауданында  тұрғын үй көмегін көрсетудің мөлшері мен қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-05
approved_by:
- '157022000002'
version_date:
  kaz: 2025-10-24
  rus: 2025-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/198753/kaz/24.10.2025
  rus: https://zan.gov.kz/client/#!/doc/198753/rus/24.10.2025
caused_by:
  code: '216125'
  requisite: Решение маслихата района Үлкен Нарын Восточно-Казахстанской области от 24 октября 2025 года № 16/173-VIII. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 октября 2025 года № 37234
  title:
    rus: О внесении изменений  в решение маслихата района Үлкен Нарын от 5 июля 2024 года № 4/21-VIII «Об определении размера и порядка оказания жилищной помощи в районе Үлкен Нарын»
    kaz: Үлкен Нарын ауданы мәслихатының 2024 жылғы 5 шілдедегі № 4/21-VIII «Үлкен Нарын ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер   енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/216125/rus
