act_code: '86169'
requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 23 декабря 2014 года № 34/5-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 января 2015 года № 3629.  Утратило силу решением Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 31 июля 2018 года № 32/3-VI
title:
  rus: Об утверждении Правил определения размера и порядка оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-12-23
approved_by:
- '157002000002'
version_date:
  kaz: 2015-02-27
  rus: 2015-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/86169/kaz/27.02.2015
  rus: https://zan.gov.kz/client/#!/doc/86169/rus/27.02.2015
caused_by:
  code: '87787'
  requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 27 февраля 2015 года № 35/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 марта 2015 года № 3762. Утратило силу решением Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 31 июля 2018 года № 32/3-VI
  title:
    rus: О внесении изменений в решение Усть-Каменогорского городского маслихата от 23 декабря 2014 года № 34/5-V «Об утверждении Правила определения размера и порядка оказания жилищной помощи»
    kaz: Өскемен қалалық мәслихатының «Тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау қағидасын бекіту туралы» 2014 жылғы 23 желтоқсандағы № 34/5-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87787/rus
