act_code: '127565'
requisite: Решение акима Каракольского сельского округа Урджарского района Восточно-Казахстанской области от 13 декабря 2018 года № 18. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 24 декабря 2018 года № 5-18-185
title:
  rus: О переименовании улицы села Каракол Каракольского сельского округа Урджарского района
  kaz: Үржар ауданы Қарақол ауылдық округі Қарақол ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-13
approved_by:
- '157019019002'
version_date:
  kaz: 2018-12-13
  rus: 2018-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/127565/kaz/13.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127565/rus/13.12.2018
