act_code: '141608'
requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 27 марта 2020 года № 54/4-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 9 апреля 2020 года № 6875
title:
  rus: Об установлении повышенных должностных окладов и тарифных ставок
  kaz: Жоғарылатылған лауазымдық айлықақылар мен тарифтiк мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-27
approved_by:
- '157002000002'
version_date:
  kaz: 2020-12-31
  rus: 2020-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/141608/kaz/31.12.2020
  rus: https://zan.gov.kz/client/#!/doc/141608/rus/31.12.2020
caused_by:
  code: '152317'
  requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 31 декабря 2020 года № 64/3-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 6 января 2021 года № 8320
  title:
    rus: О внесении изменений в решение Усть-Каменогорского городского маслихата от 27 марта 2020 года № 54/4-VI «Об  установлении повышенных должностных окладов и тарифных ставок»
    kaz: Өскемен қалалық мәслихатының 2020 жылғы 27 наурыздағы № 54/4-VI «Жоғарылатылған лауазымдық айлықақылар мен тарифтiк мөлшерлемелер белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/152317/rus
