act_code: '167780'
requisite: Решение акима поселка Суыкбулак Жарминского района Восточно-Казахстанской области от 4 мая 2022 года № 4. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 мая 2022 года № 28022. Утратило силу решением акима поселка Суыкбулак Жарминского района области Абай от 24 января 2023 года № 2 (вводится в действие со дня его подписания)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-05-04
approved_by:
- '157011018001'
version_date:
  kaz: 2022-05-04
  rus: 2022-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/167780/kaz/04.05.2022
  rus: https://zan.gov.kz/client/#!/doc/167780/rus/04.05.2022
