act_code: '27940'
requisite: Решение акима Глубоковского района Восточно-Казахстанской области от 11 мая 2006 года № 426. Зарегистрировано Управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 22 мая 2006 года № 5-9-36. Утратило силу решением акима Глубоковского района от 17 апреля 2007 года № 2
title:
  rus: Об организации и проведении учебно-полевых сборов
  kaz: Об организации и проведении учебно-полевых сборов
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-05-11
approved_by:
- '157010000003'
version_date:
  rus: 2006-05-11
source:
  rus: https://zan.gov.kz/client/#!/doc/27940/rus/11.05.2006
