act_code: '2853'
requisite: Решение Акима Восточно-Казахстанской области от 4 декабря 1998 года № 615. Зарегистрировано управлением юстиции Восточно-Казахстанской области 7 декабря 1998 года за № 117. Утратило силу решением акима Восточно-Казахстанской области от 24 сентября 2004 года № 100
title:
  rus: Об утверждении Земельного баланса на 1998 год
  kaz: 1998 жылға Жер балансын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-12-04
approved_by:
- '157000000001'
version_date:
  kaz: 1998-12-04
  rus: 1998-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/2853/kaz/04.12.1998
  rus: https://zan.gov.kz/client/#!/doc/2853/rus/04.12.1998
