act_code: '55391'
requisite: Решение акима Каменевского сельского округа Шемонаихинского района Восточно-Казахстанской области от 27 октября 2010 года № 05. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 15 ноября 2010 года за № 5-19-133
title:
  rus: О переименовании улицы села Рассыпное Каменевского сельского округа
  kaz: Каменев селолық округінің Рассыпное селосындағы көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-27
approved_by:
- '157020004002'
version_date:
  kaz: 2010-10-27
  rus: 2010-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/55391/kaz/27.10.2010
  rus: https://zan.gov.kz/client/#!/doc/55391/rus/27.10.2010
