act_code: '151101'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 8 декабря 2020 года № 54/505-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 декабря 2020 года № 8148. Утратило силу решением Аягозского районного маслихата области Абай от 16 апреля 2024 года № 12/212-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и  порядка оказания жилищной помощи в Аягозском районе
  kaz: Аягөз ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-12-08
approved_by:
- '157007000002'
version_date:
  kaz: 2022-09-28
  rus: 2022-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/151101/kaz/28.09.2022
  rus: https://zan.gov.kz/client/#!/doc/151101/rus/28.09.2022
caused_by:
  code: '172624'
  requisite: Решение Аягозского районного маслихата области Абай от 28 сентября 2022 года № 17/321-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 4 октября 2022 года № 29993. Утратило силу решением Аягозского районного маслихата области Абай от 16 апреля 2024 года № 12/212-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 8 декабря 2020 года № 54/505-VІ «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: Аягөз аудандық мәслихатының «Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау Қағидаларын бекіту туралы» 2020 жылғы 8 желтоқсандағы № 54/505-VІ  шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172624/rus
