act_code: '151101'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 8 декабря 2020 года № 54/505-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 декабря 2020 года № 8148. Утратило силу решением Аягозского районного маслихата области Абай от 16 апреля 2024 года № 12/212-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и  порядка оказания жилищной помощи в Аягозском районе
  kaz: Аягөз ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-12-08
approved_by:
- '157007000002'
version_date:
  kaz: 2023-12-07
  rus: 2023-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/151101/kaz/07.12.2023
  rus: https://zan.gov.kz/client/#!/doc/151101/rus/07.12.2023
caused_by:
  code: '190271'
  requisite: Решение Аягозского районного маслихата области Абай от 7 декабря 2023 года № 9/138-VIII. Зарегистрировано Департаментом юстиции области Абай 14 декабря 2023 года № 190-18. Утратило силу решением Аягозского районного маслихата области Абай от 16 апреля 2024 года № 12/212-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 8 декабря 2020 года № 54/505-VІ «Об определении размера и порядка оказания жилищной помощи в Аягозском районе»
    kaz: Аягөз аудандық  мәслихатының 2020 жылғы 8 желтоқсандағы № 54/505-VІ «Аягөз ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190271/rus
