act_code: '151101'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 8 декабря 2020 года № 54/505-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 декабря 2020 года № 8148. Утратило силу решением Аягозского районного маслихата области Абай от 16 апреля 2024 года № 12/212-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и  порядка оказания жилищной помощи в Аягозском районе
  kaz: Аягөз ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-12-08
approved_by:
- '157007000002'
version_date:
  kaz: 2023-04-28
  rus: 2023-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/151101/kaz/28.04.2023
  rus: https://zan.gov.kz/client/#!/doc/151101/rus/28.04.2023
caused_by:
  code: '181022'
  requisite: Решение Аягозского районного маслихата области Абай от 28 апреля 2023 года № 2/14-VIII. Зарегистрировано Департаментом юстиции области Абай 10 мая 2023 года № 67-18. Утратило силу решением Аягозского районного маслихата области Абай от 16 апреля 2024 года № 12/212-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 8 декабря 2020 года № 54/505-VІ «Об определении размера и порядка оказания жилищной помощи в Аягозском районе»
    kaz: Аягөз аудандық мәслихатының «Аягөз ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» 2020 жылғы 8 желтоқсандағы № 54/505-VІ шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181022/rus
