act_code: '9626'
requisite: Решение X сессии Восточно-Казахстанского областного маслихата от 15 июня 2001 года № 10/7-II. Зарегистрировано Управлением юстиции Восточно-Казахстанской области 17 июля 2001 года за № 526. Утратило силу - решением XIII сессии Восточно-Казахстанского областного маслихата от 18 октября 2005 года № 13/190-III
title:
  rus: Об утверждении Правил благоустройства, обеспечения санитарного состояния, охраны земель и зеленых насаждений в городах, поселках и селах Восточно-Казахстанской области
  kaz: '"Шығыс Қазақстан облысының қалаларында, кенттері мен селоларында көркейту, санитарлық жағдайды, жер мен жасыл ағаштарды қорғауды қамтамасыз етудің Ережелерін" бекіту туралы'
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2001-06-14
approved_by:
- '157000000002'
version_date:
  kaz: 2001-06-14
  rus: 2001-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/9626/kaz/14.06.2001
  rus: https://zan.gov.kz/client/#!/doc/9626/rus/14.06.2001
