act_code: '80086'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 21 апреля 2014 года № 26/5-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 мая 2014 года № 3337. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 18 сентября 2019 года № 34/8-VI
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-04-21
approved_by:
- '157010000002'
version_date:
  kaz: 2018-06-25
  rus: 2018-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/80086/kaz/25.06.2018
  rus: https://zan.gov.kz/client/#!/doc/80086/rus/25.06.2018
caused_by:
  code: '123443'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 25 июня 2018 года № 23/7-VI. Зарегистрировано Управлением юстиции Глубоковского района Департамента юстиции Восточно-Казахстанской области 12 июля 2018 года № 5-9-176. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 18 сентября 2019 года № 34/8-VI
  title:
    rus: О внесении изменений в решение Глубоковского районного маслихата от 21 апреля 2014 года № 26/5-V «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Глубокое аудандық мәслихатының 2014 жылғы 21 сәуірдегі № 26/5-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123443/rus
