act_code: '96187'
requisite: Решение акима Зайсанского района Восточно-Казахстанской области от 26 октября 2015 года № 8. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 ноября 2015 года № 4243. Утратило силу - решением акима Зайсанского района Восточно-Казахстанской области от 6 сентября 2016 года № 8
title:
  rus: Об определении границ избирательных участков по Зайсанскому району
  kaz: Зайсан ауданы бойынша сайлау учаскелерінің шекараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-26
approved_by:
- '157012000001'
version_date:
  kaz: 2016-01-08
  rus: 2016-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/96187/kaz/08.01.2016
  rus: https://zan.gov.kz/client/#!/doc/96187/rus/08.01.2016
caused_by:
  code: '100134'
  requisite: Постановление Зайсанского районного акимата Восточно-Казахстанской области от 8 января 2016 года № 1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 января 2016 год № 4342. Утратило силу - решением акима Зайсанского района Восточно-Казахстанской области от 6 сентября 2016 года № 8
  title:
    rus: О внесении изменения в решение акима Зайсанского района от 26 октября 2015 года № 8 «Об определении границ избирательных участков по Зайсанскому району»
    kaz: «Зайсан ауданы бойынша сайлау учаскелерінің шекараларын белгілеу туралы» 2015 жылғы 26 қазандағы Зайсан ауданы әкімінің № 8 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/100134/rus
