act_code: '66092'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 18 мая 2012 года N 4/26-V. Зарегистрировано управлением юстиции Аягозского района Департамента юстиции Восточно-Казахстанской области 18 июня 2012 года за N 5-6-164. Утратило силу - решением Аягозского районного маслихата Восточно-Казахстанской области от 27 января 2015 года N 32/223-V
title:
  rus: Об утверждении Правил о размере и порядке оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсетудің мөлшері мен тәртібі туралы Қағиданы бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-05-18
approved_by:
- '157007000002'
version_date:
  kaz: 2012-05-18
  rus: 2012-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/66092/kaz/18.05.2012
  rus: https://zan.gov.kz/client/#!/doc/66092/rus/18.05.2012
