act_code: '59479'
requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 9 июня 2011 года № 33/6. Зарегистрировано Управлением юстиции города Усть-Каменогорска Департамента юстиции Восточно-Казахстанской области 7 июля 2011 года № 5-1-167. Утратило силу решением Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 17 мая 2018 года № 30/4-VI
title:
  rus: Об установлении категории автостоянок (паркингов) и увеличении размеров базовых ставок налога на земли, выделенные под автостоянки (паркинги)
  kaz: Автотұрақтардың (паркингтердің) санаттарын белгілеу және автотұрақтар (паркингтер) үшін бөлінген жерлерге салынатын базалық салық ставкаларының мөлшерлерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-06-09
approved_by:
- '157002000002'
version_date:
  kaz: 2011-06-09
  rus: 2011-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/59479/kaz/09.06.2011
  rus: https://zan.gov.kz/client/#!/doc/59479/rus/09.06.2011
