act_code: '54229'
requisite: Решение акима Выдрихинского сельского округа Шемонаихинского района Восточно-Казахстанской области от 12 августа 2010 года № 05. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 27 августа 2010 года за № 5-19-128
title:
  rus: О переименовании улиц и переулка села Выдриха
  kaz: Выдриха селосының көшелерін және тұйық көшесінің атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-12
approved_by:
- '157020007002'
version_date:
  kaz: 2010-08-12
  rus: 2010-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/54229/kaz/12.08.2010
  rus: https://zan.gov.kz/client/#!/doc/54229/rus/12.08.2010
