act_code: '93286'
requisite: Решение акима Кызыл кесикского сельского округа Тарбагатайского района Восточно-Казахстанской области от 09 июля 2015 года N 2. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 13 августа 2015 года N 4110. Утратило силу решением акима Кызыл кесикского сельского округа Тарбагатайского района Восточно-Казахстанской области от 1 сентября 2022 года № 12 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий в зимовке «Тогжан» Кызыл кесикского сельского округа Тарбагатайского района
  kaz: Тарбағатай ауданы Қызыл кесік ауылдық округiнiң «Тоғжан» қыстағына шектеу іс-шарасын белгiлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-09
approved_by:
- '157017008001'
version_date:
  kaz: 2015-07-09
  rus: 2015-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/93286/kaz/09.07.2015
  rus: https://zan.gov.kz/client/#!/doc/93286/rus/09.07.2015
