act_code: '87714'
requisite: ''
title:
  rus: 'О переименовании улицы села Курчум '
  kaz: 'Күршім ауылындағы көшенің атауын өзгерту туралы  '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-24
approved_by:
- '157016001001'
version_date:
  kaz: 2015-02-24
  rus: 2015-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/87714/kaz/24.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87714/rus/24.02.2015
