act_code: '139180'
requisite: Решение акима Урджарского сельского округа Урджарского района Восточно-Казахстанской области от 27 января 2020 года № 11. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 29 января 2020 года № 6712
title:
  rus: О переименовании улиц села Урджар Урджарского сельского округа Урджарского района
  kaz: Үржар ауданы Үржар ауылдық округі Үржар ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-27
approved_by:
- '157019001002'
version_date:
  kaz: 2020-01-27
  rus: 2020-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/139180/kaz/27.01.2020
  rus: https://zan.gov.kz/client/#!/doc/139180/rus/27.01.2020
