act_code: '163944'
requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 19 января 2022 года № 16-2. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 января 2022 года № 26569
title:
  rus: Об утверждении проекта (схемы) зонирования земель населенных пунктов Зайсанского района Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысы Зайсан ауданының елді мекендерінің жерлерін аймақтарға бөлу жобасын (схемасын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-01-19
approved_by:
- '157012000002'
version_date:
  kaz: 2022-01-19
  rus: 2022-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/163944/kaz/19.01.2022
  rus: https://zan.gov.kz/client/#!/doc/163944/rus/19.01.2022
