act_code: '11057'
requisite: Решение XII сессии Восточно-Казахстанского областного маслихата от 21 декабря 2001 года N 12/8-II. Зарегистрировано Управлением юстиции Восточно-Казахстанской области 21 января 2002 года за N 651. Отменено - решением VII сессии ВКО маслихата от 28 сентября 2004 года N 7/93-III
title:
  rus: О ставках платы за загрязнение окружающей среды на 2002 год
  kaz: Қоршаған ортаны ластағаны үшiн 2002 жылға арналған төлем ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-21
approved_by:
- '157000000002'
version_date:
  kaz: 2001-12-21
  rus: 2001-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/11057/kaz/21.12.2001
  rus: https://zan.gov.kz/client/#!/doc/11057/rus/21.12.2001
