act_code: '201221'
requisite: Решение маслихата района Самар Восточно-Казахстанской области от 26 сентября 2024 года № 15-6/VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 сентября 2024 года № 9087-16
title:
  rus: Об утверждении положения о награждении Почетной грамотой района Самар
  kaz: Самар ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2024-09-26
approved_by:
- '157021000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/201221/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/201221/rus/25.12.2024
caused_by:
  code: '205074'
  requisite: Решение маслихата района Самар Восточно-Казахстанской области от 25 декабря 2024 года № 18-8/VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 декабря 2024 года № 9120-16
  title:
    rus: О внесении изменений в решение маслихата района Самар от 26 сентября 2024 года № 15-6/VIІІ «Об утверждении положения о награждении Почетной грамотой района Самар»
    kaz: Самар ауданы мәслихатының 2024 жылғы 26 қыркүйектегі № 15-6/VIII «Самар ауданының Құрмет грамотасымен марапаттау туралы Ережені бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/205074/rus
