act_code: '33568'
requisite: Шығыс Қазақстан облысы Күршім аудандық мәслихатының 2007 жылғы 24 мамырдағы № 28-5 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Күршім аудандық Әділет басқармасында 2007 жылғы 7 маусымда № 5-14-50 тіркелді. Күші жойылды - ШҚО Күршім аудандық мәслихатының 2011 жылғы 30 қыркүйектегі № 29-5 шешімімен
title:
  rus: Біржолғы талондардың құнының мөлшері туралы
  kaz: Біржолғы талондардың құнының мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-05-24
approved_by:
- '157016000002'
version_date:
  kaz: 2009-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/33568/kaz/23.04.2009
caused_by:
  code: '45818'
  requisite: Шығыс Қазақстан облысы Күршім аудандық мәслихатының 2009 жылғы 23 сәуірдегі № 13-6 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Күршім аудандық Әділет басқармасында 2009 жылғы 7 мамырда № 5-14-83 тіркелді. Күші жойылды - ШҚО Күршім аудандық мәслихатының 2011 жылғы 30 қыркүйектегі № 29-5 шешімімен
  title:
    rus: '"Біржолғы талондардың құнының мөлшері туралы" 2007 жылғы 24 мамырдағы № 28-5 шешіміне өзгерістер енгізу туралы'
    kaz: '"Біржолғы талондардың құнының мөлшері туралы" 2007 жылғы 24 мамырдағы № 28-5 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/45818/rus
