act_code: '192050'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 22 декабря 2023 года № 8/9-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 5 января 2024 года № 8946-16
title:
  rus: Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Глубоковского района
  kaz: Глубокое ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету Қағидалары мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-22
approved_by:
- '157010000002'
version_date:
  kaz: 2024-09-24
  rus: 2024-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/192050/kaz/24.09.2024
  rus: https://zan.gov.kz/client/#!/doc/192050/rus/24.09.2024
caused_by:
  code: '201219'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 24 сентября 2024 года № 15/9-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 сентября 2024 года № 9086-16
  title:
    rus: О внесении изменений в решение Глубоковского районного маслихата от 22 декабря 2023 года № 8/9-VIII «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Глубоковского района»
    kaz: Глубокое аудандық мәслихатының 2023 жылғы 22 желтоқсандағы № 8/9-VIII «Глубокое ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық қызметтерге ақы төлеу және бюджет қаражаты есебінен отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібі мен мөлшерін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201219/rus
