act_code: '97142'
requisite: Решение от 15.12.2015 №7, Акимат Сартерекского сельского округа
title:
  rus: О признании утратившим силу решение акима Сартерекского сельского округа «Об установлении ограничительных мероприятий в селах Сартерек, Когедай Сартерекского сельского округа» № 5 от 24 сентября 2014 года
  kaz: 'Сартерек ауылдық  округі  әкімінің 2014 жылғы 24 қыркүйектегі № 5 «Сартерек ауылдық округіндегі Сартерек, Когедай ауылдарында шектеу іс-шараларын белгілеу туралы»  шешімінің күшін жою туралы  '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-15
approved_by:
- '157012007001'
version_date:
  kaz: 2015-12-15
  rus: 2015-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/97142/kaz/15.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97142/rus/15.12.2015
