act_code: '128259'
requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 29 декабря 2018 года № 35/5-VI. Зарегистрировано Управлением юстиции Бескарагайского района Департамента юстиции Восточно-Казахстанской области 9 января 2019 года № 5-7-155. Утратило силу решением Бескарагайского районного маслихата Восточно-Казахстанской области от 16 января 2020 года № 49/11-VI (вводится в действие с 01.01.2020)
title:
  rus: О бюджете Ерназаровского сельского округа на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Ерназар ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '157009000002'
version_date:
  kaz: 2019-11-26
  rus: 2019-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/128259/kaz/26.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128259/rus/26.11.2019
caused_by:
  code: '136596'
  requisite: Решение Бескарагайского районного маслихата Восточно-Казахстанской области от 26 ноября 2019 года № 45/4-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 3 декабря 2019 года № 6338. Утратило силу решением Бескарагайского районного маслихата Восточно-Казахстанской области от 16 января 2020 года № 49/11-VI (вводится в действие с 01.01.2020)
  title:
    rus: О внесении изменений в решение Бескарагайского районного маслихата от 29 декабря 2018 года № 35/5-VI «О бюджете Ерназаровского сельского округа на 2019-2021 годы»
    kaz: Бесқарағай аудандық мәслихатының 2018 жылғы 29 желтоқсандағы № 35/5-VІ «2019-2021 жылдарға арналған Ерназар ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136596/rus
