act_code: '170926'
requisite: Решение акима Баскольского сельского округа Бескарагайского района области Абай от 23 августа 2022 года № 5. Утратило силу решением акима Баскольского сельского округа Бескарагайского района области Абай от 11 октября 2022 года № 6 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий на животноводческой точке «Котлаван» села Карагайлы Баскольского сельского округа Бескарагайского района области Абай
  kaz: Абай облысы Бесқарағай ауданы Баскөл ауылдық округінің Қарағайлы ауылына қарасты «Котлаван» мал шаруашылық  жайылым мекеніне шектеу  іс-шараларын орнату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-23
approved_by:
- '157009002002'
version_date:
  kaz: 2022-08-23
  rus: 2022-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/170926/kaz/23.08.2022
  rus: https://zan.gov.kz/client/#!/doc/170926/rus/23.08.2022
