act_code: '152328'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/540-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 5 января 2021 года № 8313
title:
  rus: О бюджете Копинского сельского округа Аягозского района на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Аягөз ауданының Қопа ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '157007000002'
version_date:
  kaz: 2020-12-25
  rus: 2020-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/152328/kaz/25.12.2020
  rus: https://zan.gov.kz/client/#!/doc/152328/rus/25.12.2020
