act_code: '4148'
requisite: Решение Акима Восточно-Казахстанской области от 9 сентября 1999 года № 745 зарегистрировано управлением юстиции Восточно-Казахстанской обл. 20.09.1999 г. за № 233. Утратило силу - постановлением Восточно-Казахстанского областного акимата от 8 июня 2009 года № 03
title:
  rus: О создании системы общественной безопасности и единой диспетчерской службы
  kaz: Қоғамдық қауіпсіздік жүйесін және Бірыңғай диспетчерлік қызмет құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-09-08
approved_by:
- '157000000001'
version_date:
  kaz: 1999-09-08
  rus: 1999-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/4148/kaz/08.09.1999
  rus: https://zan.gov.kz/client/#!/doc/4148/rus/08.09.1999
