act_code: '5715'
requisite: Решение Акима Восточно-Казахстанской области от 6 апреля 2000 года N 836. Зарегистрировано управлением юстиции осточно- Казахстанской области 7 апреля 2000 года за N 290. Утратило силу решением акима ВКО от 28 июля 2004 года N 90
title:
  rus: О закупках элитных семян зерновых культур в Российской Федерации
  kaz: Россия Федерациясынан дәндi дақылдардың элиталық тұқымдарын сатып алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-04-05
approved_by:
- '157000000001'
version_date:
  kaz: 2000-04-05
  rus: 2000-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/5715/kaz/05.04.2000
  rus: https://zan.gov.kz/client/#!/doc/5715/rus/05.04.2000
