act_code: '162473'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 24 декабря 2021 года № 11/186-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26096
title:
  rus: О бюджете Жарминского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Жарма ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '157011000002'
version_date:
  kaz: 2022-06-14
  rus: 2022-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/162473/kaz/14.06.2022
  rus: https://zan.gov.kz/client/#!/doc/162473/rus/14.06.2022
caused_by:
  code: '169052'
  requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 14 июня 2022 года № 17/266-VII
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 24 декабря 2021 года № 11/186-VІI «О бюджете Жарминского района на 2022-2024 годы»
    kaz: Жарма аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 11/186-VІI «2022-2024 жылдарға арналған Жарма ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169052/rus
