act_code: '46542'
requisite: Решение акима Сарытерекского сельского округа Зайсанского района Восточно-Казахстанской области от 14 мая 2015 года № 1. Зарегистрировано Управлением юстиции Зайсанского района Департамента юстиции Восточно-Казахстанской области 29 мая 2009 года № 5-11-94
title:
  rus: Шалқар ауылының бұрын атауы жоқ көшесіне атау беру туралы
  kaz: Шалқар ауылының бұрын атауы жоқ көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-14
approved_by:
- '157012007001'
version_date:
  kaz: 2009-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/46542/kaz/14.05.2009
