act_code: '227079'
requisite: Решение маслихата района Самар Восточно-Казахстанской области от 29 июня 2026 года № 33-3/VIIІ
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по району Самар на 2026-2030 годы
  kaz: Самар ауданы бойынша 2026-2030 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-29
approved_by:
- '157021000002'
version_date:
  kaz: 2026-06-29
  rus: 2026-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/227079/kaz/29.06.2026
  rus: https://zan.gov.kz/client/#!/doc/227079/rus/29.06.2026
