act_code: '65758'
requisite: Решение акима Тассайского сельского округа Кокпектинского района Восточно-Казахстанской области от 18 апреля 2012 года № 2. Зарегистрировано управлением юстиции Кокпектинского района департамента юстиции Восточно-Казахстанской области 25 мая 2012 года за № 5-15-107
title:
  rus: О присвоении наименований улицам сел Кайнар, Аксу, Ушкомей Тассайского сельского округа
  kaz: Тассай селолық округінің аумағындағы Қайнар, Ақсу, Үшкөмей ауылдарындағы көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-18
approved_by:
- '157015002002'
version_date:
  kaz: 2012-04-18
  rus: 2012-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/65758/kaz/18.04.2012
  rus: https://zan.gov.kz/client/#!/doc/65758/rus/18.04.2012
