act_code: '6256'
requisite: Решение акима Восточно-Казахстанской области от 15 июня 2000 года № 868. Зарегистрировано управлением юстиции Восточно-Казахстанской области 26 июня 2000 года за № 344. Утратило силу - постановлением акимата Восточно-Казахстанской области от 10 декабря 2001 года № 35
title:
  rus: О предельных (максимальных) размерах земельных участков, которые могут находиться в постоянном землепользовании или в собственности
  kaz: Тұрақты жер пайдалануда немесе меншiкте бола алатын жер учаскелерiнiң шектi (барынша көп) мөлшерi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-06-14
approved_by:
- '157000000001'
version_date:
  kaz: 2000-06-14
  rus: 2000-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/6256/kaz/14.06.2000
  rus: https://zan.gov.kz/client/#!/doc/6256/rus/14.06.2000
