act_code: '99807'
requisite: Решение акима Курчумского сельского округа Курчумского района Восточно-Казахстанской области от 23 февраля 2016 года № 4
title:
  rus: О снятии ограничительных мероприятий  на участке «Ақтасты», села Курчум Курчумского сельского округа Курчумского района
  kaz: Күршім ауданының Күршім ауылдық  округінің Күршім ауылындағы «Ақтасты» учаскесінде шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-23
approved_by:
- '157016001001'
version_date:
  kaz: 2016-02-23
  rus: 2016-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/99807/kaz/23.02.2016
  rus: https://zan.gov.kz/client/#!/doc/99807/rus/23.02.2016
