act_code: '7861'
requisite: Решение VII сессии Восточно-Казахстанского областного маслихата II созыва от 26 декабря 2000 года N 7/2-II. Зарегистрировано управлением юстиции Восточно-Казахстанской области 12 января 2001 года за N 422. Утратило силу в связи с истечением срока действия - письмо ВКО маслихата от 30 марта 2007 года N 01-151/01-06
title:
  rus: Об областном бюджете на 2001 год
  kaz: 2001 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-12-26
approved_by:
- '157000000002'
version_date:
  kaz: 2000-12-26
  rus: 2000-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/7861/kaz/26.12.2000
  rus: https://zan.gov.kz/client/#!/doc/7861/rus/26.12.2000
