act_code: '2947'
requisite: Решение XVIII сессии Восточно-Казахстанского областного маслихата от 17 сентября 1998 года № 18/10. Зарегистрировано управлением юстиции Восточно-Казахстанской области 9 октября 1998 года за № 99. Утратило силу - решением Восточно-Казахстанского областного маслихата от 11 марта 2005 года № 10/145-III
title:
  rus: О правилах оптовой торговли
  kaz: Көтерме сауда ережесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-09-16
approved_by:
- '157000000002'
version_date:
  kaz: 1998-09-16
  rus: 1998-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/2947/kaz/16.09.1998
  rus: https://zan.gov.kz/client/#!/doc/2947/rus/16.09.1998
