act_code: '199259'
requisite: Решение Тарбагатайского районного маслихата Восточно-Казахстанской области от 12 июля 2024 года № 16/16-VIII. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 29 июля 2024 года № 9058-16
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Тарбагатайском районе
  kaz: Тарбағатай ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-12
approved_by:
- '157017000002'
version_date:
  kaz: 2024-07-12
  rus: 2024-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/199259/kaz/12.07.2024
  rus: https://zan.gov.kz/client/#!/doc/199259/rus/12.07.2024
