act_code: '58736'
requisite: Решение акима Курчумского сельского округа Курчумского района Восточно-Казахстанской области от 19 апреля 2011 года № 3. Зарегистрировано управлением юстиции Курчумского района Департамента юстиции Восточно-Казахстанской области 6 мая 2011 года за № 5-14-127
title:
  rus: О переименовании улиц села Курчум
  kaz: Күршім ауылының көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-19
approved_by:
- '157016001001'
version_date:
  kaz: 2021-03-10
  rus: 2021-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/58736/kaz/10.03.2021
  rus: https://zan.gov.kz/client/#!/doc/58736/rus/10.03.2021
caused_by:
  code: '153442'
  requisite: Решение акима Курчумского сельского округа Курчумского района Восточно-Казахстанской области от 10 марта 2021 года № 1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 марта 2021 года № 8444
  title:
    rus: О внесении изменений в решение акима Курчумского сельского округа от 19 апреля 2011 года № 3 «О переименовании улиц села Курчум»
    kaz: Күршім ауылдық округі әкімінің 2011 жылғы 19 сәуірдегі «Күршім ауылының көшелерінің атауын өзгерту туралы» № 3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153442/rus
