act_code: '139171'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 30 декабря 2019 года № 48/321-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 22 января 2020 года № 6688. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 29 декабря 2020 года № 62/446-VI (вводится в действие с 01.01.2021)
title:
  rus: «О бюджете Алгабасского сельского округа на 2020-2022 годы»
  kaz: «Алғабас ауылдық округінің 2020-2022 жылдарға арналған бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '157003000002'
version_date:
  kaz: 2020-03-19
  rus: 2020-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/139171/kaz/19.03.2020
  rus: https://zan.gov.kz/client/#!/doc/139171/rus/19.03.2020
caused_by:
  code: '140885'
  requisite: Решение маслихата города Семей Восточно-Казахстанской области от 19 марта 2020 года № 50/359-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 марта 2020 года № 6826. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 29 декабря 2020 года № 62/446-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение маслихата города Семей от 30 декабря 2019 года № 48/321-VI «О бюджете Алгабасского сельского округа на 2020-2022 годы»
    kaz: Семей қаласы мәслихатының 2019 жылғы 30 желтоқсандағы № 48/321-VI «Алғабас ауылдық округінің 2020-2022 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140885/rus
