act_code: '83054'
requisite: Решение акима Курчумского района Восточно-Казахстанской области от 25 августа 2014 года № 8. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 5 сентября 2014 года № 3475. Утратило силу - решением акима Курчумского района Восточно-Казахстанской области от 24 декабря 2014 года № 13
title:
  rus: Об объявлении чрезвычайной ситуации
  kaz: Төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-08-25
approved_by:
- '157016000001'
version_date:
  kaz: 2014-08-25
  rus: 2014-08-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/83054/kaz/25.08.2014
  rus: https://zan.gov.kz/client/#!/doc/83054/rus/25.08.2014
