act_code: '55461'
requisite: Шығыс Қазақстан облысы Аягөз аудандық мәслихатының 2010 жылғы 26 қазандағы № 01-02/28-9 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Аягөз аудандық әділет басқармасында 2010 жылғы 18 қарашада № 5-6-123 тіркелді. Күші жойылды - Аягөз аудандық мәслихатының 2012 жылғы 13 шілдедегі № 5/37-V шешімімен
title:
  rus: Бір жолғы талондардың құнын бекіту туралы
  kaz: Бір жолғы талондардың құнын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-26
approved_by:
- '157007000002'
version_date:
  kaz: 2010-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/55461/kaz/26.10.2010
