act_code: '139175'
requisite: Решение маслихата города Семей Восточно-Казахстанской области от 30 декабря 2019 года № 48/329-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 22 января 2020 года № 6693. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 29 декабря 2020 года № 62/454-VI (вводится в действие с 01.01.2021)
title:
  rus: «О бюджете Приречного сельского округа на 2020-2022 годы»
  kaz: «Приречный ауылдық округінің 2020-2022 жылдарға арналған бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '157003000002'
version_date:
  kaz: 2020-11-16
  rus: 2020-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/139175/kaz/16.11.2020
  rus: https://zan.gov.kz/client/#!/doc/139175/rus/16.11.2020
caused_by:
  code: '148932'
  requisite: Решение маслихата города Семей Восточно-Казахстанской области от 16 ноября 2020 года № 58/426-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 26 ноября 2020 года № 7864. Утратило силу решением маслихата города Семей Восточно-Казахстанской области от 29 декабря 2020 года № 62/454-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение маслихата города Семей от 30 декабря 2019 года № 48/329-VI «О бюджете Приречного сельского округа на 2020-2022 годы»
    kaz: Семей қаласы мәслихатының 2019 жылғы 30 желтоқсандағы № 48/329-VI «Приречный ауылдық округінің 2020-2022 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148932/rus
