act_code: '149602'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 3 декабря 2020 года № 53/4-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 10 декабря 2020 года № 7957
title:
  rus: Об установлении повышенных должностных окладов и тарифных ставок гражданским служащим сельской местности Глубоковского района
  kaz: Глубокое ауданының ауылдық жердегі азаматтық қызметшілеріне жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелерді белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-03
approved_by:
- '157010000002'
version_date:
  kaz: 2020-12-03
  rus: 2020-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/149602/kaz/03.12.2020
  rus: https://zan.gov.kz/client/#!/doc/149602/rus/03.12.2020
