act_code: '135398'
requisite: Решение акима города Алтай Восточно-Казахстанской области от 14 октября 2019 года № 3. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 октября 2019 года № 6201
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью «Gold Mining Corp.» для проведения операций по разведке полезных ископаемых
  kaz: «Gold Mining Corp.» жауапкершілігі шектеулі серіктестігіне пайдалы қазбаларды барлау жөніндегі операцияларды жүргізу үшін жер теліміне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-14
approved_by:
- '157013016001'
version_date:
  kaz: 2020-01-24
  rus: 2020-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/135398/kaz/24.01.2020
  rus: https://zan.gov.kz/client/#!/doc/135398/rus/24.01.2020
caused_by:
  code: '139184'
  requisite: Решение акима района Алтай Восточно-Казахстанской области от 24 января 2020 года № 1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 28 января 2020 года № 6709
  title:
    rus: О внесении изменений в решение акима города Алтай от 14 октября 2019 года № 3 «Об установлении публичного сервитута товариществу с ограниченной ответственностью «Gold Mining Corp.» для проведения операций по разведке полезных ископаемых»
    kaz: «Пайдалы қазбаларды барлау бойынша операцияларды жүргізу үшін «Gold Mining Corp.» жауапкершілігі шектеулі серіктестігіне қауымдық сервитут орнату туралы» Алтай қаласы әкімінің 2019 жылғы 14 қазандағы № 3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/139184/rus
