act_code: '142323'
requisite: Решение акима Тугылского сельского округа Тарбагатайского района Восточно-Казахстанской области от 13 апреля 2020 года № 17. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 23 апреля 2020 года № 6990
title:
  rus: О переименовании улицы в селе Тугыл Тугылского сельского округа
  kaz: Тұғыл ауылдық округінің Тұғыл ауылындағы көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-13
approved_by:
- '157017003002'
version_date:
  kaz: 2020-04-13
  rus: 2020-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/142323/kaz/13.04.2020
  rus: https://zan.gov.kz/client/#!/doc/142323/rus/13.04.2020
