act_code: '567'
requisite: Решение XIV сессии Восточно-Казахстанского областного маслихата от 30 сентября 1997 года № 14/9. Зарегистрировано управлением юстиции Восточно-Казахстанской области 27 ноября 1997 года за № 1. Утратило силу решением Восточно-Казахстанского областного маслихата от 11 марта 2005 года № 10/145-III
title:
  rus: Об упорядочении торговли алкогольными напитками и пивом на территории Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысының аумағында алкогольді iшiмдiктермен және сырамен сауда жасауды ретке келтiру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-09-29
approved_by:
- '157000000002'
version_date:
  kaz: 1997-09-29
  rus: 1997-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/567/kaz/29.09.1997
  rus: https://zan.gov.kz/client/#!/doc/567/rus/29.09.1997
