act_code: '162804'
requisite: Решение Кокпектинского районного маслихата Восточно-Казахстанской области от 24 декабря 2021 года № 12-2. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2021 года № 26206
title:
  rus: О Кокпектинском районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Көкпекті аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '157015000002'
version_date:
  kaz: 2022-10-06
  rus: 2022-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/162804/kaz/06.10.2022
  rus: https://zan.gov.kz/client/#!/doc/162804/rus/06.10.2022
caused_by:
  code: '173510'
  requisite: Решение Кокпектинского районного маслихата области Абай от 6 октября 2022 года № 24-5/1
  title:
    rus: О внесении изменений в решение Кокпектинского районного маслихата от 24 декабря 2021 года № 12-2 «О Кокпектинском районном бюджете на 2022-2024 годы»
    kaz: Көкпекті аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 12-2 «2022-2024 жылдарға арналған Көкпекті аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173510/rus
