act_code: '121005'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 29 марта 2018 года № 23/3-VI. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 17 апреля 2018 года № 5-19-176. Утратило силу решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 5 августа 2020 года № 55/9-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Шемонаихинскому району на 2018-2019 годы
  kaz: Шемонаиха ауданы бойынша 2018-2019 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2018-03-29
approved_by:
- '157020000002'
version_date:
  kaz: 2018-03-29
  rus: 2018-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/121005/kaz/29.03.2018
  rus: https://zan.gov.kz/client/#!/doc/121005/rus/29.03.2018
