act_code: '61793'
requisite: Решение акима города Курчатова Восточно-Казахстанской области от 28 ноября 2011 года № 21. Зарегистрировано Управлением юстиции города Курчатова Департамента юстиции Восточно-Казахстанской области 8 декабря 2011 года за № 5-3-111. Утратило силу - решением акима города Курчатова Восточно-Казахстанской области от 17 августа 2015 года № 9
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-28
approved_by:
- '157004000001'
version_date:
  kaz: 2011-11-28
  rus: 2011-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/61793/kaz/28.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61793/rus/28.11.2011
