act_code: '138768'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 10 января 2020 года № 48-567/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 января 2020 года № 6565. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 29 декабря 2020 года № 57-781/VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Шолпанского сельского округа Урджарского района на 2020-2022 годы
  kaz: Үржар ауданы Шолпан ауылдық округінің 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '157019000002'
version_date:
  kaz: 2020-01-10
  rus: 2020-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/138768/kaz/10.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138768/rus/10.01.2020
