act_code: '182822'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 9 июня 2023 года № 40
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Толеген-Тохтаровскому сельскому округу на 2023-2024 годы
  kaz: Төлеген Тоқтаров ауылдық округі бойынша 2023-2024  жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2023-06-09
approved_by:
- '157018000002'
version_date:
  kaz: 2023-06-09
  rus: 2023-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/182822/kaz/09.06.2023
  rus: https://zan.gov.kz/client/#!/doc/182822/rus/09.06.2023
