act_code: '153274'
requisite: Решение акима Нарынского сельского округа Аягозского района Восточно-Казахстанской области от 4 марта 2021 года № 7. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 5 марта 2021 года № 8425. Утратило силу решением акима Нарынского сельского округа Аягозского района Восточно-Казахстанской области от 9 апреля 2021 года № 10 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении карантина на территории крестьянского хозяйства «Жақсылық» Нарынского сельского округа Аягозского района
  kaz: Аягөз ауданы Нарын ауылдық округінің «Жақсылық» шаруа қожалығының аумағына карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-04
approved_by:
- '157007018002'
version_date:
  kaz: 2021-03-04
  rus: 2021-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/153274/kaz/04.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153274/rus/04.03.2021
