act_code: '79935'
requisite: Решение Кокпектинского районного маслихата Восточно-Казахстанской области от 3 апреля 2014 года № 22-6/4. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 6 мая 2014 года № 3288. Утратило силу решением Кокпектинского районного маслихата Восточно-Казахстанской области от 20 июня 2018 года № 23-6/3
title:
  rus: Об утверждении проекта (схемы) зонирования земель и поправочных коэффициентов к базовым ставкам земельного налога по Кокпектинскому району
  kaz: Көкпекті ауданының жерлерін аймақтарға бөлу жобасын (сызбасын) және жер салығының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-03
approved_by:
- '157015000002'
version_date:
  kaz: 2014-04-03
  rus: 2014-04-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/79935/kaz/03.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79935/rus/03.04.2014
