act_code: '55214'
requisite: Шығыс Қазақстан облысы Ұлан ауданы Таврия ауылдық округі әкімінің 2010 жылғы 24 қыркүйектегі № 1 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Ұлан аудандық әділет басқармасында 2010 жылғы 3 қарашада № 5-17-135 тіркелді
title:
  rus: Таврия ауылындағы көшелерінің атауын өзгерту туралы
  kaz: Таврия ауылындағы көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-24
approved_by:
- '157018016001'
version_date:
  kaz: 2010-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/55214/kaz/24.09.2010
