act_code: '49864'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 25 декабря 2009 года № 21/4-IV. Зарегистрировано управлением юстиции города Риддера Департамента юстиции Восточно-Казахстанской области 14 января 2010 года за № 5-4-124. Утратило силу решением Риддерского городского маслихата от 29 декабря 2010 года № 29/8-IV
title:
  rus: О стоимости разовых талонов на 2010 год
  kaz: 2010 жылға бір жолғы талондардың құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '157005000002'
version_date:
  kaz: 2009-12-25
  rus: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49864/kaz/25.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49864/rus/25.12.2009
