act_code: '131007'
requisite: Решение акима Курчумского сельского округа Курчумского района Восточно-Казахстанской области от 29 апреля 2019 года № 1. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 2 мая 2019 года № 5899. Утратило силу решением акима Курчумского сельского округа Курчумского района Восточно-Казахстанской области от 30 января 2020 года № 1 (вводится в действие по истечении десяти календарных дней после его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий в селе Топтерек Курчумского сельского округа Курчумского района
  kaz: Күршім ауданының Күршім ауылдық округіне қарасты Топтерек ауылында шектеуіс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-04-29
approved_by:
- '157016001002'
version_date:
  kaz: 2019-04-29
  rus: 2019-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/131007/kaz/29.04.2019
  rus: https://zan.gov.kz/client/#!/doc/131007/rus/29.04.2019
