act_code: '91069'
requisite: Решение акима Бурановского сельского округа Курчумского района Восточно-Казахстанской области от 29 мая 2015 года № 02. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 29 июня 2015 года № 4011. Утратило силу - решением акима Бурановского сельского округа Курчумского района Восточно-Казахстанской области от 10 мая 2017 года № 02
title:
  rus: Об установлении ограничительных мероприятий в селе Жанаауыл Бурановского сельского округа Курчумского района
  kaz: Күршім ауданы Боран ауылдық округі Жаңаауыл ауылына шектеу іс-шарасын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-29
approved_by:
- '157016006001'
version_date:
  kaz: 2015-05-29
  rus: 2015-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/91069/kaz/29.05.2015
  rus: https://zan.gov.kz/client/#!/doc/91069/rus/29.05.2015
