act_code: '27804'
requisite: Постановление акимата Зыряновского района Восточно-Казахстанской области от 19 апреля 2006 года № 2296. Зарегистрировано Управлением юстиции Зыряновского района Департамента юстиции Восточно-Казахстанской области 2 мая 2018 года № 5-12-28. Утратило силу постановлением акимата Зыряновского района Восточно-Казахстанской области  от 18 апреля 2007 года № 3299
title:
  rus: О проведении призыва на срочную военную службу граждан 1979 - 1988 годов рождения весной и осенью 2006 года
  kaz: 2006 жылғы көктемде және күзде 1979-1988 жылдары туған азаматтарды мерзімді әскери қызметке шақыруды өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-04-19
approved_by:
- '157013000001'
version_date:
  kaz: 2006-04-19
  rus: 2006-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/27804/kaz/19.04.2006
  rus: https://zan.gov.kz/client/#!/doc/27804/rus/19.04.2006
