act_code: '147190'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 16 сентября 2020 года № 46/7-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 8 октября 2020 года № 7633
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования, норм их предельной заполняемости, требований к их материально-техническому и организационному обеспечению, границ прилегающих территорий, в которых запрещено проведение пикетирования по городу Риддеру
  kaz: Риддер қаласы бойынша бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, оларды пайдалану тәртібін, олардың шекті толу нормаларын, оларды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-16
approved_by:
- '157005000002'
version_date:
  kaz: 2020-09-16
  rus: 2020-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/147190/kaz/16.09.2020
  rus: https://zan.gov.kz/client/#!/doc/147190/rus/16.09.2020
