act_code: '72784'
requisite: Решение Катон-Карагайского районного маслихата Восточно-Казахстанской области от 23 апреля 2013 года № 11/96-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 мая 2013 года № 2963. Прекращено действие по истечении срока, на который решение было принято (письмо маслихата Катон-Карагайского района от 30 мая 2014 года № 117)
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты района в 2013 году
  kaz: Ауданның ауылдық елдi мекендеріне жұмыс iстеу және тұру үшiн келген денсаулық сақтау, бiлiм беру, әлеуметтiк қамсыздандыру, мәдениет, спорт және ветеринария мамандарына 2013  жылы әлеуметтiк қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-04-23
approved_by:
- '157014000002'
version_date:
  kaz: 2013-04-23
  rus: 2013-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/72784/kaz/23.04.2013
  rus: https://zan.gov.kz/client/#!/doc/72784/rus/23.04.2013
