act_code: '146944'
requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 16 сентября 2020 года № 46/8-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 30 сентября 2020 года № 7610
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по городу Риддеру
  kaz: Риддер қаласы бойынша тұрғын үй сертификаттарының мөлшерін және алушылар санатының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-16
approved_by:
- '157005000002'
version_date:
  kaz: 2022-04-20
  rus: 2022-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/146944/kaz/20.04.2022
  rus: https://zan.gov.kz/client/#!/doc/146944/rus/20.04.2022
caused_by:
  code: '166972'
  requisite: Решение Риддерского городского маслихата Восточно-Казахстанской области от 20 апреля 2022 года № 14/7-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 25 апреля 2022 года № 27745
  title:
    rus: О внесении изменения в решение Риддерского городского маслихата от 16 сентября 2020 года № 46/8-VI «Об определении размера и перечня категорий получателей жилищных сертификатов по городу Риддеру»
    kaz: «Риддер қаласы бойынша тұрғын үй сертификаттарының мөлшерін және алушылар санатының тізбесін айқындау туралы» Риддер қалалық мәслихатының 2020 жылғы 16 қыркүйектегі № 46/8-VI шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166972/rus
