act_code: '118177'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 4 января 2018 года № 155. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 19 января 2018 года № 5446. Утратило силу решением Уланского районного маслихата Восточно-Казахстанской области от 28 декабря 2018 года № 265
title:
  rus: О бюджете поселка Касыма Кайсенова Уланского района на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Ұлан ауданы Қасым Кайсенов кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-04
approved_by:
- '157018000002'
version_date:
  kaz: 2018-10-11
  rus: 2018-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/118177/kaz/11.10.2018
  rus: https://zan.gov.kz/client/#!/doc/118177/rus/11.10.2018
caused_by:
  code: '125707'
  requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 11 октября 2018 года № 231. Зарегистрировано Управлением юстиции Уланского района Департамента юстиции Восточно-Казахстанской области 31 октября 2018 года № 5-17-197. Утратило силу решением Уланского районного маслихата Восточно-Казахстанской области от 28 декабря 2018 года № 265
  title:
    rus: О внесении изменений в решение Уланского районного маслихата от 4 января 2018 года № 155 «О бюджете поселка Касыма Кайсенова Уланского района на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған Ұлан ауданы Қасым Кайсенов кентінің бюджеті туралы» Ұлан аудандық мәслихатының 2018 жылғы 4 қаңтардағы № 155 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125707/rus
