act_code: '109459'
requisite: Решение Бородулихинского районного маслихата Восточно-Казахстанской области от 23 декабря 2016 года № 8-7-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 26 января 2017 года № 4857. Утратило силу решением Бородулихинского районного маслихата Восточно-Казахстанской области от 14 декабря 2018 года № 30-3-VI
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на неиспользуемые земли сельскохозяйственного назначения по Бородулихинскому району
  kaz: Бородулиха ауданы бойынша ауыл шаруашылығы мақсатында пайдаланылмайтын жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-23
approved_by:
- '157008000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/109459/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109459/rus/23.12.2016
