act_code: '92446'
requisite: Решение от 13.07.2015 №29/6-V, Маслихат Абайского района (Восточно-Казахстанская область). Утратило силу - решением маслихата Абайского района Восточно-Казахстанской области от 20.10.2015 № 31/7-V.
title:
  rus: 'О повышении ставок земельного и единого земельного налогов по Абайскому району '
  kaz: 'Абай  ауданы бойынша жер және бірыңғай жер салықтарының мөлшерлемелерін жоғарылату  туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-13
approved_by:
- '157006000002'
version_date:
  kaz: 2015-07-13
  rus: 2015-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/92446/kaz/13.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92446/rus/13.07.2015
