act_code: '52921'
requisite: Шығыс Қазақстан облысы Катонқарағай ауданы Үлкен Нарын ауылдық округі әкімінің 2010 жылғы 21 мамырдағы № 1 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Катонқарағай аудандық әділет басқармасында 2010 жылғы 3 маусымда № 5-13-74 тіркелді
title:
  rus: Көше атауын өзгерту туралы
  kaz: Көше атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-21
approved_by:
- '157014012002'
version_date:
  kaz: 2010-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/52921/kaz/21.05.2010
