act_code: '126771'
requisite: Решение акима Каменского сельского округа Уланского района Восточно-Казахстанской области от 23 ноября 2018 года № 1. Зарегистрировано Управлением юстиции Уланского района Департамента юстиции Восточно-Казахстанской области 11 декабря 2018 года № 5-17-206
title:
  rus: О переименовании улицы в селе Каменка Каменского сельского округа
  kaz: Каменка ауылдық округінің Каменка ауылының көшесінің атауын қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-23
approved_by:
- '157018011002'
version_date:
  kaz: 2018-11-23
  rus: 2018-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/126771/kaz/23.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126771/rus/23.11.2018
