act_code: '12019'
requisite: Решение Акима Восточно-Казахстанской области от 14 февраля 2002 года № 1156. Зарегистрировано управлением юстиции Восточно-Казахстанской области 29 апреля 2002 года за № 799. Утратило силу решением акима Восточно-Казахстанской области от 29 июня 2007 года № 09
title:
  rus: Об утверждении перечня документов и показателей, необходимых для определения финансового состояния заявителей, осуществляющих деятельность по организации и проведению тотализаторов и казино
  kaz: Об утверждении перечня документов и показателей, необходимых для определения финансового состояния заявителей, осуществляющих деятельность по организации и проведению тотализаторов и казино
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-02-14
approved_by:
- '157000000001'
version_date:
  rus: 2002-02-14
source:
  rus: https://zan.gov.kz/client/#!/doc/12019/rus/14.02.2002
