act_code: '39349'
requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 15 апреля 2008 года № 7/58-IV. Зарегистрировано в Управлении юстиции города Курчатова Департамента юстиции Восточно-Казахстанской области 4 мая 2008 года за № 5-3-56. Утратило силу решением Курчатовского городского маслихата Восточно-Казахстанской области от 16 июля 2012 года № 6/45-V
title:
  rus: О Правилах содержания собак и кошек в городе Курчатове
  kaz: Курчатов қаласында ит пен мысықтарды ұстау Қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2008-04-15
approved_by:
- '157004000002'
version_date:
  kaz: 2009-04-23
  rus: 2009-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/39349/kaz/23.04.2009
  rus: https://zan.gov.kz/client/#!/doc/39349/rus/23.04.2009
caused_by:
  code: '45705'
  requisite: Решение Курчатовского городского маслихата Восточно-Казахстанской области от 23 апреля 2009 года № 18/137-IV. Зарегистрировано Управлением юстиции города Курчатова Департамента юстиции Восточно-Казахстанской области 8 мая 2009 года за № 5-3-74. Утратило силу решением Курчатовского городского маслихата Восточно-Казахстанской области от 16 июля 2012 года № 6/45-V
  title:
    rus: О внесении изменений в решение от 15 апреля 2008 года № 7/58-IV "О Правилах содержания животных, выгула собак и кошек в городе Курчатове"
    kaz: '"Курчатов қаласында жануарларды ұстау, ит пен мысықтарды серуендету қағидалары туралы" 2008 жылғы 15 сәуірдегі № 7/58-IV шешімге өзгертулер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/45705/rus
