act_code: '82219'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 21 июля 2014 года № 21/6-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 13 августа 2014 года № 3453. Утратило силу решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 4 апреля 2019 года № 38/4-VI
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын  бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-07-21
approved_by:
- '157020000002'
version_date:
  kaz: 2015-03-02
  rus: 2015-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/82219/kaz/02.03.2015
  rus: https://zan.gov.kz/client/#!/doc/82219/rus/02.03.2015
caused_by:
  code: '88055'
  requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 2 марта 2015 года № 26/2-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 26 марта 2015 года № 3775. Утратило силу решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 4 апреля 2019 года № 38/4-VI
  title:
    rus: О внесении изменения и дополнения в решение Шемонаихинского районного маслихата от 21 июля 2014 года № 21/6-V «Об утверждении Правил оказания социальной помощи, установления размеров и определения  перечня отдельных категорий нуждающихся граждан»
    kaz: «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Шемонаиха аудандық мәслихатының 2014 жылғы 21 шілдедегі № 21/6-V шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88055/rus
