act_code: '43260'
requisite: Шығыс Қазақстан облысы Жарма аудандық мәслихатының 2008 жылғы 29 желтоқсандағы № 9/2-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Жарма аудандық әділет басқармасында 2009 жылғы 6 қаңтарда № 5-10-73 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Жарма аудандық мәслихатының 2010 жылғы 5 ақпандағы № 29/4-15 хаты
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-29
approved_by:
- '157011000002'
version_date:
  kaz: 2009-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43260/kaz/24.11.2009
caused_by:
  code: '49017'
  requisite: Шығыс Қазақстан облысы Жарма аудандық мәслихатының 2009 жылғы 24 қарашадағы № 16/2-IV шешімі. Шығыс Қазақстан облысы Әділет департаментінің Жарма аудандық әділет басқармасында 2009 жылғы 30 қарашада № 5-10-91 тіркелді. Қабылданған мерзімінің бітуіне байланысты күші жойылды - Жарма аудандық мәслихатының 2010 жылғы 5 ақпандағы № 29/4-15 хаты
  title:
    rus: 2008 жылғы 29 желтоқсандағы № 9/2-IV "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: 2008 жылғы 29 желтоқсандағы № 9/2-IV "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49017/rus
