act_code: '125592'
requisite: Решение маслихата Абайского района Восточно-Казахстанской области от 23 октября 2018 года № 27/7-VІ. Зарегистрировано Управлением юстиции Абайского района Департамента юстиции Восточно-Казахстанской области 1 ноября 2018 года № 5-5-158. Действие решения приостановлено до приведения его в соответствие с действующим законодательством Республики Казахстан и принятия решения на сессии Абайского районного маслихата решением Абайского районного маслихата Восточно-Казахстанской области от 13  апреля 2020 года № 46/11-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования). Утратило силу решением Абайского районного маслихата Восточно-Казахстанской области от 23 июня 2020 года № 49/7-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об оказании социальной поддержки специалистам государственных организаций, проживающим и работающим в сельских населенных пунктах Абайского района
  kaz: Абай ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік ұйымдардың мамандарына әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-23
approved_by:
- '157006000002'
version_date:
  kaz: 2020-04-13
  rus: 2020-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/125592/kaz/13.04.2020
  rus: https://zan.gov.kz/client/#!/doc/125592/rus/13.04.2020
caused_by:
  code: '141886'
  requisite: Решение маслихата Абайского района Восточно-Казахстанской области от 13 апреля 2020 года № 46/11-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 апреля 2020 года № 6901. Утратило силу решением Абайского районного маслихата Восточно-Казахстанской области от 23 июня 2020 года № 49/7-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О приостановлении действия решения маслихата Абайского района от 23 октября 2018 года № 27/7-VI «Об оказании социальной поддержки специалистам государственных организаций, проживающим и работающим в сельских населенных пунктах Абайского района»
    kaz: Абай аудандық мәслихатының 2018 жылғы 23 қазандағы № 27/7-VI «Абай ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік ұйымдардың мамандарына әлеуметтік қолдау көрсету туралы» шешімінің қолданылуын тоқтата тұру туралы
  link: https://zan.gov.kz/client/#!/doc/141886/rus
