act_code: '86257'
requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 23 декабря 2014 года № 29-8/4. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 21 января 2015 года № 3646. Утратило силу - решением Зайсанского районного маслихата Восточно-Казахстанской области от 22.12.2015 № 41-8/1
title:
  rus: О предоставлении мер социальной поддержки специалистам  здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса прибывшим для работы и проживания в сельские населенные пункты на 2015 год
  kaz: 2015 жылға арналған ауылдық елдi мекендерге жұмыс iстеу және тұру үшiн келген денсаулық сақтау, бiлiм беру, әлеуметтiк қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен мамандарына әлеуметтiк қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '157012000002'
version_date:
  kaz: 2014-12-23
  rus: 2014-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/86257/kaz/23.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86257/rus/23.12.2014
