act_code: '79826'
requisite: Решение Восточно-Казахстанского областного маслихата от 11 апреля 2014 года № 19/219-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 13 мая 2014 года № 3312
title:
  rus: Об утверждении Правил содержания животных в населенных пунктах Восточно-Казахстанской области, Правил содержания сельскохозяйственных животных в населенных пунктах Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысының елді мекендерінде жануарларды асырау қағидаларын, Шығыс Қазақстан облысының елді мекендерінде ауыл шаруашылығы жануарларын асырау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-04-11
approved_by:
- '157000000002'
version_date:
  kaz: 2014-04-10
  rus: 2014-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/79826/kaz/10.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79826/rus/10.04.2014
