act_code: '201091'
requisite: Решение Восточно-Казахстанского областного маслихата от 20 сентября 2024 года № 16/125-VІІІ
title:
  rus: Об утверждении Положения о государственном учреждении «Аппарат Восточно-Казахстанского областного маслихата»
  kaz: «Шығыс Қазақстан облыстық мәслихатының аппараты» мемлекеттік мекемесі туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2024-09-20
approved_by:
- '157000000002'
version_date:
  kaz: 2026-08-27
  rus: 2026-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/201091/kaz/27.08.2026
  rus: https://zan.gov.kz/client/#!/doc/201091/rus/27.08.2026
caused_by:
  code: '229648'
  requisite: Решение Восточно-Казахстанского областного маслихата от 27 августа 2026 года № 30/259-VIII
  title:
    rus: О внесении изменения в решение Восточно-Казахстанского областного маслихата от 20 сентября 2024 года № 16/125-VІII «Об утверждении Положения о государственном учреждении «Аппарат Восточно-Казахстанского областного маслихата»
    kaz: «Шығыс Қазақстан облыстық мәслихатының аппараты» мемлекеттік мекемесі туралы ережені бекіту туралы» Шығыс Қазақстан облыстық мәслихатының 2024 жылғы 20 қыркүйектегі № 16/125-VІІІ шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229648/rus
