act_code: '144119'
requisite: Решение акима Аягозского района Восточно-Казахстанской области от 22 июня 2020 года № 5. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 24 июня 2020 года № 7213. Утратило силу решением акима Аягозского района области Абай от 30 ноября 2023 года № 1 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об объявлении на территории города Аягоз, села Мамырсу, населенного пункта Старый Майлин Аягозского района чрезвычайной ситуаций местного масштаба
  kaz: Аягөз ауданының Аягөз қаласының, Мамырсу ауылының, Ескі Майлин елді мекенінің аумағында жергілікті ауқымдағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-22
approved_by:
- '157007000003'
version_date:
  kaz: 2020-06-22
  rus: 2020-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/144119/kaz/22.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144119/rus/22.06.2020
