act_code: '177829'
requisite: Решение маслихата района Алтай Восточно-Казахстанской области от 29 декабря 2022 года № 29/6-VII
title:
  rus: О бюджете поселка Новая Бухтарма на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Жаңа Бұқтырма кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '157013000002'
version_date:
  kaz: 2023-12-07
  rus: 2023-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/177829/kaz/07.12.2023
  rus: https://zan.gov.kz/client/#!/doc/177829/rus/07.12.2023
caused_by:
  code: '189913'
  requisite: Решение маслихата района Алтай Восточно-Казахстанской области от 7 декабря 2023 года № 8/6-VIII
  title:
    rus: О внесении изменений в решение маслихата района Алтай от 29 декабря 2022 года № 29/6-VII «О бюджете поселка Новая Бухтарма на 2023-2025 годы»
    kaz: Алтай ауданының мәслихатының 2022 жылғы 29 желтоқсандағы № 29/6-VII «2023-2025 жылдарға арналған Жаңа Бұқтырма кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189913/rus
