act_code: '125142'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 12 сентября 2018 года № 25/218-VI. Зарегистрировано Управлением юстиции Жарминского района Департамента юстиции Восточно-Казахстанской области 10 октября 2018 года № 5-10-155. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 10 сентября 2020 года № 49/466-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил определения размера и порядка оказания Жилищной помощи
  kaz: Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-09-12
approved_by:
- '157011000002'
version_date:
  kaz: 2019-10-28
  rus: 2019-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/125142/kaz/28.10.2019
  rus: https://zan.gov.kz/client/#!/doc/125142/rus/28.10.2019
caused_by:
  code: '135842'
  requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 28 октября 2019 года № 39/318-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 7 ноября 2019 года № 6263. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 10 сентября 2020 года № 49/466-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 12 сентября 2018 года № 25/218-VI «Об утверждении Правил определения размера и порядка оказания жилищной помощи»
    kaz: Жарма аудандық мәслихатының 2018 жылғы 12 қыркүйектегі № 25/218-VI «Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау Қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135842/rus
