act_code: '177218'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 27 декабря 2022 года № 204
title:
  rus: О бюджете Уланского района на 2023-2025 годы
  kaz: 2023-2025  жылдарға арналған Ұлан ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '157018000002'
version_date:
  kaz: 2023-06-09
  rus: 2023-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/177218/kaz/09.06.2023
  rus: https://zan.gov.kz/client/#!/doc/177218/rus/09.06.2023
caused_by:
  code: '182826'
  requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 9 июня 2023 года № 25
  title:
    rus: О внесении изменений в решение Уланского районного маслихата «О бюджете Уланского района на 2023-2025 годы» от 27 декабря 2022 года № 204
    kaz: Ұлан аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 204 «2023-2025 жылдарға арналған Ұлан ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182826/rus
