act_code: '147278'
requisite: Решение акима Калбатауского сельского округа Жарминского района Восточно-Казахстанской области от 1 октября 2020 года № 10. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 12 октября 2020 года № 7634
title:
  rus: О присвоении наименования парку в селе Калбатау Жарминского района
  kaz: Жарма ауданы Қалбатау ауылындағы саябаққа атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-10-01
approved_by:
- '157011008002'
version_date:
  kaz: 2020-10-01
  rus: 2020-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/147278/kaz/01.10.2020
  rus: https://zan.gov.kz/client/#!/doc/147278/rus/01.10.2020
