act_code: '79816'
requisite: Решение Восточно-Казахстанского областного маслихата от 11 апреля 2014 года № 19/220-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 13 мая 2014 года N 3317. Утратило силу  решением Восточно-Казахстанского областного маслихата от 22 августа 2022 года № 18/155-VІІ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил содержания и выгула собак и кошек в населенных пунктах Восточно-Казахстанской области
  kaz: Шығыс Қазақстан облысының елді мекендерінде иттер мен мысықтарды асырау және серуендету қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-04-11
approved_by:
- '157000000002'
version_date:
  kaz: 2015-04-17
  rus: 2015-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/79816/kaz/17.04.2015
  rus: https://zan.gov.kz/client/#!/doc/79816/rus/17.04.2015
caused_by:
  code: '89692'
  requisite: Решение Восточно-Казахстанского областного маслихата от 17 апреля 2015 года № 27/328-V. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 13 мая 2015 года N 3933. Утратило силу  решением Восточно-Казахстанского областного маслихата от 22 августа 2022 года № 18/155-VІІ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в некоторые  решения Восточно-Казахстанского  областного маслихата
    kaz: Шығыс Қазақстан облыстық мәслихатының кейбір шешімдеріне  өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/89692/rus
