act_code: '138541'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 31 декабря 2019 года № 38/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 января 2020 года № 6507. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 31 декабря 2020 года № 56/2-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджетах поселков и сельских округов Глубоковского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Глубокое ауданының кенттер мен ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-31
approved_by:
- '157010000002'
version_date:
  kaz: 2020-11-17
  rus: 2020-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/138541/kaz/17.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138541/rus/17.11.2020
caused_by:
  code: '148948'
  requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 17 ноября 2020 года № 52/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 25 ноября 2020 года № 7859. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 31 декабря 2020 года № 56/2-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Глубоковского районного маслихата от 31 декабря 2019 года № 38/2-VI «О бюджетах поселков и сельских округов Глубоковского района на 2020-2022 годы»
    kaz: Глубокое аудандық мәслихатының 2019 жылғы 31 желтоқсандағы № 38/2-VІ «2020-2022 жылдарға арналған Глубокое ауданының кенттер мен ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148948/rus
