act_code: '138541'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 31 декабря 2019 года № 38/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 15 января 2020 года № 6507. Утратило силу решением Глубоковского районного маслихата Восточно-Казахстанской области от 31 декабря 2020 года № 56/2-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджетах поселков и сельских округов Глубоковского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Глубокое ауданының кенттер мен ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-31
approved_by:
- '157010000002'
version_date:
  kaz: 2019-12-31
  rus: 2019-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/138541/kaz/31.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138541/rus/31.12.2019
