act_code: '109636'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 23 декабря 2016 года № 8/68-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 26 января 2017 года № 4847. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области  от 25 октября 2021 года № 8/123-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану
  kaz: Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-23
approved_by:
- '157007000002'
version_date:
  kaz: 2019-11-29
  rus: 2019-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/109636/kaz/29.11.2019
  rus: https://zan.gov.kz/client/#!/doc/109636/rus/29.11.2019
caused_by:
  code: '136924'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 29 ноября 2019 года № 41/287-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 декабря 2019 года № 6379. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области  от 25 октября 2021 года № 8/123-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 23 декабря 2016 года № 8/68-VІ «О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану»
    kaz: Аягөз аудандық мәслихатының 2016 жылғы 23 желтоқсандағы № 8/68-VІ «Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын айқындау туралы» шешiмiне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136924/rus
