act_code: '122242'
requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 17 мая 2018 года № 30/8-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 1 июня 2018 года № 5641. Утратило силу решением Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 9 апреля 2020 года № 54/10-VI (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-05-17
approved_by:
- '157002000002'
version_date:
  kaz: 2019-05-31
  rus: 2019-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/122242/kaz/31.05.2019
  rus: https://zan.gov.kz/client/#!/doc/122242/rus/31.05.2019
caused_by:
  code: '132209'
  requisite: Решение Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 31 мая 2019 года № 44/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 7 июня 2019 года № 5995. Утратило силу решением Усть-Каменогорского городского маслихата Восточно-Казахстанской области от 9 апреля 2020 года № 54/10-VI (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в решение Усть-Каменогорского городского маслихата от 17 мая 2018 года № 30/8-VI «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Өскемен қалалық мәслихатының 2018 жылғы 17 мамырдағы № 30/8-VІ «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132209/rus
