act_code: '125977'
requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 16 ноября 2018 года № 34-353/VI. Зарегистрировано Управлением юстиции Урджарского района Департамента юстиции Восточно-Казахстанской области 16 ноября 2018 года № 5-18-181. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 24 июня 2020 года № 53-656/VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования); Действие решения приостановлено решением Урджарского районного маслихата Восточно-Казахстанской области от 23 апреля 2020 года № 52-633/VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Урджарского района
  kaz: Үржар ауданының ауылдық елді  мекендерінде тұратын  және жұмыс  істейтін мемлекеттік денсаулық сақтау,  әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт  және ветеринария  ұйымдарының мамандарына коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу әлеуметтік қолдау көрсету тәртібі  мен мөлшерін  бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2018-11-16
approved_by:
- '157019000002'
version_date:
  kaz: 2020-04-23
  rus: 2020-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/125977/kaz/23.04.2020
  rus: https://zan.gov.kz/client/#!/doc/125977/rus/23.04.2020
caused_by:
  code: '142590'
  requisite: Решение Урджарского районного маслихата Восточно-Казахстанской области от 23 апреля 2020 года № 52-633/VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 4 мая 2020 года № 7040. Утратило силу решением Урджарского районного маслихата Восточно-Казахстанской области от 24 июня 2020 года № 53-656/VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О приостановлении действия решения Урджарского районного маслихата от 16 ноября 2018 года № 34-353/VI «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального  обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Урджарского района»
    kaz: Үржар аудандық мәслихатының 2018 жылғы 16 қарашадағы № 34-353/VI «Үржар ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт  және ветеринария ұйымдарының мамандарына коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу әлеуметтік қолдау көрсету тәртібі  мен мөлшерін бекіту туралы» шешімінің қолданылуын тоқтата тұру туралы
  link: https://zan.gov.kz/client/#!/doc/142590/rus
