act_code: '139211'
requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 13 января 2020 года № 42/353-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 20 января 2020 года № 6645. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 53/542-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Божыгурского сельского округа Жарминского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Жарма ауданы Божығұр ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '157011000002'
version_date:
  kaz: 2020-09-10
  rus: 2020-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/139211/kaz/10.09.2020
  rus: https://zan.gov.kz/client/#!/doc/139211/rus/10.09.2020
caused_by:
  code: '146480'
  requisite: Решение Жарминского районного маслихата Восточно-Казахстанской области от 10 сентября 2020 года № 49/456-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 сентября 2020 года № 7547. Утратило силу решением Жарминского районного маслихата Восточно-Казахстанской области от 30 декабря 2020 года № 53/542-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 13 января 2020 года № 42/353-VI «О бюджете Божыгурского сельского округа Жарминского района на 2020-2022 годы»
    kaz: Жарма аудандық мәслихатының 2020 жылғы 13 қаңтардағы № 42/353-VI «2020-2022 жылдарға арналған Жарма ауданы Божығұр ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146480/rus
