act_code: '138785'
requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 10 января 2020 года № 43/312-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 17 января 2020 года № 6591. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/541-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджете Косагашского сельского округа Аягозского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Аягөз ауданының Қосағаш ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '157007000002'
version_date:
  kaz: 2020-06-02
  rus: 2020-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/138785/kaz/02.06.2020
  rus: https://zan.gov.kz/client/#!/doc/138785/rus/02.06.2020
caused_by:
  code: '143751'
  requisite: Решение Аягозского районного маслихата Восточно-Казахстанской области от 2 июня 2020 года № 48/391-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 11 июня 2020 года № 7179. Утратило силу решением Аягозского районного маслихата Восточно-Казахстанской области от 25 декабря 2020 года № 55/541-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 10 января 2020 года № 43/312-VI «О бюджете Косагашского сельского округа Аягозского района на 2020-2022 годы»
    kaz: Аягөз аудандық мәслихатының 2020 жылғы 10 қаңтардағы № 43/312-VІ «2020-2022 жылдарға арналған Аягөз ауданының Қосағаш ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143751/rus
