act_code: '197340'
requisite: Решение Глубоковского районного маслихата Восточно-Казахстанской области от 5 июня 2024 года № 12/7-VIII
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Глубоковскому району
  kaz: Глубокое ауданы бойынша халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-05
approved_by:
- '157010000002'
version_date:
  kaz: 2024-06-05
  rus: 2024-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/197340/kaz/05.06.2024
  rus: https://zan.gov.kz/client/#!/doc/197340/rus/05.06.2024
