act_code: '126494'
requisite: Решение акима Зайсанского района Восточно-Казахстанской области от 26 ноября 2018 года № 15. Зарегистрировано Управлением юстиции Зайсанского района Департамента юстиции Восточно-Казахстанской области 29 ноября 2018 года № 5-11-172
title:
  rus: Об образовании избирательных участков по Зайсанскому району
  kaz: Зайсан ауданы бойынша сайлау учаскелерiн құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-26
approved_by:
- '157012000003'
version_date:
  kaz: 2021-07-13
  rus: 2021-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/126494/kaz/13.07.2021
  rus: https://zan.gov.kz/client/#!/doc/126494/rus/13.07.2021
caused_by:
  code: '156965'
  requisite: Решение акима Зайсанского района Восточно-Казахстанской области от 13 июля 2021 года № 9. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 июля 2021 года № 23487
  title:
    rus: О внесении изменения в решение акима Зайсанского района от 26 ноября 2018 года № 15 «Об образовании избирательных участков по Зайсанскому району»
    kaz: Зайсан ауданы әкімінің 2018 жылғы 26 қарашадағы № 15 «Зайсан ауданы бойынша сайлау учаскелерiн құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156965/rus
