act_code: '55765'
requisite: Шығыс Қазақстан облысы Көкпекті аудандық мәслихатының 2010 жылғы 2 қарашадағы № 25-4/2 шешімі. Шығыс Қазақстан облысы Әділет департаментінің Көкпекті аудандық әділет басқармасында 2010 жылғы 7 желтоқсанда № 5-15-77 тіркелді. Күші жойылды - Көкпекті аудандық мәслихатының 2012 жылғы 6 маусымдағы № 4-2 шешімімен
title:
  rus: Көкпекті ауданындағы елді мекендердің аумақтарын көріктендіру, инфрақұрылым объектілерін сақтау және жасыл желектерді күтіп ұстау мен қорғау Ережесін бекіту туралы
  kaz: Көкпекті ауданындағы елді мекендердің аумақтарын көріктендіру, инфрақұрылым объектілерін сақтау және жасыл желектерді күтіп ұстау мен қорғау Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-11-02
approved_by:
- '157015000002'
version_date:
  kaz: 2010-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/55765/kaz/02.11.2010
