act_code: '58156'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 19 марта 2011 года № 35/5-IV. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 12 апреля 2011 года за № 5-19-147. Утратило силу решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 5 июля 2018 года № 26/9-VI
title:
  rus: Об установлении категории автостоянок (паркингов), увеличения размеров ставок налога на земли, выделенные под автостоянки (паркинги)
  kaz: Автотұрақтар (паркингтер) санатын белгілеу, автотұрақтар (паркингтер) үшін бөлінген жерлерге арналған салық ставкаларының мөлшерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-19
approved_by:
- '157020000002'
version_date:
  kaz: 2011-03-19
  rus: 2011-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/58156/kaz/19.03.2011
  rus: https://zan.gov.kz/client/#!/doc/58156/rus/19.03.2011
