act_code: '58156'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 19 марта 2011 года № 35/5-IV. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 12 апреля 2011 года за № 5-19-147. Утратило силу решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 5 июля 2018 года № 26/9-VI
title:
  rus: Об установлении категории автостоянок (паркингов), увеличения размеров ставок налога на земли, выделенные под автостоянки (паркинги)
  kaz: Автотұрақтар (паркингтер) санатын белгілеу, автотұрақтар (паркингтер) үшін бөлінген жерлерге арналған салық ставкаларының мөлшерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-19
approved_by:
- '157020000002'
version_date:
  kaz: 2011-12-21
  rus: 2011-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/58156/kaz/21.12.2011
  rus: https://zan.gov.kz/client/#!/doc/58156/rus/21.12.2011
caused_by:
  code: '62472'
  requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 21 декабря 2011 года № 41/8-IV. Зарегистрировано Управлением юстиции Шемонаихинского района Департамента юстиции Восточно-Казахстанской области 5 января 2012 года за № 5-19-161. Утратило силу решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 5 июля 2018 года № 26/9-VI
  title:
    rus: О внесении изменения в решение от 19 марта 2011 года № 35/5-IV "О ставках налога на земли, выделенные под автостоянки (паркинги)"
    kaz: '"Автотұрақтар (паркингтер) үшін бөлінген жерлерге арналған салық ставкалары туралы" 2011 жылғы 19 наурыздағы № 35/5-IV шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/62472/rus
