act_code: '127582'
requisite: Решение Уланского районного маслихата Восточно-Казахстанской области от 30 ноября 2018 года № 250. Зарегистрировано Управлением юстиции Уланского района Департамента юстиции Восточно-Казахстанской области 25 декабря 2018 года № 5-17-210. Утратило силу решением Уланского районного маслихата Восточно-Казахстанской области от 27 декабря 2023 года № 104 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Уланскому району
  kaz: Ұлан ауданы бойынша пайдаланылмайтын ауыл шаруашылық мақсатындағы жерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемесін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-30
approved_by:
- '157018000002'
version_date:
  kaz: 2018-11-30
  rus: 2018-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/127582/kaz/30.11.2018
  rus: https://zan.gov.kz/client/#!/doc/127582/rus/30.11.2018
