act_code: '1018'
requisite: Решение Акима Восточно-Казахстанской области от 27 января 1998 года N 461-К. Зарегистрировано управлением юстиции Восточно-Казахстанской области 15 мая 1998 года за N 20. Утратило силу решением акима ВКО от 24 сентября 2004 года N 100
title:
  rus: О состоянии организаторской и практической работы Акимов г.г.Семипалатинска и Курчатова по выполнению Программы Акима области по углублению реформ на 1997-1998 годы в свете  Послания Президента страны народу Казахстана
  kaz: Семей, Курчатов қалалары әкімдерінің Қазақстан Республикасы Президентінің Қазақстан халқына Жолдауы тұрғысында облыс әкімінің реформаларды тереңдету жөнінде 1997-1998 жылдарға арналған Бағдарламасын орындау жөніндегі ұйымдастыру және практикалық жұмысының жағдайы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-01-27
approved_by:
- '157000000001'
version_date:
  kaz: 1998-01-27
  rus: 1998-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/1018/kaz/27.01.1998
  rus: https://zan.gov.kz/client/#!/doc/1018/rus/27.01.1998
