act_code: '96243'
requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 29 сентября 2015 года № 38-6/3. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 23 октября 2015 года № 4190. Утратило силу решением Зайсанского районного маслихата Восточно-Казахстанской области от 22 июня 2023 года № 01-02/VIII-6-6/4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норм образования, накопления коммунальных отходов и тарифы на сбор, вывоз, захоронение твердых бытовых отходов по городу Зайсан
  kaz: Зайсан қаласы бойынша коммуналдық қалдықтардың пайда болу және жинақталу нормаларын және тұрмыстық қатты қалдықтарды жинау, әкету, көму тарифтерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-29
approved_by:
- '157012000002'
version_date:
  kaz: 2016-06-10
  rus: 2016-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/96243/kaz/10.06.2016
  rus: https://zan.gov.kz/client/#!/doc/96243/rus/10.06.2016
caused_by:
  code: '104707'
  requisite: Решение Зайсанского районного маслихата Восточно-Казахстанской области от 10 июня 2016 года № 3-5/2. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 21 июля 2016 года № 4605. Утратило силу решением Зайсанского районного маслихата Восточно-Казахстанской области от 22 июня 2023 года № 01-02/VIII-6-6/4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Зайсанского районного  маслихата от 29 сентября 2015 года № 38-6/3 «Об утверждении норм образования, накопления коммунальных отходов и тарифы на сбор, вывоз, захоронение коммунальных отходов по городу Зайсан»
    kaz: '"Зайсан қаласы бойынша коммуналдық қалдықтардың пайда болу және жинақталу нормаларын және коммуналдық қалдықтарды жинау, әкету, көму тарифтерін бекіту туралы" 2015 жылғы 29 қыркүйектегі № 38-6/3 Зайсан аудандық мәслихатының шешіміне өзгерістер енгізу туралы.'
  link: https://zan.gov.kz/client/#!/doc/104707/rus
