act_code: '139108'
requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 13 января 2020 года № 49/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 27 января 2020 года № 6700. Утратило силу решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 12 января 2021 года № 61/2-VI (вводится в действие с 01.01.2021)
title:
  rus: О бюджетах города, поселков и сельских округов Шемонаихинского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Шемонаиха ауданының қала, кенттер және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '157020000002'
version_date:
  kaz: 2020-07-02
  rus: 2020-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/139108/kaz/02.07.2020
  rus: https://zan.gov.kz/client/#!/doc/139108/rus/02.07.2020
caused_by:
  code: '144890'
  requisite: Решение Шемонаихинского районного маслихата Восточно-Казахстанской области от 2 июля 2020 года № 54/2-VI. Зарегистрировано Департаментом юстиции Восточно-Казахстанской области 14 июля 2020 года № 7360. Утратило силу решением Шемонаихинского районного маслихата Восточно-Казахстанской области от 12 января 2021 года № 61/2-VI (вводится в действие с 01.01.2021)
  title:
    rus: О внесении изменений в решение Шемонаихинского районного маслихата от 13 января 2020 года № 49/2-VI «О бюджетах города, поселков и сельских округов Шемонаихинского района на 2020-2022 годы»
    kaz: Шемонаиха аудандық мәслихатының 2020 жылғы 13 қаңтардағы № 49/2-VI «2020-2022 жылдарға арналған Шемонаиха ауданының қала, кенттер және ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144890/rus
